// ==========================================================================
//                 SeqAn - The Library for Sequence Analysis
// ==========================================================================
// Copyright (c) 2006-2010, Knut Reinert, FU Berlin
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
//     * Redistributions of source code must retain the above copyright
//       notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above copyright
//       notice, this list of conditions and the following disclaimer in the
//       documentation and/or other materials provided with the distribution.
//     * Neither the name of Knut Reinert or the FU Berlin nor the names of
//       its contributors may be used to endorse or promote products derived
//       from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL KNUT REINERT OR THE FU BERLIN BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
// LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
// OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
// DAMAGE.
//
// ==========================================================================


#ifndef SEQAN_HEADER_SEQ_IO_GENERATED_FORWARDS_H 
#define SEQAN_HEADER_SEQ_IO_GENERATED_FORWARDS_H 

//////////////////////////////////////////////////////////////////////////////
// NOTE: This file is automatically generated by build_forwards.py
//       Do not edit this file manually!
//////////////////////////////////////////////////////////////////////////////


//////////////////////////////////////////////////////////////////////////////
// CLASSES
//////////////////////////////////////////////////////////////////////////////

namespace seqan {

//____________________________________________________________________________
// EmblHeader_

struct EmblHeader_;       	// "core/include/seqan/seq_io/read_embl.h"(55)

//____________________________________________________________________________
// EmblSequence_

struct EmblSequence_;       	// "core/include/seqan/seq_io/read_embl.h"(58)

//____________________________________________________________________________
// FaiIndex

class FaiIndex;       	// "core/include/seqan/seq_io/fai_index.h"(131)

//____________________________________________________________________________
// FaiIndexEntry_

class FaiIndexEntry_;       	// "core/include/seqan/seq_io/fai_index.h"(64)

//____________________________________________________________________________
// GenBankHeader_

struct GenBankHeader_;       	// "core/include/seqan/seq_io/read_genbank.h"(61)

//____________________________________________________________________________
// GenBankSequence_

struct GenBankSequence_;       	// "core/include/seqan/seq_io/read_genbank.h"(64)

//____________________________________________________________________________
// GenBank_

struct GenBank_;       	// "core/include/seqan/seq_io/read_genbank.h"(58)

//____________________________________________________________________________
// GenomicRegion

class GenomicRegion;       	// "core/include/seqan/seq_io/genomic_region.h"(47)
class GenomicRegion;       	// "core/include/seqan/seq_io/genomic_region.h"(129)

//____________________________________________________________________________
// LimitRecordReaderInScope

template <typename TStream, typename TPass> class LimitRecordReaderInScope;       	// "core/include/seqan/seq_io/guess_stream_format.h"(106)

//____________________________________________________________________________
// MetaFirstChar_

template <typename TTag> struct MetaFirstChar_;       	// "core/include/seqan/seq_io/read_fasta_fastq.h"(75)

//____________________________________________________________________________
// SeqIOFileFormat_

struct SeqIOFileFormat_;       	// "core/include/seqan/seq_io/sequence_stream_impl.h"(75)

//____________________________________________________________________________
// SeqIOFileType_

struct SeqIOFileType_;       	// "core/include/seqan/seq_io/sequence_stream_impl.h"(57)

//____________________________________________________________________________
// SequenceStream

class SequenceStream;       	// "core/include/seqan/seq_io/sequence_stream.h"(118)

//____________________________________________________________________________
// SequenceStreamImpl_

class SequenceStreamImpl_;       	// "core/include/seqan/seq_io/sequence_stream_impl.h"(95)

//____________________________________________________________________________
// TagFasta_

struct TagFasta_;       	// "core/include/seqan/seq_io/read_fasta_fastq.h"(58)

//____________________________________________________________________________
// TagFastq_

struct TagFastq_;       	// "core/include/seqan/seq_io/read_fasta_fastq.h"(66)

} //namespace seqan


//////////////////////////////////////////////////////////////////////////////
// TYPEDEFS
//////////////////////////////////////////////////////////////////////////////

namespace seqan {

//____________________________________________________________________________
// AutoSeqStreamFormat

typedef TagSelector<SeqStreamFormats>    AutoSeqStreamFormat;       	// "core/include/seqan/seq_io/guess_stream_format.h"(82)

//____________________________________________________________________________
// EmblHeader

typedef Tag<EmblHeader_> EmblHeader;       	// "core/include/seqan/seq_io/read_embl.h"(56)

//____________________________________________________________________________
// EmblSequence

typedef Tag<EmblSequence_> EmblSequence;       	// "core/include/seqan/seq_io/read_embl.h"(59)

//____________________________________________________________________________
// Fasta

typedef Tag<TagFasta_> const Fasta;       	// "core/include/seqan/seq_io/read_fasta_fastq.h"(59)

//____________________________________________________________________________
// Fastq

typedef Tag<TagFastq_> const Fastq;       	// "core/include/seqan/seq_io/read_fasta_fastq.h"(67)

//____________________________________________________________________________
// GenBank

typedef Tag<GenBank_> GenBank;       	// "core/include/seqan/seq_io/read_genbank.h"(59)

//____________________________________________________________________________
// GenBankHeader

typedef Tag<GenBankHeader_> GenBankHeader;       	// "core/include/seqan/seq_io/read_genbank.h"(62)

//____________________________________________________________________________
// GenBankSequence

typedef Tag<GenBankSequence_> GenBankSequence;       	// "core/include/seqan/seq_io/read_genbank.h"(65)

//____________________________________________________________________________
// SeqStreamFormats

typedef TagList<Fastq, TagList<Fasta > >  SeqStreamFormats;       	// "core/include/seqan/seq_io/guess_stream_format.h"(61)

} //namespace seqan


//////////////////////////////////////////////////////////////////////////////
// FUNCTIONS
//////////////////////////////////////////////////////////////////////////////

namespace seqan {

//____________________________________________________________________________
// _clearAndReserveMemory

template <typename TIdString, typename TSeqString, typename TFile, typename TSpec, typename TTag> inline int _clearAndReserveMemory(TIdString & meta, TSeqString & seq, RecordReader<TFile, SinglePass<TSpec> > & , TTag const & );       	// "core/include/seqan/seq_io/read_fasta_fastq.h"(169)
template <typename TIdString, typename TSeqString, typename TFile, typename TSpec, typename TTag> inline int _clearAndReserveMemory(TIdString & meta, TSeqString & seq, RecordReader<TFile, DoublePass<TSpec> > & reader, TTag const & );       	// "core/include/seqan/seq_io/read_fasta_fastq.h"(185)
template <typename TIdString, typename TSeqString, typename TQualString, typename TFile, typename TSpec, typename TTag> inline int _clearAndReserveMemory(TIdString & meta, TSeqString & seq, TQualString & qual, RecordReader<TFile, TSpec> & reader, TTag const & tag);       	// "core/include/seqan/seq_io/read_fasta_fastq.h"(221)

//____________________________________________________________________________
// _countMetaAndSequence

template <typename TSeqAlph, typename TFile, typename TSpec, typename TTag> inline int _countMetaAndSequence(unsigned int & metaLength, unsigned int & seqLength, RecordReader<TFile, DoublePass<TSpec> > & reader, TTag const & , TSeqAlph const & );       	// "core/include/seqan/seq_io/read_fasta_fastq.h"(127)

//____________________________________________________________________________
// _countSequenceFastAQ

template <typename TRecordReader> inline int _countSequenceFastAQ(unsigned int & count, TRecordReader & reader, char const & );       	// "core/include/seqan/seq_io/read_fasta_fastq.h"(103)
template <typename TAlph, typename TRecordReader> inline int _countSequenceFastAQ(unsigned int & count, TRecordReader & reader, TAlph const & );       	// "core/include/seqan/seq_io/read_fasta_fastq.h"(113)

//____________________________________________________________________________
// _readFastAQ

template <typename TIdString, typename TSeqString, typename TQualString, typename TFile, typename TSpec, typename TTag> int _readFastAQ(StringSet<TIdString, Owner<ConcatDirect<> > > & sequenceIds, StringSet<TSeqString, Owner<ConcatDirect<> > > & sequences, StringSet<TQualString, Owner<ConcatDirect<> > > & qualities, RecordReader<TFile, DoublePass<TSpec> > & reader, bool const withQual, TTag const & );       	// "core/include/seqan/seq_io/read_fasta_fastq.h"(593)
template <typename TIdString, typename TIdSpec, typename TSeqString, typename TSeqSpec, typename TQualString, typename TQualSpec, typename TFile, typename TSpec, typename TTag> int _readFastAQ(StringSet<TIdString, TIdSpec> & sequenceIds, StringSet<TSeqString, TSeqSpec> & sequences, StringSet<TQualString, TQualSpec> & qualities, RecordReader<TFile, DoublePass<TSpec> > & reader, bool const withQual, TTag const & );       	// "core/include/seqan/seq_io/read_fasta_fastq.h"(705)

//____________________________________________________________________________
// _readFastAQQualityReadDispatcher

template <typename TIdString, typename TSeqString, typename TQualString, typename TRecordReader> inline int _readFastAQQualityReadDispatcher(StringSet<TIdString, Owner<ConcatDirect<> > > & sequenceIds, StringSet<TSeqString, Owner<ConcatDirect<> > > & sequences, StringSet<TQualString, Owner<ConcatDirect<> > > & , TRecordReader & reader, unsigned i, True const & );       	// "core/include/seqan/seq_io/read_fasta_fastq.h"(561)
template <typename TIdString, typename TSeqString, typename TQualString, typename TRecordReader> inline int _readFastAQQualityReadDispatcher(StringSet<TIdString, Owner<ConcatDirect<> > > & sequenceIds, StringSet<TSeqString, Owner<ConcatDirect<> > > & sequences, StringSet<TQualString, Owner<ConcatDirect<> > > & qualities, TRecordReader & reader, unsigned i, False const & );       	// "core/include/seqan/seq_io/read_fasta_fastq.h"(577)

//____________________________________________________________________________
// _readMetaAndSequence

template <typename TIdString, typename TSeqString, typename TFile, typename TPass, typename TTag> inline int _readMetaAndSequence(TIdString & meta, TSeqString & seq, RecordReader<TFile, TPass > & reader, TTag const & );       	// "core/include/seqan/seq_io/read_fasta_fastq.h"(269)

//____________________________________________________________________________
// _readQualityBlock

template <typename TIdString, typename TQualString, typename TFile, typename TPass> inline int _readQualityBlock(TQualString & qual, RecordReader<TFile, TPass > & reader, unsigned const seqLength, TIdString const & meta, Fastq const & );       	// "core/include/seqan/seq_io/read_fasta_fastq.h"(390)

//____________________________________________________________________________
// _readQualityBlockHelper

template <typename TSeqString, typename TFile, typename TPass> inline int _readQualityBlockHelper(TSeqString & seq, RecordReader<TFile, TPass > & reader, unsigned const seqLength, True const & );       	// "core/include/seqan/seq_io/read_fasta_fastq.h"(341)
template <typename TQualString, typename TFile, typename TPass> inline int _readQualityBlockHelper(TQualString & qual, RecordReader<TFile, TPass > & reader, unsigned const seqLength, False const & );       	// "core/include/seqan/seq_io/read_fasta_fastq.h"(375)

//____________________________________________________________________________
// _readSequenceFastAQ

template <typename TSpec, typename TRecordReader> inline int _readSequenceFastAQ(String<char, TSpec> & string, TRecordReader & reader);       	// "core/include/seqan/seq_io/read_fasta_fastq.h"(237)
template <typename TAlph, typename TSpec, typename TRecordReader> inline int _readSequenceFastAQ(String<TAlph, TSpec> & string, TRecordReader & reader);       	// "core/include/seqan/seq_io/read_fasta_fastq.h"(246)
template <typename TString, typename TRecordReader> inline int _readSequenceFastAQ(TString & string, TRecordReader & reader);       	// "core/include/seqan/seq_io/read_fasta_fastq.h"(255)

//____________________________________________________________________________
// _skipQualityBlock

template <typename TFile, typename TPass> inline int _skipQualityBlock(RecordReader<TFile, TPass > & , unsigned const , Fasta const & );       	// "core/include/seqan/seq_io/read_fasta_fastq.h"(305)
template <typename TFile, typename TPass> inline int _skipQualityBlock(RecordReader<TFile, TPass > & reader, unsigned const seqLength, Fastq const & );       	// "core/include/seqan/seq_io/read_fasta_fastq.h"(315)

//____________________________________________________________________________
// _writeRecordFastq

template <typename TStream, typename TSequence, typename TQualString> inline int _writeRecordFastq(TStream & stream, TSequence const & seq, TQualString const &, unsigned const options, True const & );       	// "core/include/seqan/seq_io/write_fasta_fastq.h"(170)
template <typename TStream, typename TSequence, typename TQualString> inline int _writeRecordFastq(TStream & stream, TSequence const & seq, TQualString const & qual, unsigned const options, False const & );       	// "core/include/seqan/seq_io/write_fasta_fastq.h"(212)

//____________________________________________________________________________
// atEnd

inline bool atEnd(SequenceStream const & seqIO);       	// "core/include/seqan/seq_io/sequence_stream.h"(273)
inline bool atEnd(SequenceStream & seqIO);       	// "core/include/seqan/seq_io/sequence_stream.h"(279)

//____________________________________________________________________________
// build

inline int build(FaiIndex & index, char const * seqFilename, char const * faiFilename);       	// "core/include/seqan/seq_io/fai_index.h"(651)
inline int build(FaiIndex & index, char const * seqFilename);       	// "core/include/seqan/seq_io/fai_index.h"(729)

//____________________________________________________________________________
// checkStreamFormat

template <typename TRecordReader > inline bool checkStreamFormat(TRecordReader & reader, TagSelector<> & formats);       	// "core/include/seqan/seq_io/guess_stream_format.h"(285)
template <typename TRecordReader, typename TTagList > inline bool checkStreamFormat(TRecordReader & reader, TagSelector<TTagList> & formats);       	// "core/include/seqan/seq_io/guess_stream_format.h"(294)
template <typename TStream, typename TPass> inline bool checkStreamFormat(RecordReader<TStream, TPass> & reader, Fasta const & );       	// "core/include/seqan/seq_io/read_fasta_fastq.h"(960)
template <typename TStream, typename TPass> inline bool checkStreamFormat(RecordReader<TStream, TPass> & reader, Fastq const & );       	// "core/include/seqan/seq_io/read_fasta_fastq.h"(977)

//____________________________________________________________________________
// clear

inline void clear(FaiIndex & index);       	// "core/include/seqan/seq_io/fai_index.h"(176)
inline void clear(GenomicRegion & region);       	// "core/include/seqan/seq_io/genomic_region.h"(176)

//____________________________________________________________________________
// close

inline void close(SequenceStream & seqIO);       	// "core/include/seqan/seq_io/sequence_stream.h"(233)

//____________________________________________________________________________
// flush

inline void flush(SequenceStream & seqIO);       	// "core/include/seqan/seq_io/sequence_stream.h"(252)

//____________________________________________________________________________
// getAutoSeqStreamFormatName

inline char const * getAutoSeqStreamFormatName(AutoSeqStreamFormat const & format);       	// "core/include/seqan/seq_io/guess_stream_format.h"(216)

//____________________________________________________________________________
// getIdByName

template <typename TName, typename TId> inline bool getIdByName(FaiIndex & index, TName const & name, TId & id);       	// "core/include/seqan/seq_io/fai_index.h"(210)
template <typename TName, typename TId> inline bool getIdByName(FaiIndex const & index, TName const & name, TId & id);       	// "core/include/seqan/seq_io/fai_index.h"(216)

//____________________________________________________________________________
// isGood

inline bool isGood(SequenceStream const & seqIO);       	// "core/include/seqan/seq_io/sequence_stream.h"(300)

//____________________________________________________________________________
// nextIs

template <typename TStream, typename TSpec> inline bool nextIs(RecordReader<TStream, TSpec> & reader, EmblHeader const & );       	// "core/include/seqan/seq_io/read_embl.h"(127)
template <typename TStream, typename TSpec> inline bool nextIs(RecordReader<TStream, TSpec> & reader, EmblSequence const & );       	// "core/include/seqan/seq_io/read_embl.h"(136)
template <typename TStream, typename TSpec> inline bool nextIs(RecordReader<TStream, TSpec> & reader, GenBankHeader const & );       	// "core/include/seqan/seq_io/read_genbank.h"(137)
template <typename TStream, typename TSpec> inline bool nextIs(RecordReader<TStream, TSpec> & reader, GenBankSequence const & );       	// "core/include/seqan/seq_io/read_genbank.h"(146)

//____________________________________________________________________________
// numSeqs

inline __uint64 numSeqs(FaiIndex const & index);       	// "core/include/seqan/seq_io/fai_index.h"(292)

//____________________________________________________________________________
// parse

inline bool parse(GenomicRegion & region, CharString const & regionString);       	// "core/include/seqan/seq_io/genomic_region.h"(206)

//____________________________________________________________________________
// read

inline int read(FaiIndex & index, char const * fastaFilename, char const * faiFilename);       	// "core/include/seqan/seq_io/fai_index.h"(443)
inline int read(FaiIndex & index, char * fastaFilename, char const * faiFilename);       	// "core/include/seqan/seq_io/fai_index.h"(535)
inline int read(FaiIndex & index, char const * fastaFilename, char * faiFilename);       	// "core/include/seqan/seq_io/fai_index.h"(540)
inline int read(FaiIndex & index, char * fastaFilename, char * faiFilename);       	// "core/include/seqan/seq_io/fai_index.h"(545)
inline int read(FaiIndex & index, char const * fastaFilename);       	// "core/include/seqan/seq_io/fai_index.h"(550)
inline int read(FaiIndex & index, char * fastaFilename);       	// "core/include/seqan/seq_io/fai_index.h"(557)
inline int read(FaiIndex & index);       	// "core/include/seqan/seq_io/fai_index.h"(562)

//____________________________________________________________________________
// read2

template <typename TIdString, typename TIdSpec, typename TSeqString, typename TSeqSpec, typename TStream, typename TSpec> int read2(StringSet<TIdString, TIdSpec> & sequenceIds, StringSet<TSeqString, TSeqSpec> & sequences, RecordReader<TStream, SinglePass<TSpec> > & reader, Embl const & tag);       	// "core/include/seqan/seq_io/read_embl.h"(237)
template <typename TIdString, typename TIdSpec, typename TSeqString, typename TSeqSpec, typename TFile, typename TSpec> int read2(StringSet<TIdString, TIdSpec> & sequenceIds, StringSet<TSeqString, TSeqSpec> & sequences, RecordReader<TFile, DoublePass<TSpec> > & reader, Fasta const & );       	// "core/include/seqan/seq_io/read_fasta_fastq.h"(808)
template <typename TIdString, typename TIdSpec, typename TSeqString, typename TSeqSpec, typename TQualString, typename TQualSpec, typename TFile, typename TSpec> int read2(StringSet<TIdString, TIdSpec> & sequenceIds, StringSet<TSeqString, TSeqSpec> & sequences, StringSet<TQualString, TQualSpec> & qualities, RecordReader<TFile, DoublePass<TSpec> > & reader, Fasta const & );       	// "core/include/seqan/seq_io/read_fasta_fastq.h"(823)
template <typename TIdString, typename TIdSpec, typename TSeqString, typename TSeqSpec, typename TFile, typename TSpec> int read2(StringSet<TIdString, TIdSpec> & sequenceIds, StringSet<TSeqString, TSeqSpec> & sequences, RecordReader<TFile, DoublePass<TSpec> > & reader, Fastq const & );       	// "core/include/seqan/seq_io/read_fasta_fastq.h"(844)
template <typename TIdString, typename TIdSpec, typename TSeqString, typename TSeqSpec, typename TQualString, typename TQualSpec, typename TFile, typename TSpec> int read2(StringSet<TIdString, TIdSpec> & sequenceIds, StringSet<TSeqString, TSeqSpec> & sequences, StringSet<TQualString, TQualSpec> & qualities, RecordReader<TFile, DoublePass<TSpec> > & reader, Fastq const & );       	// "core/include/seqan/seq_io/read_fasta_fastq.h"(866)
template <typename TIdString, typename TIdSpec, typename TSeqString, typename TSeqSpec, typename TFile, typename TSpec, typename TTag> typename EnableIf<typename Or<typename IsSameType<typename RemoveConst_<TTag>::Type, typename RemoveConst_<Fasta>::Type >::Type, typename IsSameType<typename RemoveConst_<TTag>::Type, typename RemoveConst_<Fastq>::Type >::Type>::Type, int>::Type read2(StringSet<TIdString, TIdSpec> & sequenceIds, StringSet<TSeqString, TSeqSpec> & sequences, RecordReader<TFile, SinglePass<TSpec> > & reader, TTag const & tag);       	// "core/include/seqan/seq_io/read_fasta_fastq.h"(885)
template <typename TIdString, typename TIdSpec, typename TSeqString, typename TSeqSpec, typename TQualString, typename TQualSpec, typename TFile, typename TSpec, typename TTag> int read2(StringSet<TIdString, TIdSpec> & sequenceIds, StringSet<TSeqString, TSeqSpec> & sequences, StringSet<TQualString, TQualSpec> & qualities, RecordReader<TFile, SinglePass<TSpec> > & reader, TTag const & tag);       	// "core/include/seqan/seq_io/read_fasta_fastq.h"(909)
template <typename TIdString, typename TIdSpec, typename TSeqString, typename TSeqSpec, typename TQualString, typename TQualSpec, typename TFile, typename TSpec> int read2(StringSet<TIdString, TIdSpec> & sequenceIds, StringSet<TSeqString, TSeqSpec> & sequences, StringSet<TQualString, TQualSpec> & qualities, RecordReader<TFile, SinglePass<TSpec> > & reader, Fastq const & tag);       	// "core/include/seqan/seq_io/read_fasta_fastq.h"(924)
template <typename TIdString, typename TIdSpec, typename TSeqString, typename TSeqSpec, typename TStream, typename TSpec> int read2(StringSet<TIdString, TIdSpec> & sequenceIds, StringSet<TSeqString, TSeqSpec> & sequences, RecordReader<TStream, SinglePass<TSpec> > & reader, GenBank const & tag);       	// "core/include/seqan/seq_io/read_genbank.h"(269)

//____________________________________________________________________________
// readAll

template <typename TId, typename TIdSpec, typename TSequence, typename TSeqSpec, typename TQualities, typename TQualSpec> int readAll(StringSet<TId, TIdSpec> & ids, StringSet<TSequence, TSeqSpec> & seqs, StringSet<TQualities, TQualSpec> & quals, SequenceStream & seqIO);       	// "core/include/seqan/seq_io/sequence_stream.h"(513)
template <typename TId, typename TIdSpec, typename TSequence, typename TSeqSpec> int readAll(StringSet<TId, TIdSpec> & ids, StringSet<TSequence, TSeqSpec> & seqs, SequenceStream & seqIO);       	// "core/include/seqan/seq_io/sequence_stream.h"(532)

//____________________________________________________________________________
// readBatch

template <typename TId, typename TIdSpec, typename TSequence, typename TSeqSpec, typename TQualities, typename TQualSpec> int readBatch(StringSet<TId, TIdSpec> & ids, StringSet<TSequence, TSeqSpec> & seqs, StringSet<TQualities, TQualSpec> & quals, SequenceStream & seqIO, unsigned num);       	// "core/include/seqan/seq_io/sequence_stream.h"(431)
template <typename TId, typename TIdSpec, typename TSequence, typename TSeqSpec> int readBatch(StringSet<TId, TIdSpec> & ids, StringSet<TSequence, TSeqSpec> & seqs, SequenceStream & seqIO, unsigned num);       	// "core/include/seqan/seq_io/sequence_stream.h"(451)

//____________________________________________________________________________
// readFasta

template <typename TValue, typename TSpec> int readFasta(String<TValue, TSpec> & seq, char const * filename);       	// "core/include/seqan/seq_io/simple_read_fasta.h"(97)

//____________________________________________________________________________
// readRecord

template <typename TTarget, typename TStream, typename TSpec> inline int readRecord(TTarget & buffer, RecordReader<TStream, SinglePass<TSpec> > & reader, EmblHeader const & tag);       	// "core/include/seqan/seq_io/read_embl.h"(150)
template <typename TTarget, typename TStream, typename TSpec> inline int readRecord(TTarget & buffer, RecordReader<TStream, SinglePass<TSpec> > & reader, EmblSequence const & tag);       	// "core/include/seqan/seq_io/read_embl.h"(168)
template <typename TId, typename TSequence, typename TStream, typename TSpec> inline int readRecord(TId & id, TSequence & sequence, RecordReader<TStream, SinglePass<TSpec> > & reader, Embl const & );       	// "core/include/seqan/seq_io/read_embl.h"(206)
template <typename TIdString, typename TSeqString, typename TFile, typename TPass> inline int readRecord(TIdString & meta, TSeqString & seq, RecordReader<TFile, TPass > & reader, Fasta const & );       	// "core/include/seqan/seq_io/read_fasta_fastq.h"(451)
template <typename TIdString, typename TSeqString, typename TQualString, typename TFile, typename TPass> inline int readRecord(TIdString & meta, TSeqString & seq, TQualString & quals, RecordReader<TFile, TPass > & reader, Fasta const & );       	// "core/include/seqan/seq_io/read_fasta_fastq.h"(474)
template <typename TIdString, typename TSeqString, typename TFile, typename TPass> inline int readRecord(TIdString & meta, TSeqString & seq, RecordReader<TFile, TPass > & reader, Fastq const & );       	// "core/include/seqan/seq_io/read_fasta_fastq.h"(497)
template <typename TIdString, typename TSeqString, typename TQualString, typename TFile, typename TPass> inline int readRecord(TIdString & meta, TSeqString & seq, TQualString & qual, RecordReader<TFile, TPass > & reader, Fastq const & );       	// "core/include/seqan/seq_io/read_fasta_fastq.h"(531)
template <typename TTarget, typename TStream, typename TSpec> inline int readRecord(TTarget & result, RecordReader<TStream, SinglePass<TSpec> > & reader, GenBankHeader const & tag);       	// "core/include/seqan/seq_io/read_genbank.h"(162)
template <typename TTarget, typename TStream, typename TSpec> inline int readRecord(TTarget & result, RecordReader<TStream, SinglePass<TSpec> > & reader, GenBankSequence const & tag);       	// "core/include/seqan/seq_io/read_genbank.h"(191)
template <typename TId, typename TSequence, typename TStream, typename TSpec> inline int readRecord(TId & id, TSequence & sequence, RecordReader<TStream, SinglePass<TSpec> > & reader, GenBank const & );       	// "core/include/seqan/seq_io/read_genbank.h"(238)
template <typename TId, typename TSequence, typename TQualities> int readRecord(TId & id, TSequence & seq, TQualities & qual, SequenceStream & seqIO);       	// "core/include/seqan/seq_io/sequence_stream.h"(352)
template <typename TId, typename TSequence> int readRecord(TId & id, TSequence & seq, SequenceStream & seqIO);       	// "core/include/seqan/seq_io/sequence_stream.h"(369)

//____________________________________________________________________________
// readRegion

template <typename TValue, typename TSpec> inline int readRegion(String<TValue, TSpec> & str, FaiIndex const & index, unsigned refId, unsigned beginPos, unsigned endPos);       	// "core/include/seqan/seq_io/fai_index.h"(329)
template <typename TValue, typename TSpec> inline int readRegion(String<TValue, TSpec> & str, FaiIndex const & index, GenomicRegion const & region);       	// "core/include/seqan/seq_io/fai_index.h"(374)

//____________________________________________________________________________
// readSequence

template <typename TValue, typename TSpec> inline int readSequence(String<TValue, TSpec> & str, FaiIndex const & index, unsigned refId);       	// "core/include/seqan/seq_io/fai_index.h"(414)

//____________________________________________________________________________
// sequenceLength

template <typename TRefId> inline __uint64 sequenceLength(FaiIndex const & index, TRefId refId);       	// "core/include/seqan/seq_io/fai_index.h"(240)
template <typename TRefId> inline __uint64 sequenceLength(FaiIndex & index, TRefId refId);       	// "core/include/seqan/seq_io/fai_index.h"(248)

//____________________________________________________________________________
// sequenceName

inline CharString sequenceName(FaiIndex const & index, unsigned refId);       	// "core/include/seqan/seq_io/fai_index.h"(271)

//____________________________________________________________________________
// splitEmblHeader

template <typename TKey, typename TValue, typename TLine> inline void splitEmblHeader(TKey & key, TValue & value, TLine const & line);       	// "core/include/seqan/seq_io/read_embl.h"(93)

//____________________________________________________________________________
// splitGenBankHeader

template <typename TKey, typename TValue, typename TLine> inline void splitGenBankHeader(TKey & key, TValue & value, TLine const & lines);       	// "core/include/seqan/seq_io/read_genbank.h"(101)

//____________________________________________________________________________
// write

inline int write(FaiIndex const & index, char const * faiFilename);       	// "core/include/seqan/seq_io/fai_index.h"(593)
inline int write(FaiIndex const & index, char * faiFilename);       	// "core/include/seqan/seq_io/fai_index.h"(608)
inline int write(FaiIndex & index, char * faiFilename);       	// "core/include/seqan/seq_io/fai_index.h"(613)
inline int write(FaiIndex const & index);       	// "core/include/seqan/seq_io/fai_index.h"(618)
inline int write(FaiIndex & index);       	// "core/include/seqan/seq_io/fai_index.h"(625)

//____________________________________________________________________________
// write2

template <typename TStream, typename TIdString, typename TIdSpec, typename TSeqString, typename TSeqSpec> int write2(TStream & stream, StringSet<TIdString, TIdSpec> const & sequenceIds, StringSet<TSeqString, TSeqSpec> const & sequences, Fasta const & , FastAQOutputOptions const options);       	// "core/include/seqan/seq_io/write_fasta_fastq.h"(417)
template <typename TStream, typename TIdString, typename TIdSpec, typename TSeqString, typename TSeqSpec> int write2(TStream & stream, StringSet<TIdString, TIdSpec> const & sequenceIds, StringSet<TSeqString, TSeqSpec> const & sequences, Fasta const & );       	// "core/include/seqan/seq_io/write_fasta_fastq.h"(445)
template <typename TStream, typename TIdString, typename TIdSpec, typename TSeqString, typename TSeqSpec, typename TQualString, typename TQualSpec> int write2(TStream & stream, StringSet<TIdString, TIdSpec> const & sequenceIds, StringSet<TSeqString, TSeqSpec> const & sequences, StringSet<TQualString, TQualSpec> const & qualities, Fastq const & , FastAQOutputOptions const options);       	// "core/include/seqan/seq_io/write_fasta_fastq.h"(465)
template <typename TStream, typename TIdString, typename TIdSpec, typename TSeqString, typename TSeqSpec, typename TQualString, typename TQualSpec> int write2(TStream & stream, StringSet<TIdString, TIdSpec> const & sequenceIds, StringSet<TSeqString, TSeqSpec> const & sequences, StringSet<TQualString, TQualSpec> const & qualities, Fastq const & );       	// "core/include/seqan/seq_io/write_fasta_fastq.h"(502)
template <typename TStream, typename TIdString, typename TIdSpec, typename TSeqString, typename TSeqSpec> int write2(TStream & stream, StringSet<TIdString, TIdSpec> const & sequenceIds, StringSet<TSeqString, TSeqSpec> const & sequences, Fastq const & , FastAQOutputOptions const options);       	// "core/include/seqan/seq_io/write_fasta_fastq.h"(517)
template <typename TStream, typename TIdString, typename TIdSpec, typename TSeqString, typename TSeqSpec> int write2(TStream & stream, StringSet<TIdString, TIdSpec> const & sequenceIds, StringSet<TSeqString, TSeqSpec> const & sequences, Fastq const & );       	// "core/include/seqan/seq_io/write_fasta_fastq.h"(545)

//____________________________________________________________________________
// writeAll

template <typename TId, typename TIdSpec, typename TSequence, typename TSeqSpec, typename TQualities, typename TQualSpec> int writeAll(SequenceStream & seqIO, StringSet<TId, TIdSpec> const & ids, StringSet<TSequence, TSeqSpec> const & seqs, StringSet<TQualities, TQualSpec> const & quals);       	// "core/include/seqan/seq_io/sequence_stream.h"(731)
template <typename TId, typename TIdSpec, typename TSequence, typename TSeqSpec> int writeAll(SequenceStream & seqIO, StringSet<TId, TIdSpec> const & ids, StringSet<TSequence, TSeqSpec> const & seqs);       	// "core/include/seqan/seq_io/sequence_stream.h"(749)

//____________________________________________________________________________
// writeRecord

template <typename TId, typename TSequence, typename TQualities> int writeRecord(SequenceStream & seqIO, TId const & id, TSequence const & seq, TQualities const & qual);       	// "core/include/seqan/seq_io/sequence_stream.h"(645)
template <typename TId, typename TSequence> int writeRecord(SequenceStream & seqIO, TId const & id, TSequence const & seq);       	// "core/include/seqan/seq_io/sequence_stream.h"(663)
template <typename TStream, typename TIdString, typename TSeqString> inline int writeRecord(TStream & stream, TIdString const & meta, TSeqString const & seq, Fasta const & , unsigned const options);       	// "core/include/seqan/seq_io/write_fasta_fastq.h"(105)
template <typename TStream, typename TIdString, typename TSeqString> inline int writeRecord(TStream & stream, TIdString const & meta, TSeqString const & seq, Fasta const & );       	// "core/include/seqan/seq_io/write_fasta_fastq.h"(158)
template <typename TStream, typename TIdString, typename TQualString, typename TSeqString> inline int writeRecord(TStream & stream, TIdString const & meta, TSeqString const & seq, TQualString const & qual, Fastq const & , unsigned const options);       	// "core/include/seqan/seq_io/write_fasta_fastq.h"(287)
template <typename TStream, typename TIdString, typename TQualString, typename TSeqString> inline int writeRecord(TStream & stream, TIdString const & meta, TSeqString const & seq, TQualString const & qual, Fastq const & );       	// "core/include/seqan/seq_io/write_fasta_fastq.h"(360)
template <typename TStream, typename TIdString, typename TSeqString> inline int writeRecord(TStream & stream, TIdString const & meta, TSeqString const & seq, Fastq const & , unsigned const options);       	// "core/include/seqan/seq_io/write_fasta_fastq.h"(379)
template <typename TStream, typename TIdString, typename TSeqString> inline int writeRecord(TStream & stream, TIdString const & meta, TSeqString const & seq, Fastq const & );       	// "core/include/seqan/seq_io/write_fasta_fastq.h"(391)

} //namespace seqan

#endif

