// ==========================================================================
//                 SeqAn - The Library for Sequence Analysis
// ==========================================================================
// Copyright (c) 2006-2010, Knut Reinert, FU Berlin
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
//     * Redistributions of source code must retain the above copyright
//       notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above copyright
//       notice, this list of conditions and the following disclaimer in the
//       documentation and/or other materials provided with the distribution.
//     * Neither the name of Knut Reinert or the FU Berlin nor the names of
//       its contributors may be used to endorse or promote products derived
//       from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL KNUT REINERT OR THE FU BERLIN BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
// LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
// OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
// DAMAGE.
//
// ==========================================================================


#ifndef SEQAN_HEADER_STREAM_GENERATED_FORWARDS_H 
#define SEQAN_HEADER_STREAM_GENERATED_FORWARDS_H 

//////////////////////////////////////////////////////////////////////////////
// NOTE: This file is automatically generated by build_forwards.py
//       Do not edit this file manually!
//////////////////////////////////////////////////////////////////////////////


//////////////////////////////////////////////////////////////////////////////
// CLASSES
//////////////////////////////////////////////////////////////////////////////

namespace seqan {

//____________________________________________________________________________
// AlphaNum__

struct AlphaNum__;       	// "core/include/seqan/stream/tokenize.h"(77)

//____________________________________________________________________________
// Alpha__

struct Alpha__;       	// "core/include/seqan/stream/tokenize.h"(76)

//____________________________________________________________________________
// BZ2File_

struct BZ2File_;       	// "core/include/seqan/stream/stream_base.h"(68)

//____________________________________________________________________________
// BackslashR__

struct BackslashR__;       	// "core/include/seqan/stream/tokenize.h"(79)

//____________________________________________________________________________
// BgzfCacheEntry_

struct BgzfCacheEntry_;       	// "core/include/seqan/stream/stream_bgzf.h"(90)

//____________________________________________________________________________
// Bgzf_

struct Bgzf_;       	// "core/include/seqan/stream/stream_bgzf.h"(78)
struct Bgzf_;       	// "core/include/seqan/stream/stream_bgzf.h"(115)

//____________________________________________________________________________
// Blank__

struct Blank__;       	// "core/include/seqan/stream/tokenize.h"(73)

//____________________________________________________________________________
// CharArray

template <typename TPointer > struct CharArray;       	// "core/include/seqan/stream/stream_base.h"(60)

//____________________________________________________________________________
// Char__

struct Char__;       	// "core/include/seqan/stream/tokenize.h"(74)

//____________________________________________________________________________
// Digit__

struct Digit__;       	// "core/include/seqan/stream/tokenize.h"(75)

//____________________________________________________________________________
// DoublePass

template <typename TSpec > struct DoublePass;       	// "core/include/seqan/stream/record_reader_base.h"(55)

//____________________________________________________________________________
// GZFile_

struct GZFile_;       	// "core/include/seqan/stream/stream_base.h"(63)

//____________________________________________________________________________
// Graph__

struct Graph__;       	// "core/include/seqan/stream/tokenize.h"(80)

//____________________________________________________________________________
// HasFilename_

struct HasFilename_;       	// "core/include/seqan/stream/concept_stream.h"(83)

//____________________________________________________________________________
// HasPeek_

struct HasPeek_;       	// "core/include/seqan/stream/concept_stream.h"(80)

//____________________________________________________________________________
// HasStreamFeature

template <typename TStream, typename TTag> struct HasStreamFeature;       	// "core/include/seqan/stream/concept_stream.h"(117)

//____________________________________________________________________________
// Identifier__

struct Identifier__;       	// "core/include/seqan/stream/tokenize.h"(82)

//____________________________________________________________________________
// IsInput_

struct IsInput_;       	// "core/include/seqan/stream/concept_stream.h"(74)

//____________________________________________________________________________
// IsOutput_

struct IsOutput_;       	// "core/include/seqan/stream/concept_stream.h"(77)

//____________________________________________________________________________
// Mapped_

struct Mapped_;       	// "core/include/seqan/stream/record_reader_base.h"(48)

//____________________________________________________________________________
// OriginBegin_

struct OriginBegin_;       	// "core/include/seqan/stream/concept_stream.h"(86)

//____________________________________________________________________________
// OriginCurrent_

struct OriginCurrent_;       	// "core/include/seqan/stream/concept_stream.h"(92)

//____________________________________________________________________________
// OriginEnd_

struct OriginEnd_;       	// "core/include/seqan/stream/concept_stream.h"(89)

//____________________________________________________________________________
// RecordReader

template <typename TStream, typename TSpec> class RecordReader;       	// "core/include/seqan/stream/record_reader_base.h"(79)

//____________________________________________________________________________
// SamAlignment

struct SamAlignment;       	// "core/include/seqan/stream/read_sam.h"(93)

//____________________________________________________________________________
// SamHeader

struct SamHeader;       	// "core/include/seqan/stream/read_sam.h"(76)

//____________________________________________________________________________
// Seek

template <typename TSpec> struct Seek;       	// "core/include/seqan/stream/concept_stream.h"(96)

//____________________________________________________________________________
// SinglePass

template <typename TSpec > struct SinglePass;       	// "core/include/seqan/stream/record_reader_base.h"(52)

//____________________________________________________________________________
// Stream

template <typename TSpec> class Stream;       	// "core/include/seqan/stream/stream_base.h"(73)

//____________________________________________________________________________
// TabOrLineBreak__

struct TabOrLineBreak__;       	// "core/include/seqan/stream/tokenize.h"(81)

//____________________________________________________________________________
// Tell_

struct Tell_;       	// "core/include/seqan/stream/concept_stream.h"(98)

//____________________________________________________________________________
// UnixEOL__

struct UnixEOL__;       	// "core/include/seqan/stream/tokenize.h"(78)

//____________________________________________________________________________
// Whitespace__

struct Whitespace__;       	// "core/include/seqan/stream/tokenize.h"(72)

} //namespace seqan


//////////////////////////////////////////////////////////////////////////////
// TYPEDEFS
//////////////////////////////////////////////////////////////////////////////

namespace seqan {

//____________________________________________________________________________
// AlphaNum_

typedef Tag<AlphaNum__> AlphaNum_;       	// "core/include/seqan/stream/tokenize.h"(89)

//____________________________________________________________________________
// Alpha_

typedef Tag<Alpha__> Alpha_;       	// "core/include/seqan/stream/tokenize.h"(88)

//____________________________________________________________________________
// BZ2File

typedef Tag<BZ2File_> BZ2File;       	// "core/include/seqan/stream/stream_base.h"(69)

//____________________________________________________________________________
// BackslashR_

typedef Tag<BackslashR__> BackslashR_;       	// "core/include/seqan/stream/tokenize.h"(91)

//____________________________________________________________________________
// Bgzf

typedef Tag<Bgzf_> Bgzf;       	// "core/include/seqan/stream/stream_bgzf.h"(79)
typedef Tag<Bgzf_> Bgzf;       	// "core/include/seqan/stream/stream_bgzf.h"(116)

//____________________________________________________________________________
// Blank_

typedef Tag<Blank__> Blank_;       	// "core/include/seqan/stream/tokenize.h"(85)

//____________________________________________________________________________
// Char_

typedef Tag<Char__> Char_;       	// "core/include/seqan/stream/tokenize.h"(86)

//____________________________________________________________________________
// Digit_

typedef Tag<Digit__> Digit_;       	// "core/include/seqan/stream/tokenize.h"(87)

//____________________________________________________________________________
// GZFile

typedef Tag<GZFile_> GZFile;       	// "core/include/seqan/stream/stream_base.h"(64)

//____________________________________________________________________________
// Graph_

typedef Tag<Graph__> Graph_;       	// "core/include/seqan/stream/tokenize.h"(92)

//____________________________________________________________________________
// HasFilename

typedef Tag<HasFilename_> HasFilename;       	// "core/include/seqan/stream/concept_stream.h"(84)

//____________________________________________________________________________
// HasPeek

typedef Tag<HasPeek_> HasPeek;       	// "core/include/seqan/stream/concept_stream.h"(81)

//____________________________________________________________________________
// Identifier_

typedef Tag<Identifier__> Identifier_;       	// "core/include/seqan/stream/tokenize.h"(94)

//____________________________________________________________________________
// IsInput

typedef Tag<IsInput_> IsInput;       	// "core/include/seqan/stream/concept_stream.h"(75)

//____________________________________________________________________________
// IsOutput

typedef Tag<IsOutput_> IsOutput;       	// "core/include/seqan/stream/concept_stream.h"(78)

//____________________________________________________________________________
// Mapped

typedef Tag<Mapped_> Mapped;       	// "core/include/seqan/stream/record_reader_base.h"(49)

//____________________________________________________________________________
// OriginBegin

typedef Tag<OriginBegin_> OriginBegin;       	// "core/include/seqan/stream/concept_stream.h"(87)

//____________________________________________________________________________
// OriginCurrent

typedef Tag<OriginCurrent_> OriginCurrent;       	// "core/include/seqan/stream/concept_stream.h"(93)

//____________________________________________________________________________
// OriginEnd

typedef Tag<OriginEnd_> OriginEnd;       	// "core/include/seqan/stream/concept_stream.h"(90)

//____________________________________________________________________________
// TabOrLineBreak_

typedef Tag<TabOrLineBreak__> TabOrLineBreak_;       	// "core/include/seqan/stream/tokenize.h"(93)

//____________________________________________________________________________
// Tell

typedef Tag<Tell_> Tell;       	// "core/include/seqan/stream/concept_stream.h"(99)

//____________________________________________________________________________
// UnixEOL_

typedef Tag<UnixEOL__> UnixEOL_;       	// "core/include/seqan/stream/tokenize.h"(90)

//____________________________________________________________________________
// Whitespace_

typedef Tag<Whitespace__> Whitespace_;       	// "core/include/seqan/stream/tokenize.h"(84)

} //namespace seqan


//////////////////////////////////////////////////////////////////////////////
// FUNCTIONS
//////////////////////////////////////////////////////////////////////////////

namespace seqan {

//____________________________________________________________________________
// _appendWithoutTrailing0

template <typename TValue, typename TSpec, typename TSource> inline int _appendWithoutTrailing0(String<TValue, TSpec> & stream, TSource const & source);       	// "core/include/seqan/stream/adapt_mmap.h"(141)

//____________________________________________________________________________
// _bgzfCacheBlock

inline bool _bgzfCacheBlock(Stream<Bgzf> & stream, size_t size);       	// "core/include/seqan/stream/stream_bgzf.h"(405)

//____________________________________________________________________________
// _bgzfCheckHeader

inline int _bgzfCheckHeader(char const * header);       	// "core/include/seqan/stream/stream_bgzf.h"(351)

//____________________________________________________________________________
// _bgzfClearCache

inline void _bgzfClearCache(Stream<Bgzf> & stream);       	// "core/include/seqan/stream/stream_bgzf.h"(443)

//____________________________________________________________________________
// _bgzfDeflateBlock

inline int _bgzfDeflateBlock(Stream<Bgzf> & stream, int blockLength);       	// "core/include/seqan/stream/stream_bgzf.h"(579)

//____________________________________________________________________________
// _bgzfInflateBlock

inline int _bgzfInflateBlock(Stream<Bgzf> & stream, size_t blockLength);       	// "core/include/seqan/stream/stream_bgzf.h"(459)

//____________________________________________________________________________
// _bgzfLoadBlockFromCache

inline int _bgzfLoadBlockFromCache(Stream<Bgzf> & stream, __int64 blockAddress);       	// "core/include/seqan/stream/stream_bgzf.h"(378)

//____________________________________________________________________________
// _bgzfPackInt16

inline void _bgzfPackInt16(unsigned char * buffer, __uint16 value);       	// "core/include/seqan/stream/stream_bgzf.h"(327)

//____________________________________________________________________________
// _bgzfPackInt32

inline void _bgzfPackInt32(unsigned char * buffer, __int32 value);       	// "core/include/seqan/stream/stream_bgzf.h"(338)

//____________________________________________________________________________
// _bgzfReadBlock

inline int _bgzfReadBlock(Stream<Bgzf> & stream);       	// "core/include/seqan/stream/stream_bgzf.h"(497)

//____________________________________________________________________________
// _bgzfUnpackInt16

inline int _bgzfUnpackInt16(unsigned char const * buffer);       	// "core/include/seqan/stream/stream_bgzf.h"(316)

//____________________________________________________________________________
// _charCompare

inline int _charCompare(int const c, Whitespace_ const & );       	// "core/include/seqan/stream/tokenize.h"(113)
inline int _charCompare(int const c, Blank_ const & );       	// "core/include/seqan/stream/tokenize.h"(119)
inline int _charCompare(int const c, Alpha_ const & );       	// "core/include/seqan/stream/tokenize.h"(125)
inline int _charCompare(int const c, AlphaNum_ const & );       	// "core/include/seqan/stream/tokenize.h"(131)
inline int _charCompare(int const c, Identifier_ const & );       	// "core/include/seqan/stream/tokenize.h"(137)
inline int _charCompare(int const c, Digit_ const & );       	// "core/include/seqan/stream/tokenize.h"(143)
inline int _charCompare(int const c, Graph_ const & );       	// "core/include/seqan/stream/tokenize.h"(149)
inline int _charCompare(int const c, UnixEOL_ const & );       	// "core/include/seqan/stream/tokenize.h"(155)
inline int _charCompare(int const c, BackslashR_ const & );       	// "core/include/seqan/stream/tokenize.h"(161)
inline int _charCompare(int const c, Tag<AminoAcid_> const & );       	// "core/include/seqan/stream/tokenize.h"(167)
inline int _charCompare(int const c, Tag<Dna_> const & );       	// "core/include/seqan/stream/tokenize.h"(224)
inline int _charCompare(int const c, Tag<Rna_> const & );       	// "core/include/seqan/stream/tokenize.h"(241)
inline int _charCompare(int const c, Tag<DnaQ_> const & );       	// "core/include/seqan/stream/tokenize.h"(258)
inline int _charCompare(int const c, Tag<Dna5_> const & );       	// "core/include/seqan/stream/tokenize.h"(264)
inline int _charCompare(int const c, Tag<Rna5_> const & );       	// "core/include/seqan/stream/tokenize.h"(284)
inline int _charCompare(int const c, Tag<Dna5Q_> const & );       	// "core/include/seqan/stream/tokenize.h"(304)
template <typename TSpec> inline int _charCompare(int const c, Tag<SimpleType<unsigned char, TSpec> > const & );       	// "core/include/seqan/stream/tokenize.h"(312)
inline int _charCompare(int const c, TabOrLineBreak_ const & );       	// "core/include/seqan/stream/tokenize.h"(318)

//____________________________________________________________________________
// _countHelper

template <typename TTagSpec, typename TRecordReader> inline int _countHelper(unsigned & count, TRecordReader & reader, Tag<TTagSpec> const & tag, bool const desiredOutcomeOfComparison);       	// "core/include/seqan/stream/tokenize.h"(459)
template <typename TTagSpec, typename TRecordReader> inline int _countHelper(unsigned & count, TRecordReader & reader, Tag<TTagSpec> const & tag);       	// "core/include/seqan/stream/tokenize.h"(481)
template <typename TTagSpec, typename TTagSpec2, typename TRecordReader> inline int _countHelper(unsigned & count, TRecordReader & reader, Tag<TTagSpec> const & compTag, Tag<TTagSpec2> const & skipTag, bool const desiredOutcomeOfComparison);       	// "core/include/seqan/stream/tokenize.h"(495)
template <typename TTagSpec, typename TTagSpec2, typename TRecordReader> inline int _countHelper(unsigned & count, TRecordReader & reader, Tag<TTagSpec> const & compTag, Tag<TTagSpec2> const & skipTag);       	// "core/include/seqan/stream/tokenize.h"(525)

//____________________________________________________________________________
// _fillNextBuffer

template <typename TFile> inline bool _fillNextBuffer(RecordReader<TFile, DoublePass<> > & recordReader);       	// "core/include/seqan/stream/record_reader_double.h"(131)

//____________________________________________________________________________
// _jumpToNextBuffer

template <typename TFile> bool _jumpToNextBuffer(RecordReader<TFile, DoublePass<> > & recordReader);       	// "core/include/seqan/stream/record_reader_double.h"(221)

//____________________________________________________________________________
// _read2

template <typename TIdString, typename TIdSpec, typename TSeqString, typename TSeqSpec, typename TQualString, typename TQualSpec, typename TRecordReader> int _read2(StringSet<TIdString, TIdSpec> & , StringSet<TSeqString, TSeqSpec> & , StringSet<TQualString, TQualSpec> & , TRecordReader & , TagSelector<void> const & , int i);       	// "core/include/seqan/stream/read_auto_format.h"(78)
template <typename TIdString, typename TIdSpec, typename TSeqString, typename TSeqSpec, typename TQualString, typename TQualSpec, typename TRecordReader, typename TTagList> int _read2(StringSet<TIdString, TIdSpec> & metas, StringSet<TSeqString, TSeqSpec> & seqs, StringSet<TQualString, TQualSpec> & quals, TRecordReader & reader, TagSelector<TTagList> const & tagSelector, int i);       	// "core/include/seqan/stream/read_auto_format.h"(92)
template <typename TIdString, typename TIdSpec, typename TSeqString, typename TSeqSpec, typename TRecordReader> int _read2(StringSet<TIdString, TIdSpec> & , StringSet<TSeqString, TSeqSpec> & , TRecordReader & , TagSelector<void> const & , int i);       	// "core/include/seqan/stream/read_auto_format.h"(125)
template <typename TIdString, typename TIdSpec, typename TSeqString, typename TSeqSpec, typename TRecordReader, typename TTagList> int _read2(StringSet<TIdString, TIdSpec> & metas, StringSet<TSeqString, TSeqSpec> & seqs, TRecordReader & reader, TagSelector<TTagList> const & tagSelector, int i);       	// "core/include/seqan/stream/read_auto_format.h"(138)

//____________________________________________________________________________
// _readAndCompareWithStr

template <typename TRecordReader, typename TString> inline int _readAndCompareWithStr(TRecordReader & reader, TString const & str);       	// "core/include/seqan/stream/tokenize.h"(542)

//____________________________________________________________________________
// _readHelper

template <typename TTagSpec, typename TRecordReader, typename TBuffer> inline int _readHelper(TBuffer & buffer, TRecordReader & reader, Tag<TTagSpec> const & tag, bool const desiredOutcomeOfComparison);       	// "core/include/seqan/stream/tokenize.h"(339)
template <typename TSpec, typename TRecordReader, typename TBuffer> inline int _readHelper(TBuffer & buffer, TRecordReader & reader, Tag<TSpec> const & tag);       	// "core/include/seqan/stream/tokenize.h"(363)
template <typename TTagSpec, typename TTagSpec2, typename TRecordReader, typename TBuffer> inline int _readHelper(TBuffer & buffer, TRecordReader & reader, Tag<TTagSpec> const & compTag, Tag<TTagSpec2> const & skipTag, bool const desiredOutcomeOfComparison);       	// "core/include/seqan/stream/tokenize.h"(378)
template <typename TTagSpec, typename TTagSpec2, typename TRecordReader, typename TBuffer> inline int _readHelper(TBuffer & buffer, TRecordReader & reader, Tag<TTagSpec> const & compTag, Tag<TTagSpec2> const & skipTag);       	// "core/include/seqan/stream/tokenize.h"(408)

//____________________________________________________________________________
// _readNCharsIgnoringType

template <typename TBuffer, typename TStream, typename TPass, typename TIgnoredType> inline int _readNCharsIgnoringType(TBuffer & buffer, RecordReader<TStream, TPass> & reader, unsigned const n, TIgnoredType );       	// "core/include/seqan/stream/tokenize.h"(858)

//____________________________________________________________________________
// _readRecord

template <typename TIdString, typename TSeqString, typename TQualString, typename TRecordReader> int _readRecord(TIdString & , TSeqString & , TQualString & , TRecordReader & , TagSelector<void> const & , int i);       	// "core/include/seqan/stream/read_auto_format.h"(169)
template <typename TIdString, typename TSeqString, typename TQualString, typename TRecordReader, typename TTagList> int _readRecord(TIdString & meta, TSeqString & seq, TQualString & qual, TRecordReader & reader, TagSelector<TTagList> const & tagSelector, int i);       	// "core/include/seqan/stream/read_auto_format.h"(177)
template <typename TIdString, typename TSeqString, typename TRecordReader> int _readRecord(TIdString & , TSeqString & , TRecordReader & , TagSelector<void> const & , int i);       	// "core/include/seqan/stream/read_auto_format.h"(201)
template <typename TIdString, typename TSeqString, typename TRecordReader, typename TTagList> int _readRecord(TIdString & meta, TSeqString & seq, TRecordReader & reader, TagSelector<TTagList> const & tagSelector, int i);       	// "core/include/seqan/stream/read_auto_format.h"(209)

//____________________________________________________________________________
// _refillBuffer

template <typename TFile> inline bool _refillBuffer(RecordReader<TFile, SinglePass<void> > & recordReader);       	// "core/include/seqan/stream/record_reader_single.h"(123)

//____________________________________________________________________________
// _skipHelper

template <typename TTagSpec, typename TRecordReader> inline int _skipHelper(TRecordReader & reader, Tag<TTagSpec> const & tag, bool const desiredOutcomeOfComparison);       	// "core/include/seqan/stream/tokenize.h"(424)
template <typename TTagSpec, typename TRecordReader> inline int _skipHelper(TRecordReader & reader, Tag<TTagSpec> const & tag);       	// "core/include/seqan/stream/tokenize.h"(444)

//____________________________________________________________________________
// _skipNCharsIgnoringType

template <typename TStream, typename TPass, typename TIgnoredType> inline int _skipNCharsIgnoringType(RecordReader<TStream, TPass> & reader, unsigned const n, TIgnoredType const & );       	// "core/include/seqan/stream/tokenize.h"(950)

//____________________________________________________________________________
// _streamPeekImpl

inline int _streamPeekImpl(char & c, char const * & ptr, char const * & end, bool & eof);       	// "core/include/seqan/stream/stream_char_array.h"(278)

//____________________________________________________________________________
// _streamPeekImplIOStream

template <typename TStream> inline int _streamPeekImplIOStream(char & c, TStream & stream);       	// "core/include/seqan/stream/adapt_fstream.h"(273)

//____________________________________________________________________________
// _streamPut

template <typename TStream, typename TSource> inline int _streamPut(Stream<TStream> & stream, TSource const & source, False const & );       	// "core/include/seqan/stream/stream_base.h"(137)
template <typename TStream, typename TSource> inline int _streamPut(TStream & target, TSource const & source, True const & );       	// "core/include/seqan/stream/stream_base.h"(163)
template <typename TStream> inline int _streamPut(Stream<TStream> & stream, char const * source, True const & );       	// "core/include/seqan/stream/stream_base.h"(182)
template <typename TStream, typename TSourceValue> inline int _streamPut(TStream & stream, TSourceValue const * source, True const & );       	// "core/include/seqan/stream/stream_base.h"(192)

//____________________________________________________________________________
// _streamPutChar

inline char const * _streamPutChar(char const * );       	// "core/include/seqan/stream/adapt_cstdio.h"(289)
inline char const * _streamPutChar(int const );       	// "core/include/seqan/stream/adapt_cstdio.h"(295)
inline char const * _streamPutChar(unsigned int const );       	// "core/include/seqan/stream/adapt_cstdio.h"(301)
inline char const * _streamPutChar(long const );       	// "core/include/seqan/stream/adapt_cstdio.h"(307)
inline char const * _streamPutChar(unsigned long const );       	// "core/include/seqan/stream/adapt_cstdio.h"(313)
inline char const * _streamPutChar(float const );       	// "core/include/seqan/stream/adapt_cstdio.h"(319)
inline char const * _streamPutChar(double const );       	// "core/include/seqan/stream/adapt_cstdio.h"(325)

//____________________________________________________________________________
// _streamReadBlockImpl

inline size_t _streamReadBlockImpl(bool & eof, char * target, char const * & ptr, char const * & end, size_t maxLen);       	// "core/include/seqan/stream/stream_char_array.h"(351)

//____________________________________________________________________________
// _streamReadBlockImplIOStream

template <typename TStream> inline size_t _streamReadBlockImplIOStream(char * target, TStream & stream, size_t maxLen);       	// "core/include/seqan/stream/adapt_fstream.h"(383)

//____________________________________________________________________________
// _streamReadCharImpl

inline int _streamReadCharImpl(bool & eof, char & c, char const * & ptr, char const * & end);       	// "core/include/seqan/stream/stream_char_array.h"(306)

//____________________________________________________________________________
// _streamReadCharImplIOStream

template <typename TStream> inline int _streamReadCharImplIOStream(char & c, TStream & stream);       	// "core/include/seqan/stream/adapt_fstream.h"(300)

//____________________________________________________________________________
// _streamSeekImpl

inline int _streamSeekImpl(char const * & ptr, char const * base, char const * end, ptrdiff_t delta, int origin);       	// "core/include/seqan/stream/stream_char_array.h"(432)

//____________________________________________________________________________
// _streamWriteBlockImplIOStream

template <typename TStream> inline size_t _streamWriteBlockImplIOStream(TStream & stream, char const * source, size_t count);       	// "core/include/seqan/stream/adapt_fstream.h"(436)

//____________________________________________________________________________
// _streamWriteCharImplIOStream

template <typename TStream> inline int _streamWriteCharImplIOStream(TStream & stream, char const c);       	// "core/include/seqan/stream/adapt_fstream.h"(407)

//____________________________________________________________________________
// atEnd

template <typename TFile> inline bool atEnd(RecordReader<TFile, DoublePass<> > & recordReader);       	// "core/include/seqan/stream/record_reader_double.h"(273)
template <typename TMMapString> inline bool atEnd(RecordReader<TMMapString, DoublePass<Mapped> > & recordReader);       	// "core/include/seqan/stream/record_reader_double_mmap.h"(142)
template <typename TFile> inline bool atEnd(RecordReader<TFile, SinglePass<void> > & recordReader);       	// "core/include/seqan/stream/record_reader_single.h"(157)
template <typename TMMapString> inline bool atEnd(RecordReader<TMMapString, SinglePass<Mapped> > & recordReader);       	// "core/include/seqan/stream/record_reader_single_mmap.h"(118)
template <typename TMMapString> inline bool atEnd(RecordReader<TMMapString, SinglePass<Mapped> > const & recordReader);       	// "core/include/seqan/stream/record_reader_single_mmap.h"(127)
template <typename TSpec> inline bool atEnd(Stream<TSpec> & stream);       	// "core/include/seqan/stream/stream_base.h"(93)
template <typename TSpec> inline bool atEnd(Stream<TSpec> const & stream);       	// "core/include/seqan/stream/stream_base.h"(100)

//____________________________________________________________________________
// attachToFile

inline void attachToFile(Stream<Bgzf> & stream, int fileHandle, int mode);       	// "core/include/seqan/stream/stream_bgzf.h"(717)

//____________________________________________________________________________
// checkEofIsValid

inline bool checkEofIsValid(Stream<Bgzf> & stream);       	// "core/include/seqan/stream/stream_bgzf.h"(925)

//____________________________________________________________________________
// close

inline void close(Stream<Bgzf> & stream);       	// "core/include/seqan/stream/stream_bgzf.h"(821)
inline void close(Stream<BZ2File> & stream);       	// "core/include/seqan/stream/stream_bz2_file.h"(314)
inline void close(Stream<GZFile> & stream);       	// "core/include/seqan/stream/stream_gz_file.h"(310)

//____________________________________________________________________________
// countLine

template <typename TStream, typename TPass> inline int countLine(unsigned & count, RecordReader<TStream, TPass> & reader);       	// "core/include/seqan/stream/tokenize.h"(1587)

//____________________________________________________________________________
// goNext

template <typename TFile> inline bool goNext(RecordReader<TFile, DoublePass<> > & recordReader);       	// "core/include/seqan/stream/record_reader_double.h"(331)
template <typename TMMapString> inline bool goNext(RecordReader<TMMapString, DoublePass<Mapped> > & recordReader);       	// "core/include/seqan/stream/record_reader_double_mmap.h"(165)
template <typename TFile> inline bool goNext(RecordReader<TFile, SinglePass<void> > & recordReader);       	// "core/include/seqan/stream/record_reader_single.h"(194)
template <typename TMMapString> inline bool goNext(RecordReader<TMMapString, SinglePass<Mapped> > & recordReader);       	// "core/include/seqan/stream/record_reader_single_mmap.h"(149)

//____________________________________________________________________________
// isDirect

inline bool isDirect(Stream<GZFile> & stream);       	// "core/include/seqan/stream/stream_gz_file.h"(292)

//____________________________________________________________________________
// isLineBreak

inline bool isLineBreak(char c);       	// "core/include/seqan/stream/read_sam.h"(125)

//____________________________________________________________________________
// lexicalCast

template <typename TTarget, typename TSource> inline TTarget lexicalCast(TSource const & source);       	// "core/include/seqan/stream/lexical_cast.h"(81)
template <typename TTarget, typename TValue, typename TSpec> inline TTarget lexicalCast(String<TValue, TSpec> const & source);       	// "core/include/seqan/stream/lexical_cast.h"(92)
template <typename TTarget, typename TValue, typename TSpec> inline TTarget lexicalCast(String<TValue, TSpec> & source);       	// "core/include/seqan/stream/lexical_cast.h"(102)

//____________________________________________________________________________
// lexicalCast2

template <typename TTarget, typename TSource > inline bool lexicalCast2(TTarget & target, TSource const & source);       	// "core/include/seqan/stream/lexical_cast.h"(146)
template <typename TTarget, typename TValue, typename TSpec> inline bool lexicalCast2(TTarget & target, String<TValue, TSpec> const & source);       	// "core/include/seqan/stream/lexical_cast.h"(154)

//____________________________________________________________________________
// open

inline bool open(Stream<Bgzf> & stream, char const * filename, char const * mode);       	// "core/include/seqan/stream/stream_bgzf.h"(740)
inline bool open(Stream<BZ2File> & stream, char const * filename, char const * mode);       	// "core/include/seqan/stream/stream_bz2_file.h"(261)
inline bool open(Stream<GZFile> & stream, char const * filename, char const * mode);       	// "core/include/seqan/stream/stream_gz_file.h"(246)

//____________________________________________________________________________
// read2

template <typename TIdString, typename TIdSpec, typename TSeqString, typename TSeqSpec, typename TQualString, typename TQualSpec, typename TRecordReader, typename TTagList> int read2(StringSet<TIdString, TIdSpec> & metas, StringSet<TSeqString, TSeqSpec> & seqs, StringSet<TQualString, TQualSpec> & quals, TRecordReader & reader, TagSelector<TTagList> & tagSelector);       	// "core/include/seqan/stream/read_auto_format.h"(109)
template <typename TIdString, typename TIdSpec, typename TSeqString, typename TSeqSpec, typename TRecordReader, typename TTagList> int read2(StringSet<TIdString, TIdSpec> & metas, StringSet<TSeqString, TSeqSpec> & seqs, TRecordReader & reader, TagSelector<TTagList> & tagSelector);       	// "core/include/seqan/stream/read_auto_format.h"(154)

//____________________________________________________________________________
// readAlphaNums

template <typename TStream, typename TPass, typename TBuffer> inline int readAlphaNums(TBuffer & buffer, RecordReader<TStream, TPass> & reader);       	// "core/include/seqan/stream/tokenize.h"(1329)

//____________________________________________________________________________
// readDigits

template <typename TStream, typename TPass, typename TBuffer> inline int readDigits(TBuffer & buffer, RecordReader<TStream, TPass> & reader);       	// "core/include/seqan/stream/tokenize.h"(1227)

//____________________________________________________________________________
// readDna5IgnoringWhitespaces

template <typename TStream, typename TPass, typename TBuffer> inline int readDna5IgnoringWhitespaces(TBuffer & buffer, RecordReader<TStream, TPass> & reader);       	// "core/include/seqan/stream/tokenize.h"(1629)

//____________________________________________________________________________
// readFloat

template <typename TStream, typename TPass, typename TBuffer> inline int readFloat(TBuffer & buffer, RecordReader<TStream, TPass> & reader);       	// "core/include/seqan/stream/tokenize.h"(1286)

//____________________________________________________________________________
// readGraphs

template <typename TStream, typename TPass, typename TBuffer> inline int readGraphs(TBuffer & buffer, RecordReader<TStream, TPass> & reader);       	// "core/include/seqan/stream/tokenize.h"(1257)

//____________________________________________________________________________
// readIdentifier

template <typename TStream, typename TPass, typename TBuffer> inline int readIdentifier(TBuffer & buffer, RecordReader<TStream, TPass> & reader);       	// "core/include/seqan/stream/tokenize.h"(1359)

//____________________________________________________________________________
// readLetters

template <typename TStream, typename TPass, typename TBuffer> inline int readLetters(TBuffer & buffer, RecordReader<TStream, TPass> & reader);       	// "core/include/seqan/stream/tokenize.h"(1196)

//____________________________________________________________________________
// readLine

template <typename TStream, typename TPass, typename TBuffer> inline int readLine(TBuffer & buffer, RecordReader<TStream, TPass> & reader);       	// "core/include/seqan/stream/tokenize.h"(1472)

//____________________________________________________________________________
// readLineStripTrailingBlanks

template <typename TStream, typename TPass, typename TBuffer> inline int readLineStripTrailingBlanks(TBuffer & buffer, RecordReader<TStream, TPass> & reader);       	// "core/include/seqan/stream/tokenize.h"(1513)

//____________________________________________________________________________
// readNChars

template <typename TBuffer, typename TStream, typename TPass> inline int readNChars(TBuffer & buffer, RecordReader<TStream, TPass> & reader, unsigned const n);       	// "core/include/seqan/stream/tokenize.h"(809)

//____________________________________________________________________________
// readNCharsIgnoringWhitespace

template <typename TBuffer, typename TStream, typename TPass> inline int readNCharsIgnoringWhitespace(TBuffer & buffer, RecordReader<TStream, TPass> & reader, unsigned const n);       	// "core/include/seqan/stream/tokenize.h"(886)

//____________________________________________________________________________
// readRecord

template <typename TIdString, typename TSeqString, typename TQualString, typename TRecordReader, typename TTagList> int readRecord(TIdString & meta, TSeqString & seq, TQualString & qual, TRecordReader & reader, TagSelector<TTagList> & tagSelector);       	// "core/include/seqan/stream/read_auto_format.h"(189)
template <typename TIdString, typename TSeqString, typename TRecordReader, typename TTagList> int readRecord(TIdString & meta, TSeqString & seq, TRecordReader & reader, TagSelector<TTagList> & tagSelector);       	// "core/include/seqan/stream/read_auto_format.h"(221)
template <typename TIdString, typename TSeqString, typename TFile, typename TSpec> int readRecord(SamHeader & header, RecordReader<TFile, SinglePass<TSpec> > & reader, Sam const & );       	// "core/include/seqan/stream/read_sam.h"(133)
template <typename TIdString, typename TSeqString, typename TFile, typename TSpec> int readRecord(SamAlignment & record, RecordReader<TFile, SinglePass<TSpec> > & reader, Sam const & );       	// "core/include/seqan/stream/read_sam.h"(178)

//____________________________________________________________________________
// readUntilBlank

template <typename TBuffer, typename TStream, typename TPass> inline int readUntilBlank(TBuffer & buffer, RecordReader<TStream, TPass> & reader);       	// "core/include/seqan/stream/tokenize.h"(731)

//____________________________________________________________________________
// readUntilChar

template <typename TBuffer, typename TStream, typename TPass, typename TCharX> inline int readUntilChar(TBuffer & buffer, RecordReader<TStream, TPass> & reader, TCharX const & x);       	// "core/include/seqan/stream/tokenize.h"(766)

//____________________________________________________________________________
// readUntilOneOf

template <typename TBuffer, typename TStream, typename TPass> inline int readUntilOneOf(TBuffer & buffer, RecordReader<TStream, TPass> & reader, char c1);       	// "core/include/seqan/stream/tokenize.h"(587)
template <typename TBuffer, typename TStream, typename TPass> inline int readUntilOneOf(TBuffer & buffer, RecordReader<TStream, TPass> & reader, char c1, char c2);       	// "core/include/seqan/stream/tokenize.h"(604)
template <typename TBuffer, typename TStream, typename TPass> inline int readUntilOneOf(TBuffer & buffer, RecordReader<TStream, TPass> & reader, char c1, char c2, char c3);       	// "core/include/seqan/stream/tokenize.h"(621)
template <typename TBuffer, typename TStream, typename TPass> inline int readUntilOneOf(TBuffer & buffer, RecordReader<TStream, TPass> & reader, char c1, char c2, char c3, char c4);       	// "core/include/seqan/stream/tokenize.h"(638)
template <typename TBuffer, typename TStream, typename TPass> inline int readUntilOneOf(TBuffer & buffer, RecordReader<TStream, TPass> & reader, char c1, char c2, char c3, char c4, char c5);       	// "core/include/seqan/stream/tokenize.h"(655)

//____________________________________________________________________________
// readUntilTabOrLineBreak

template <typename TBuffer, typename TStream, typename TPass> inline int readUntilTabOrLineBreak(TBuffer & buffer, RecordReader<TStream, TPass> & reader);       	// "core/include/seqan/stream/tokenize.h"(1163)

//____________________________________________________________________________
// readUntilWhitespace

template <typename TBuffer, typename TStream, typename TPass> inline int readUntilWhitespace(TBuffer & buffer, RecordReader<TStream, TPass> & reader);       	// "core/include/seqan/stream/tokenize.h"(697)

//____________________________________________________________________________
// resultCode

template <typename TFile> inline int resultCode(RecordReader<TFile, DoublePass<> > & recordReader);       	// "core/include/seqan/stream/record_reader_double.h"(320)
template <typename TMMapString> inline int resultCode(RecordReader<TMMapString, DoublePass<Mapped> > & );       	// "core/include/seqan/stream/record_reader_double_mmap.h"(154)
template <typename TFile> inline int resultCode(RecordReader<TFile, SinglePass<void> > & recordReader);       	// "core/include/seqan/stream/record_reader_single.h"(183)
template <typename TMMapString> inline int resultCode(RecordReader<TMMapString, SinglePass<Mapped> > & );       	// "core/include/seqan/stream/record_reader_single_mmap.h"(138)

//____________________________________________________________________________
// skipBlanks

template <typename TStream, typename TPass> inline int skipBlanks(RecordReader<TStream, TPass> & reader);       	// "core/include/seqan/stream/tokenize.h"(1443)

//____________________________________________________________________________
// skipChar

template <typename TStream, typename TPass> inline int skipChar(RecordReader<TStream, TPass> & reader, char const c);       	// "core/include/seqan/stream/tokenize.h"(1411)

//____________________________________________________________________________
// skipLine

template <typename TStream, typename TPass> inline int skipLine(RecordReader<TStream, TPass> & reader);       	// "core/include/seqan/stream/tokenize.h"(1553)

//____________________________________________________________________________
// skipNChars

template <typename TStream, typename TPass> inline int skipNChars(RecordReader<TStream, TPass> & reader, unsigned const n);       	// "core/include/seqan/stream/tokenize.h"(911)

//____________________________________________________________________________
// skipNCharsIgnoringWhitespace

template <typename TStream, typename TPass> inline int skipNCharsIgnoringWhitespace(RecordReader<TStream, TPass> & reader, unsigned const n);       	// "core/include/seqan/stream/tokenize.h"(968)

//____________________________________________________________________________
// skipUntilBlank

template <typename TStream, typename TPass> inline int skipUntilBlank(RecordReader<TStream, TPass> & reader);       	// "core/include/seqan/stream/tokenize.h"(1024)

//____________________________________________________________________________
// skipUntilChar

template <typename TStream, typename TPass, typename TCharX> inline int skipUntilChar(RecordReader<TStream, TPass> & reader, TCharX const & x);       	// "core/include/seqan/stream/tokenize.h"(1078)

//____________________________________________________________________________
// skipUntilGraph

template <typename TStream, typename TPass> inline int skipUntilGraph(RecordReader<TStream, TPass> & reader);       	// "core/include/seqan/stream/tokenize.h"(1050)

//____________________________________________________________________________
// skipUntilLineBeginsWithChar

template <typename TStream, typename TPass, typename TChar> inline int skipUntilLineBeginsWithChar(RecordReader<TStream, TPass> & reader, TChar const & c );       	// "core/include/seqan/stream/tokenize.h"(1662)

//____________________________________________________________________________
// skipUntilLineBeginsWithOneCharOfStr

template <typename TStream, typename TPass, typename TString> inline int skipUntilLineBeginsWithOneCharOfStr(RecordReader<TStream, TPass> & reader, TString const & str );       	// "core/include/seqan/stream/tokenize.h"(1752)

//____________________________________________________________________________
// skipUntilLineBeginsWithStr

template <typename TStream, typename TPass, typename TString> inline int skipUntilLineBeginsWithStr(RecordReader<TStream, TPass> & reader, TString const & str );       	// "core/include/seqan/stream/tokenize.h"(1705)

//____________________________________________________________________________
// skipUntilString

template <typename TStream, typename TPass, typename TString> inline int skipUntilString(RecordReader<TStream, TPass> & reader, TString const & str);       	// "core/include/seqan/stream/tokenize.h"(1119)

//____________________________________________________________________________
// skipUntilWhitespace

template <typename TStream, typename TPass> inline int skipUntilWhitespace(RecordReader<TStream, TPass> & reader);       	// "core/include/seqan/stream/tokenize.h"(997)

//____________________________________________________________________________
// skipWhitespaces

template <typename TStream, typename TPass> inline int skipWhitespaces(RecordReader<TStream, TPass> & reader);       	// "core/include/seqan/stream/tokenize.h"(1386)

//____________________________________________________________________________
// startFirstPass

template <typename TFile> void startFirstPass(RecordReader<TFile, DoublePass<> > & recordReader);       	// "core/include/seqan/stream/record_reader_double.h"(195)
template <typename TMMapString> void startFirstPass(RecordReader<TMMapString, DoublePass<Mapped> > & recordReader);       	// "core/include/seqan/stream/record_reader_double_mmap.h"(116)

//____________________________________________________________________________
// startSecondPass

template <typename TFile> void startSecondPass(RecordReader<TFile, DoublePass<> > & recordReader);       	// "core/include/seqan/stream/record_reader_double.h"(256)
template <typename TMMapString> void startSecondPass(RecordReader<TMMapString, DoublePass<Mapped> > & recordReader);       	// "core/include/seqan/stream/record_reader_double_mmap.h"(129)

//____________________________________________________________________________
// streamEof

inline bool streamEof(FILE * stream);       	// "core/include/seqan/stream/adapt_cstdio.h"(192)
inline bool streamEof(::std::fstream & stream);       	// "core/include/seqan/stream/adapt_fstream.h"(326)
inline bool streamEof(::std::ifstream & stream);       	// "core/include/seqan/stream/adapt_fstream.h"(332)
inline bool streamEof(::std::ofstream & stream);       	// "core/include/seqan/stream/adapt_fstream.h"(338)
inline bool streamEof(::std::ostream & stream);       	// "core/include/seqan/stream/adapt_iostream.h"(239)
inline bool streamEof(::std::istream & stream);       	// "core/include/seqan/stream/adapt_iostream.h"(245)
inline bool streamEof(::std::stringstream & stream);       	// "core/include/seqan/stream/adapt_sstream.h"(306)
inline bool streamEof(::std::istringstream & stream);       	// "core/include/seqan/stream/adapt_sstream.h"(312)
inline bool streamEof(::std::ostringstream & stream);       	// "core/include/seqan/stream/adapt_sstream.h"(318)
inline bool streamEof(Stream<Bgzf> & stream);       	// "core/include/seqan/stream/stream_bgzf.h"(959)
inline bool streamEof(Stream<Bgzf> const & stream);       	// "core/include/seqan/stream/stream_bgzf.h"(981)
inline bool streamEof(Stream<BZ2File> & stream);       	// "core/include/seqan/stream/stream_bz2_file.h"(334)
inline bool streamEof(Stream<CharArray<char const *> > & stream);       	// "core/include/seqan/stream/stream_char_array.h"(335)
inline bool streamEof(Stream<CharArray<char *> > & stream);       	// "core/include/seqan/stream/stream_char_array.h"(341)
inline bool streamEof(Stream<GZFile> & stream);       	// "core/include/seqan/stream/stream_gz_file.h"(354)

//____________________________________________________________________________
// streamError

inline int streamError(FILE * stream);       	// "core/include/seqan/stream/adapt_cstdio.h"(202)
inline int streamError(::std::fstream & stream);       	// "core/include/seqan/stream/adapt_fstream.h"(348)
inline int streamError(::std::ifstream & stream);       	// "core/include/seqan/stream/adapt_fstream.h"(358)
inline int streamError(::std::ofstream & stream);       	// "core/include/seqan/stream/adapt_fstream.h"(368)
inline int streamError(::std::ostream & stream);       	// "core/include/seqan/stream/adapt_iostream.h"(255)
inline int streamError(::std::istream & stream);       	// "core/include/seqan/stream/adapt_iostream.h"(265)
inline int streamError(::std::stringstream & stream);       	// "core/include/seqan/stream/adapt_sstream.h"(328)
inline int streamError(::std::istringstream & stream);       	// "core/include/seqan/stream/adapt_sstream.h"(338)
inline int streamError(::std::ostringstream & stream);       	// "core/include/seqan/stream/adapt_sstream.h"(348)
inline int streamError(Stream<Bgzf> & stream);       	// "core/include/seqan/stream/stream_bgzf.h"(991)
inline int streamError(Stream<BZ2File> & stream);       	// "core/include/seqan/stream/stream_bz2_file.h"(358)
inline int streamError(Stream<CharArray<char *> > & );       	// "core/include/seqan/stream/stream_char_array.h"(486)
inline int streamError(Stream<CharArray<char const *> > & );       	// "core/include/seqan/stream/stream_char_array.h"(492)
inline int streamError(Stream<GZFile> & stream);       	// "core/include/seqan/stream/stream_gz_file.h"(365)

//____________________________________________________________________________
// streamFlush

inline int streamFlush(FILE * stream);       	// "core/include/seqan/stream/adapt_cstdio.h"(356)
inline int streamFlush(::std::fstream & stream);       	// "core/include/seqan/stream/adapt_fstream.h"(561)
inline int streamFlush(::std::ofstream & stream);       	// "core/include/seqan/stream/adapt_fstream.h"(568)
inline int streamFlush(::std::ostream & stream);       	// "core/include/seqan/stream/adapt_iostream.h"(357)
inline int streamFlush(::std::stringstream & stream);       	// "core/include/seqan/stream/adapt_sstream.h"(518)
inline int streamFlush(::std::ostringstream & stream);       	// "core/include/seqan/stream/adapt_sstream.h"(525)
inline int streamFlush(Stream<Bgzf> & stream);       	// "core/include/seqan/stream/stream_bgzf.h"(785)
inline int streamFlush(Stream<BZ2File> & );       	// "core/include/seqan/stream/stream_bz2_file.h"(408)
inline int streamFlush(Stream<CharArray<char *> > & );       	// "core/include/seqan/stream/stream_char_array.h"(416)
inline int streamFlush(Stream<CharArray<char const *> > & );       	// "core/include/seqan/stream/stream_char_array.h"(422)
inline int streamFlush(Stream<GZFile> & stream);       	// "core/include/seqan/stream/stream_gz_file.h"(413)

//____________________________________________________________________________
// streamPeek

inline int streamPeek(char & c, FILE * stream);       	// "core/include/seqan/stream/adapt_cstdio.h"(165)
inline int streamPeek(char & c, ::std::fstream & stream);       	// "core/include/seqan/stream/adapt_fstream.h"(283)
inline int streamPeek(char & c, ::std::ifstream & stream);       	// "core/include/seqan/stream/adapt_fstream.h"(289)
inline int streamPeek(char & c, ::std::istream & stream);       	// "core/include/seqan/stream/adapt_iostream.h"(219)
inline int streamPeek(char & c, ::std::stringstream & stream);       	// "core/include/seqan/stream/adapt_sstream.h"(272)
inline int streamPeek(char & c, ::std::istringstream & stream);       	// "core/include/seqan/stream/adapt_sstream.h"(278)
inline int streamPeek(char & c, Stream<Bgzf> & stream);       	// "core/include/seqan/stream/stream_bgzf.h"(863)
inline int streamPeek(char & c, Stream<CharArray<char const *> > & stream);       	// "core/include/seqan/stream/stream_char_array.h"(290)
inline int streamPeek(char & c, Stream<CharArray<char *> > & stream);       	// "core/include/seqan/stream/stream_char_array.h"(296)
inline int streamPeek(char & c, Stream<GZFile> & stream);       	// "core/include/seqan/stream/stream_gz_file.h"(325)

//____________________________________________________________________________
// streamPut

inline int streamPut(FILE * stream, char const * source);       	// "core/include/seqan/stream/adapt_cstdio.h"(247)
template <typename TSpec> inline int streamPut(FILE * stream, String<char, TSpec> const & source);       	// "core/include/seqan/stream/adapt_cstdio.h"(255)
template <typename TSpec, typename TSpec2> inline int streamPut(FILE * stream, String<SimpleType<unsigned char, TSpec>, TSpec2> const & source);       	// "core/include/seqan/stream/adapt_cstdio.h"(264)
inline int streamPut(FILE * stream, char const c);       	// "core/include/seqan/stream/adapt_cstdio.h"(274)
template <typename TValue, typename TSpec> inline int streamPut(FILE * stream, SimpleType<TValue, TSpec> const & c);       	// "core/include/seqan/stream/adapt_cstdio.h"(281)
template <typename TSource> inline int streamPut(FILE * stream, TSource const & source);       	// "core/include/seqan/stream/adapt_cstdio.h"(342)
inline int streamPut(::std::fstream & stream, char const c);       	// "core/include/seqan/stream/adapt_fstream.h"(462)
template <typename TValue, typename TSpec> inline int streamPut(::std::fstream & stream, SimpleType<TValue, TSpec> const & c);       	// "core/include/seqan/stream/adapt_fstream.h"(470)
inline int streamPut(::std::fstream & stream, char const * source);       	// "core/include/seqan/stream/adapt_fstream.h"(478)
template <typename TSpec> inline int streamPut(::std::fstream & stream, String<char, TSpec> const & source);       	// "core/include/seqan/stream/adapt_fstream.h"(486)
template <typename TValue, typename TSpec, typename TSpec2> inline int streamPut(::std::fstream & stream, String<SimpleType<TValue, TSpec>, TSpec2> const & source);       	// "core/include/seqan/stream/adapt_fstream.h"(495)
template <typename TSource> inline int streamPut(::std::fstream & stream, TSource const & source);       	// "core/include/seqan/stream/adapt_fstream.h"(506)
inline int streamPut(::std::ofstream & stream, char const c);       	// "core/include/seqan/stream/adapt_fstream.h"(516)
template <typename TValue, typename TSpec> inline int streamPut(::std::ofstream & stream, SimpleType<TValue, TSpec> const & c);       	// "core/include/seqan/stream/adapt_fstream.h"(524)
inline int streamPut(::std::ofstream & stream, char const * source);       	// "core/include/seqan/stream/adapt_fstream.h"(532)
template <typename TSpec> inline int streamPut(::std::ofstream & stream, String<char, TSpec> const & source);       	// "core/include/seqan/stream/adapt_fstream.h"(540)
template <typename TSource> inline int streamPut(::std::ofstream & stream, TSource const & source);       	// "core/include/seqan/stream/adapt_fstream.h"(550)
inline int streamPut(::std::ostream & stream, char const c);       	// "core/include/seqan/stream/adapt_iostream.h"(312)
template <typename TValue, typename TSpec> inline int streamPut(::std::ostream & stream, SimpleType<TValue, TSpec> const & c);       	// "core/include/seqan/stream/adapt_iostream.h"(320)
inline int streamPut(::std::ostream & stream, char const * source);       	// "core/include/seqan/stream/adapt_iostream.h"(328)
template <typename TSpec> inline int streamPut(::std::ostream & stream, String<char, TSpec> const & source);       	// "core/include/seqan/stream/adapt_iostream.h"(336)
template <typename TSource> inline int streamPut(::std::ostream & stream, TSource const & source);       	// "core/include/seqan/stream/adapt_iostream.h"(346)
template <typename TValue, typename TSpec> inline int streamPut(String<TValue, TSpec> & stream, char const c);       	// "core/include/seqan/stream/adapt_mmap.h"(101)
template <typename TValue1, typename TSpec1, typename TValue2, typename TSpec2> inline int streamPut(String<TValue1, TSpec1> & stream, SimpleType<TValue2, TSpec2> const & c);       	// "core/include/seqan/stream/adapt_mmap.h"(110)
template <typename TValue, typename TSpec, typename TValue2, typename TSpec2> inline int streamPut(String<TValue, TSpec> & stream, String<TValue2, TSpec2> const & source);       	// "core/include/seqan/stream/adapt_mmap.h"(131)
template <typename TValue, typename TSpec> inline int streamPut(String<TValue, TSpec> & stream, char const *source);       	// "core/include/seqan/stream/adapt_mmap.h"(150)
template <typename TValue, typename TSpec, typename TSource> inline int streamPut(String<TValue, TSpec> & stream, TSource const & source);       	// "core/include/seqan/stream/adapt_mmap.h"(160)
inline int streamPut(::std::stringstream & stream, char const c);       	// "core/include/seqan/stream/adapt_sstream.h"(419)
template <typename TValue, typename TSpec> inline int streamPut(::std::stringstream & stream, SimpleType<TValue, TSpec> const & c);       	// "core/include/seqan/stream/adapt_sstream.h"(427)
inline int streamPut(::std::stringstream & stream, char const * source);       	// "core/include/seqan/stream/adapt_sstream.h"(435)
template <typename TSpec> inline int streamPut(::std::stringstream & stream, String<char, TSpec> const & source);       	// "core/include/seqan/stream/adapt_sstream.h"(443)
template <typename TValue, typename TSpec, typename TSpec2> inline int streamPut(::std::stringstream & stream, String<SimpleType<TValue, TSpec>, TSpec2> const & source);       	// "core/include/seqan/stream/adapt_sstream.h"(452)
template <typename TSource> inline int streamPut(::std::stringstream & stream, TSource const & source);       	// "core/include/seqan/stream/adapt_sstream.h"(463)
inline int streamPut(::std::ostringstream & stream, char const c);       	// "core/include/seqan/stream/adapt_sstream.h"(473)
template <typename TValue, typename TSpec> inline int streamPut(::std::ostringstream & stream, SimpleType<TValue, TSpec> const & c);       	// "core/include/seqan/stream/adapt_sstream.h"(481)
inline int streamPut(::std::ostringstream & stream, char const * source);       	// "core/include/seqan/stream/adapt_sstream.h"(489)
template <typename TSpec> inline int streamPut(::std::ostringstream & stream, String<char, TSpec> const & source);       	// "core/include/seqan/stream/adapt_sstream.h"(497)
template <typename TSource> inline int streamPut(::std::ostringstream & stream, TSource const & source);       	// "core/include/seqan/stream/adapt_sstream.h"(507)
template <typename TStream> inline int streamPut(Stream<TStream> & stream, char const c);       	// "core/include/seqan/stream/stream_base.h"(119)
template <typename TStream, typename TSpec> inline int streamPut(Stream<TStream> & stream, String<char, TSpec> const & source);       	// "core/include/seqan/stream/stream_base.h"(128)
template <typename TStream, typename TSource> inline int streamPut(TStream & stream, TSource const & source);       	// "core/include/seqan/stream/stream_base.h"(204)

//____________________________________________________________________________
// streamReadBlock

inline size_t streamReadBlock(char * target, FILE * stream, size_t maxLen);       	// "core/include/seqan/stream/adapt_cstdio.h"(212)
inline size_t streamReadBlock(char * target, ::std::fstream & stream, size_t maxLen);       	// "core/include/seqan/stream/adapt_fstream.h"(390)
inline size_t streamReadBlock(char * target, ::std::ifstream & stream, size_t maxLen);       	// "core/include/seqan/stream/adapt_fstream.h"(396)
inline size_t streamReadBlock(char * target, ::std::istream & stream, size_t maxLen);       	// "core/include/seqan/stream/adapt_iostream.h"(279)
inline size_t streamReadBlock(char * target, ::std::stringstream & stream, size_t maxLen);       	// "core/include/seqan/stream/adapt_sstream.h"(362)
inline size_t streamReadBlock(char * target, ::std::istringstream & stream, size_t maxLen);       	// "core/include/seqan/stream/adapt_sstream.h"(370)
inline size_t streamReadBlock(char * target, Stream<Bgzf> & stream, size_t maxLen);       	// "core/include/seqan/stream/stream_bgzf.h"(1003)
inline size_t streamReadBlock(char * target, Stream<BZ2File> & stream, size_t maxLen);       	// "core/include/seqan/stream/stream_bz2_file.h"(371)
inline size_t streamReadBlock(char * target, Stream<CharArray<char const *> > & stream, size_t maxLen);       	// "core/include/seqan/stream/stream_char_array.h"(368)
inline size_t streamReadBlock(char * target, Stream<CharArray<char *> > & stream, size_t maxLen);       	// "core/include/seqan/stream/stream_char_array.h"(374)
inline size_t streamReadBlock(char * target, Stream<GZFile> & stream, size_t maxLen);       	// "core/include/seqan/stream/stream_gz_file.h"(378)

//____________________________________________________________________________
// streamReadChar

inline int streamReadChar(char & c, FILE * stream);       	// "core/include/seqan/stream/adapt_cstdio.h"(179)
inline int streamReadChar(char & c, ::std::fstream & stream);       	// "core/include/seqan/stream/adapt_fstream.h"(310)
inline int streamReadChar(char & c, ::std::ifstream & stream);       	// "core/include/seqan/stream/adapt_fstream.h"(316)
inline int streamReadChar(char & c, ::std::istream & stream);       	// "core/include/seqan/stream/adapt_iostream.h"(229)
inline int streamReadChar(char & c, ::std::stringstream & stream);       	// "core/include/seqan/stream/adapt_sstream.h"(288)
inline int streamReadChar(char & c, ::std::istringstream & stream);       	// "core/include/seqan/stream/adapt_sstream.h"(296)
inline int streamReadChar(char & c, Stream<Bgzf> & stream);       	// "core/include/seqan/stream/stream_bgzf.h"(885)
inline int streamReadChar(char & c, Stream<BZ2File> & stream);       	// "core/include/seqan/stream/stream_bz2_file.h"(346)
inline int streamReadChar(char & c, Stream<CharArray<char const *> > & stream);       	// "core/include/seqan/stream/stream_char_array.h"(319)
inline int streamReadChar(char & c, Stream<CharArray<char *> > & stream);       	// "core/include/seqan/stream/stream_char_array.h"(325)
inline int streamReadChar(char & c, Stream<GZFile> & stream);       	// "core/include/seqan/stream/stream_gz_file.h"(340)

//____________________________________________________________________________
// streamSeek

inline int streamSeek(FILE * stream, long int delta, int origin);       	// "core/include/seqan/stream/adapt_cstdio.h"(366)
inline int streamSeek(::std::fstream & stream, long int delta, int origin);       	// "core/include/seqan/stream/adapt_fstream.h"(579)
inline int streamSeek(::std::ifstream & stream, long int delta, int origin);       	// "core/include/seqan/stream/adapt_fstream.h"(593)
inline int streamSeek(::std::ofstream & stream, long int delta, int origin);       	// "core/include/seqan/stream/adapt_fstream.h"(605)
inline int streamSeek(::std::stringstream & stream, long int delta, int origin);       	// "core/include/seqan/stream/adapt_sstream.h"(536)
inline int streamSeek(::std::istringstream & stream, long int delta, int origin);       	// "core/include/seqan/stream/adapt_sstream.h"(553)
inline int streamSeek(::std::ostringstream & stream, long int delta, int origin);       	// "core/include/seqan/stream/adapt_sstream.h"(565)
inline int streamSeek(Stream<Bgzf> & stream, __uint64 virtualPos, int origin);       	// "core/include/seqan/stream/stream_bgzf.h"(1105)
inline int streamSeek(Stream<CharArray<char const *> > & stream, ptrdiff_t delta, int origin);       	// "core/include/seqan/stream/stream_char_array.h"(454)
inline int streamSeek(Stream<CharArray<char *> > & stream, ptrdiff_t delta, int origin);       	// "core/include/seqan/stream/stream_char_array.h"(460)
inline int streamSeek(Stream<GZFile> & stream, long int delta, int origin);       	// "core/include/seqan/stream/stream_gz_file.h"(423)

//____________________________________________________________________________
// streamTell

inline Position<FILE *>::Type streamTell(FILE * stream);       	// "core/include/seqan/stream/adapt_cstdio.h"(376)
inline Position< ::std::fstream>::Type streamTell(::std::fstream & stream);       	// "core/include/seqan/stream/adapt_fstream.h"(621)
inline Position< ::std::fstream>::Type streamTell(::std::ifstream & stream);       	// "core/include/seqan/stream/adapt_fstream.h"(629)
inline Position< ::std::fstream>::Type streamTell(::std::ofstream & stream);       	// "core/include/seqan/stream/adapt_fstream.h"(636)
inline Position< ::std::stringstream>::Type streamTell(::std::stringstream & stream);       	// "core/include/seqan/stream/adapt_sstream.h"(581)
inline Position< ::std::stringstream>::Type streamTell(::std::istringstream & stream);       	// "core/include/seqan/stream/adapt_sstream.h"(589)
inline Position< ::std::stringstream>::Type streamTell(::std::ostringstream & stream);       	// "core/include/seqan/stream/adapt_sstream.h"(596)
inline Position<Stream<Bgzf> >::Type streamTell(Stream<Bgzf> & stream);       	// "core/include/seqan/stream/stream_bgzf.h"(1142)
inline size_t streamTell(Stream<CharArray<char *> > & stream);       	// "core/include/seqan/stream/stream_char_array.h"(470)
inline size_t streamTell(Stream<CharArray<char const *> > & stream);       	// "core/include/seqan/stream/stream_char_array.h"(476)
inline Position<Stream<GZFile> >::Type streamTell(Stream<GZFile> & stream);       	// "core/include/seqan/stream/stream_gz_file.h"(434)

//____________________________________________________________________________
// streamWriteBlock

inline size_t streamWriteBlock(FILE * stream, char const * source, size_t count);       	// "core/include/seqan/stream/adapt_cstdio.h"(235)
inline size_t streamWriteBlock(::std::fstream & stream, char const * source, size_t count);       	// "core/include/seqan/stream/adapt_fstream.h"(443)
inline size_t streamWriteBlock(::std::ofstream & stream, char const * source, size_t count);       	// "core/include/seqan/stream/adapt_fstream.h"(449)
inline size_t streamWriteBlock(::std::ostream & stream, char const * source, size_t count);       	// "core/include/seqan/stream/adapt_iostream.h"(299)
template <typename TValue, typename TSpec> inline int streamWriteBlock(String<TValue, TSpec> & stream, char const * ptr, unsigned count);       	// "core/include/seqan/stream/adapt_mmap.h"(87)
inline size_t streamWriteBlock(::std::stringstream & stream, char const * source, size_t count);       	// "core/include/seqan/stream/adapt_sstream.h"(398)
inline size_t streamWriteBlock(::std::ostringstream & stream, char const * source, size_t count);       	// "core/include/seqan/stream/adapt_sstream.h"(406)
inline size_t streamWriteBlock(Stream<Bgzf> & stream, char const * source, size_t count);       	// "core/include/seqan/stream/stream_bgzf.h"(1056)
inline size_t streamWriteBlock(Stream<BZ2File> & stream, char const * source, size_t count);       	// "core/include/seqan/stream/stream_bz2_file.h"(392)
inline size_t streamWriteBlock(Stream<CharArray<char *> > & stream, char const * source, size_t count);       	// "core/include/seqan/stream/stream_char_array.h"(401)
inline size_t streamWriteBlock(Stream<GZFile> & stream, char const * source, size_t count);       	// "core/include/seqan/stream/stream_gz_file.h"(401)

//____________________________________________________________________________
// streamWriteChar

inline int streamWriteChar(FILE * stream, char const c);       	// "core/include/seqan/stream/adapt_cstdio.h"(222)
inline int streamWriteChar(::std::fstream & stream, char const c);       	// "core/include/seqan/stream/adapt_fstream.h"(419)
inline int streamWriteChar(::std::ofstream & stream, char const c);       	// "core/include/seqan/stream/adapt_fstream.h"(425)
inline int streamWriteChar(::std::ostream & stream, char const c);       	// "core/include/seqan/stream/adapt_iostream.h"(289)
template <typename TValue, typename TSpec> inline int streamWriteChar(String<TValue, TSpec> & stream, char c);       	// "core/include/seqan/stream/adapt_mmap.h"(75)
inline int streamWriteChar(::std::stringstream & stream, char const c);       	// "core/include/seqan/stream/adapt_sstream.h"(380)
inline int streamWriteChar(::std::ostringstream & stream, char const c);       	// "core/include/seqan/stream/adapt_sstream.h"(388)
inline int streamWriteChar(Stream<Bgzf> & stream, char const c);       	// "core/include/seqan/stream/stream_bgzf.h"(1095)
inline int streamWriteChar(Stream<BZ2File> & stream, char const c);       	// "core/include/seqan/stream/stream_bz2_file.h"(381)
inline int streamWriteChar(Stream<CharArray<char *> > & stream, char const c);       	// "core/include/seqan/stream/stream_char_array.h"(384)
inline int streamWriteChar(Stream<GZFile> & stream, char const c);       	// "core/include/seqan/stream/stream_gz_file.h"(391)

//____________________________________________________________________________
// value

template <typename TFile> inline char value(RecordReader<TFile, DoublePass<> > & recordReader);       	// "core/include/seqan/stream/record_reader_double.h"(357)
template <typename TMMapString> inline char value(RecordReader<TMMapString, DoublePass<Mapped> > & recordReader);       	// "core/include/seqan/stream/record_reader_double_mmap.h"(178)
template <typename TFile> inline char value(RecordReader<TFile, SinglePass<void> > & recordReader);       	// "core/include/seqan/stream/record_reader_single.h"(213)
template <typename TMMapString> inline char value(RecordReader<TMMapString, SinglePass<Mapped> > & recordReader);       	// "core/include/seqan/stream/record_reader_single_mmap.h"(162)

} //namespace seqan

//____________________________________________________________________________
// isblank

inline int isblank(int c);       	// "core/include/seqan/stream/is.h"(165)

#endif

