// ==========================================================================
//                 SeqAn - The Library for Sequence Analysis
// ==========================================================================
// Copyright (c) 2006-2010, Knut Reinert, FU Berlin
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
//     * Redistributions of source code must retain the above copyright
//       notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above copyright
//       notice, this list of conditions and the following disclaimer in the
//       documentation and/or other materials provided with the distribution.
//     * Neither the name of Knut Reinert or the FU Berlin nor the names of
//       its contributors may be used to endorse or promote products derived
//       from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL KNUT REINERT OR THE FU BERLIN BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
// LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
// OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
// DAMAGE.
//
// ==========================================================================


#ifndef SEQAN_HEADER_MISC_GENERATED_FORWARDS_H 
#define SEQAN_HEADER_MISC_GENERATED_FORWARDS_H 

//////////////////////////////////////////////////////////////////////////////
// NOTE: This file is automatically generated by build_forwards.py
//       Do not edit this file manually!
//////////////////////////////////////////////////////////////////////////////


//////////////////////////////////////////////////////////////////////////////
// CLASSES
//////////////////////////////////////////////////////////////////////////////

namespace SEQAN_NAMESPACE_MAIN {

//____________________________________________________________________________
// Dequeue

template <typename TValue, typename TSpec > class Dequeue;       	// "core/include/seqan/misc/misc_dequeue.h"(58)

//____________________________________________________________________________
// IntervalAndCargo

template <typename TValue , typename TCargo > class IntervalAndCargo;       	// "core/include/seqan/misc/misc_interval_tree.h"(65)

//____________________________________________________________________________
// IntervalTree

template <typename TValue, typename TCargo> class IntervalTree;       	// "core/include/seqan/misc/misc_interval_tree.h"(298)

//____________________________________________________________________________
// IntervalTreeNode

template <typename TInterval, typename TSpec> class IntervalTreeNode;       	// "core/include/seqan/misc/misc_interval_tree.h"(215)

//____________________________________________________________________________
// ListType

template <typename T> struct ListType;       	// "core/include/seqan/misc/misc_interval_tree.h"(813)

//____________________________________________________________________________
// MersenneBuffer_

template <typename T > struct MersenneBuffer_;       	// "core/include/seqan/misc/misc_random.h"(69)

//____________________________________________________________________________
// Object

template <typename TElement> struct Object;       	// "core/include/seqan/misc/misc_base.h"(68)

//____________________________________________________________________________
// PointAndCargo

template <typename TValue, typename TCargo> class PointAndCargo;       	// "core/include/seqan/misc/misc_interval_tree.h"(130)

//____________________________________________________________________________
// PriorityHeap

struct PriorityHeap;       	// "core/include/seqan/misc/priority_type_base.h"(43)

//____________________________________________________________________________
// PriorityType

template <typename TValue , typename TLess , typename TSpec > class PriorityType;       	// "core/include/seqan/misc/priority_type_base.h"(62)

//____________________________________________________________________________
// SVGFile

struct SVGFile;       	// "core/include/seqan/misc/misc_svg.h"(44)

//____________________________________________________________________________
// Set

template <typename TKey> struct Set;       	// "core/include/seqan/misc/misc_set.h"(562)

//____________________________________________________________________________
// SetLess_

template <typename TElement> struct SetLess_;       	// "core/include/seqan/misc/misc_set.h"(379)

//____________________________________________________________________________
// SetObjVector_

template <typename TSet> struct SetObjVector_;       	// "core/include/seqan/misc/misc_set.h"(83)

//____________________________________________________________________________
// SetSetVector_

template <typename TSet> struct SetSetVector_;       	// "core/include/seqan/misc/misc_set.h"(68)

//____________________________________________________________________________
// StoreIntervals

struct StoreIntervals;       	// "core/include/seqan/misc/misc_interval_tree.h"(188)

//____________________________________________________________________________
// StorePointsOnly

struct StorePointsOnly;       	// "core/include/seqan/misc/misc_interval_tree.h"(184)

//____________________________________________________________________________
// TagComputeCenter_

struct TagComputeCenter_;       	// "core/include/seqan/misc/misc_interval_tree.h"(427)

//____________________________________________________________________________
// TagRandomCenter_

struct TagRandomCenter_;       	// "core/include/seqan/misc/misc_interval_tree.h"(438)

//____________________________________________________________________________
// VectorSetIterator_

struct VectorSetIterator_;       	// "core/include/seqan/misc/misc_set.h"(173)

//____________________________________________________________________________
// VectorSetKeySize_

template <typename TElement> struct VectorSetKeySize_;       	// "core/include/seqan/misc/misc_set.h"(62)

//____________________________________________________________________________
// VectorSet_

template <typename TElement, typename TSpec> class VectorSet_;       	// "core/include/seqan/misc/misc_set.h"(55)
template <typename TElement , typename TSpec > class VectorSet_;       	// "core/include/seqan/misc/misc_set.h"(103)

} //namespace SEQAN_NAMESPACE_MAIN
//////////////////////////////////////////////////////////////////////////////

namespace seqan {

//____________________________________________________________________________
// Accumulator

template <typename TValue, typename TSpec> struct Accumulator;       	// "core/include/seqan/misc/misc_accumulators.h"(80)

//____________________________________________________________________________
// Average_

struct Average_;       	// "core/include/seqan/misc/misc_accumulators.h"(58)

//____________________________________________________________________________
// CommandLineOption

class CommandLineOption;       	// "core/include/seqan/misc/cmdparser/cmdoption.h"(113)

//____________________________________________________________________________
// CommandLineParser

class CommandLineParser;       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(72)

//____________________________________________________________________________
// Count_

struct Count_;       	// "core/include/seqan/misc/misc_accumulators.h"(64)

//____________________________________________________________________________
// DynamicWidth_

struct DynamicWidth_;       	// "core/include/seqan/misc/misc_long_word.h"(68)

//____________________________________________________________________________
// EditEnvironment

template <typename TDistanceSpec, unsigned DISTANCE > struct EditEnvironment;       	// "core/include/seqan/misc/edit_environment.h"(51)

//____________________________________________________________________________
// LongWord

template <typename TSpec> struct LongWord;       	// "core/include/seqan/misc/misc_long_word.h"(53)

//____________________________________________________________________________
// LongWordBitProxy

template <typename TWord, typename TSpec> struct LongWordBitProxy;       	// "core/include/seqan/misc/misc_long_word.h"(57)

//____________________________________________________________________________
// MemsetConstValueWorker

template <unsigned SIZE, bool direct, unsigned char c> struct MemsetConstValueWorker;       	// "core/include/seqan/misc/misc_memset.h"(153)

//____________________________________________________________________________
// MemsetWorker

template <unsigned SIZE, bool direct> struct MemsetWorker;       	// "core/include/seqan/misc/misc_memset.h"(86)

//____________________________________________________________________________
// OptionType

struct OptionType;       	// "core/include/seqan/misc/cmdparser/cmdoption.h"(48)

//____________________________________________________________________________
// Result

template <typename T, typename TTag> struct Result;       	// "core/include/seqan/misc/misc_accumulators.h"(52)
template <typename T, typename TTag > struct Result;       	// "core/include/seqan/misc/misc_accumulators.h"(157)

//____________________________________________________________________________
// StaticWidth

template <unsigned LENGTH> struct StaticWidth;       	// "core/include/seqan/misc/misc_long_word.h"(73)

//____________________________________________________________________________
// StringEnumerator

template <typename TObject, typename TSpec> class StringEnumerator;       	// "core/include/seqan/misc/edit_environment.h"(116)

//____________________________________________________________________________
// StringEnumeratorHammingModifier_

template <typename TSize> struct StringEnumeratorHammingModifier_;       	// "core/include/seqan/misc/edit_environment.h"(141)

//____________________________________________________________________________
// StringEnumeratorLevenshteinModifier_

template <typename TSize> struct StringEnumeratorLevenshteinModifier_;       	// "core/include/seqan/misc/edit_environment.h"(195)

//____________________________________________________________________________
// Sum_

struct Sum_;       	// "core/include/seqan/misc/misc_accumulators.h"(61)

//____________________________________________________________________________
// UnionFind

template <typename TValue> class UnionFind;       	// "core/include/seqan/misc/misc_union_find.h"(65)

//____________________________________________________________________________
// _NativeWideWidth

struct _NativeWideWidth;       	// "core/include/seqan/misc/misc_long_word.h"(64)

//____________________________________________________________________________
// _NativeWidth

struct _NativeWidth;       	// "core/include/seqan/misc/misc_long_word.h"(60)

} //namespace seqan


//////////////////////////////////////////////////////////////////////////////
// TYPEDEFS
//////////////////////////////////////////////////////////////////////////////

namespace SEQAN_NAMESPACE_MAIN {

//____________________________________________________________________________
// ComputeCenter

typedef Tag<TagComputeCenter_> const ComputeCenter;       	// "core/include/seqan/misc/misc_interval_tree.h"(428)

//____________________________________________________________________________
// RandomCenter

typedef Tag<TagRandomCenter_> const RandomCenter;       	// "core/include/seqan/misc/misc_interval_tree.h"(439)

//____________________________________________________________________________
// VectorSetIterator__

typedef Tag<VectorSetIterator_> VectorSetIterator__;       	// "core/include/seqan/misc/misc_set.h"(174)

} //namespace SEQAN_NAMESPACE_MAIN
//////////////////////////////////////////////////////////////////////////////

namespace seqan {

//____________________________________________________________________________
// Average

typedef Tag<Average_> Average;       	// "core/include/seqan/misc/misc_accumulators.h"(59)

//____________________________________________________________________________
// Count

typedef Tag<Count_> Count;       	// "core/include/seqan/misc/misc_accumulators.h"(65)

//____________________________________________________________________________
// DynamicWidth

typedef Tag<DynamicWidth_> DynamicWidth;       	// "core/include/seqan/misc/misc_long_word.h"(69)

//____________________________________________________________________________
// NativeWideWidth

typedef Tag<_NativeWideWidth> NativeWideWidth;       	// "core/include/seqan/misc/misc_long_word.h"(65)

//____________________________________________________________________________
// NativeWidth

typedef Tag<_NativeWidth> NativeWidth;       	// "core/include/seqan/misc/misc_long_word.h"(61)

//____________________________________________________________________________
// Sum

typedef Tag<Sum_> Sum;       	// "core/include/seqan/misc/misc_accumulators.h"(62)

} //namespace seqan


//////////////////////////////////////////////////////////////////////////////
// FUNCTIONS
//////////////////////////////////////////////////////////////////////////////

namespace SEQAN_NAMESPACE_MAIN {

//____________________________________________________________________________
// _adjustHeapTowardLeaves

template <typename TValue, typename TLess, typename TSize> inline void _adjustHeapTowardLeaves( PriorityType<TValue, TLess, PriorityHeap> & me, TValue element, TSize h, TSize i );       	// "core/include/seqan/misc/priority_type_heap.h"(296)

//____________________________________________________________________________
// _adjustHeapTowardRoot

template <typename TValue, typename TLess, typename TSize> inline void _adjustHeapTowardRoot( PriorityType<TValue, TLess, PriorityHeap> & me, TValue const & element, TSize h );       	// "core/include/seqan/misc/priority_type_heap.h"(243)

//____________________________________________________________________________
// _alignNeedlemanWunschMatrix

template <typename TStringSet, typename TTrace, typename TIndexPair> void _alignNeedlemanWunschMatrix(SVGFile& svg, TStringSet const& str, TTrace const& trace, TIndexPair const&);       	// "core/include/seqan/misc/misc_svg.h"(427)

//____________________________________________________________________________
// _alignTracePrint

template <typename TStringSet, typename TId, typename TPos, typename TTraceValue> inline void _alignTracePrint(SVGFile& svg, TStringSet const&, TId const, TPos pos1, TId const, TPos pos2, TPos const segLen, TTraceValue const tv);       	// "core/include/seqan/misc/misc_svg.h"(476)

//____________________________________________________________________________
// _appendIntervalTreeNodeLists

template <typename TInterval> void _appendIntervalTreeNodeLists(IntervalTreeNode<TInterval,StoreIntervals> & knot,TInterval & interval);       	// "core/include/seqan/misc/misc_interval_tree.h"(747)
template <typename TInterval> void _appendIntervalTreeNodeLists(IntervalTreeNode<TInterval,StorePointsOnly> & knot,TInterval & interval);       	// "core/include/seqan/misc/misc_interval_tree.h"(774)

//____________________________________________________________________________
// _calcIntervalTreeNodeCenterLeft

template <typename TIntervals, typename TValue> TValue _calcIntervalTreeNodeCenterLeft(TIntervals & intervals, TValue &, TValue &, Tag<TagRandomCenter_> const);       	// "core/include/seqan/misc/misc_interval_tree.h"(1200)

//____________________________________________________________________________
// _calcIntervalTreeNodeCenterRight

template <typename TIntervals, typename TValue> TValue _calcIntervalTreeNodeCenterRight(TIntervals & intervals, TValue &, TValue &, Tag<TagRandomCenter_> const);       	// "core/include/seqan/misc/misc_interval_tree.h"(1212)

//____________________________________________________________________________
// _calcIntervalTreeRootCenter

template <typename TIntervals> typename Value<typename Value<TIntervals>::Type>::Type _calcIntervalTreeRootCenter(TIntervals & intervals);       	// "core/include/seqan/misc/misc_interval_tree.h"(1224)

//____________________________________________________________________________
// _copyHeapElement

template <typename TValue, typename TLess, typename TSize> inline void _copyHeapElement (PriorityType<TValue, TLess, PriorityHeap> & me, TSize i, TSize & h);       	// "core/include/seqan/misc/priority_type_heap.h"(161)
template <typename TValue, typename TLess, typename TSize> inline void _copyHeapElement (PriorityType<TValue, TLess, PriorityHeap> & me, TValue const & element, TSize h);       	// "core/include/seqan/misc/priority_type_heap.h"(171)

//____________________________________________________________________________
// _createIntervalTree

template <typename TGraph, typename TPropertyMap, typename TIntervalPointer, typename TValue> void _createIntervalTree(TGraph & g, TPropertyMap & pm, String<TIntervalPointer*> & intervals, typename VertexDescriptor<TGraph>::Type & knot, TValue, TValue center, typename VertexDescriptor<TGraph>::Type len, Tag<TagComputeCenter_> const tag);       	// "core/include/seqan/misc/misc_interval_tree.h"(1000)
template <typename TGraph, typename TPropertyMap, typename TSpec, typename TInterval, typename TValue> void _createIntervalTree(TGraph & g, TPropertyMap & pm, String<TInterval*> & intervals, typename VertexDescriptor<TGraph>::Type & knot, TValue last_center, TValue center, typename VertexDescriptor<TGraph>::Type len, Tag<TSpec> const tag);       	// "core/include/seqan/misc/misc_interval_tree.h"(1099)

//____________________________________________________________________________
// _greater_compI2_ITree

template <typename TPair> bool _greater_compI2_ITree(TPair const& p1, TPair const& p2);       	// "core/include/seqan/misc/misc_interval_tree.h"(715)

//____________________________________________________________________________
// _less_compI1_ITree

template <typename TPair> bool _less_compI1_ITree(TPair const& p1, TPair const& p2);       	// "core/include/seqan/misc/misc_interval_tree.h"(708)

//____________________________________________________________________________
// _makePointerInterval

template <typename TIntervals, typename TIntervalPointers> void _makePointerInterval(TIntervals & intervals,TIntervalPointers & interval_pointers);       	// "core/include/seqan/misc/misc_interval_tree.h"(1175)

//____________________________________________________________________________
// _printContig

template <typename TFormatTag, typename TContigGaps, typename TContigName> inline void _printContig( SVGFile &svg, Tag<TFormatTag> const &format, AlignedReadLayout &, TContigGaps &contigGaps, TContigName const &contigName);       	// "core/include/seqan/misc/misc_svg.h"(226)

//____________________________________________________________________________
// _printRead

template <typename TFormatTag, typename TContigGaps, typename TReadGaps, typename TAlignedRead, typename TLine> inline void _printRead( SVGFile &svg, Tag<TFormatTag> const &, AlignedReadLayout &layout, TContigGaps &contigGaps, TReadGaps &readGaps, TAlignedRead &alignedRead, TLine line);       	// "core/include/seqan/misc/misc_svg.h"(279)

//____________________________________________________________________________
// _setIntervalTreeNode

template <typename TValue, typename TInterval> void _setIntervalTreeNode(IntervalTreeNode<TInterval,StoreIntervals> & knot,TValue center,TInterval & interval);       	// "core/include/seqan/misc/misc_interval_tree.h"(734)
template <typename TValue, typename TInterval> void _setIntervalTreeNode(IntervalTreeNode<TInterval,StorePointsOnly> & knot,TValue center,TInterval & interval);       	// "core/include/seqan/misc/misc_interval_tree.h"(760)

//____________________________________________________________________________
// addInterval

template <typename TGraph, typename TPropertyMap, typename TInterval> void addInterval(TGraph & g, TPropertyMap & pm, TInterval interval);       	// "core/include/seqan/misc/misc_interval_tree.h"(1269)
template <typename TValue, typename TCargo, typename TInterval> void addInterval(IntervalTree<TValue,TCargo> & itree, TInterval interval);       	// "core/include/seqan/misc/misc_interval_tree.h"(1369)
template <typename TValue, typename TCargo> void addInterval(IntervalTree<TValue,TCargo> & itree, TValue begin, TValue end, TCargo cargo);       	// "core/include/seqan/misc/misc_interval_tree.h"(1388)
template <typename TValue, typename TCargo> void addInterval(IntervalTree<TValue,TCargo> & itree, TValue begin, TValue end);       	// "core/include/seqan/misc/misc_interval_tree.h"(1407)

//____________________________________________________________________________
// adjustTop

template <typename TValue, typename TLess> inline void adjustTop (PriorityType<TValue, TLess, PriorityHeap> & me);       	// "core/include/seqan/misc/priority_type_heap.h"(191)

//____________________________________________________________________________
// atEnd

template <typename TSet> inline bool atEnd(Iter<TSet, VectorSetIterator__> const &a);       	// "core/include/seqan/misc/misc_set.h"(335)

//____________________________________________________________________________
// back

template <typename TValue, typename TSpec> inline TValue & back(Dequeue<TValue, TSpec> &me);       	// "core/include/seqan/misc/misc_dequeue.h"(223)
template <typename TValue, typename TSpec> inline TValue const & back(Dequeue<TValue, TSpec> const &me);       	// "core/include/seqan/misc/misc_dequeue.h"(230)

//____________________________________________________________________________
// begin

template <typename TElement, typename TSpec> inline typename Iterator< VectorSet_<TElement, TSpec> >::Type begin(VectorSet_<TElement, TSpec> &set);       	// "core/include/seqan/misc/misc_set.h"(294)
template <typename TElement, typename TSpec> inline typename Iterator< VectorSet_<TElement, TSpec> const>::Type begin(VectorSet_<TElement, TSpec> const &set);       	// "core/include/seqan/misc/misc_set.h"(300)

//____________________________________________________________________________
// cargo

template <typename TValue, typename TCargo> TCargo & cargo(IntervalAndCargo<TValue,TCargo> & interval);       	// "core/include/seqan/misc/misc_interval_tree.h"(548)
template <typename TValue, typename TCargo> TCargo & cargo(PointAndCargo<TValue,TCargo> & point);       	// "core/include/seqan/misc/misc_interval_tree.h"(663)

//____________________________________________________________________________
// clear

template <typename TValue, typename TSpec> inline void clear(Dequeue<TValue, TSpec> &me);       	// "core/include/seqan/misc/misc_dequeue.h"(165)
template <typename TValue, typename TSpec> finline void clear(VectorSet_<TValue, TSpec> &set);       	// "core/include/seqan/misc/misc_set.h"(228)
template <typename TValue, typename TLess> inline void clear (PriorityType<TValue,TLess, PriorityHeap> & me);       	// "core/include/seqan/misc/priority_type_heap.h"(96)

//____________________________________________________________________________
// close

inline bool close(SVGFile &svg);       	// "core/include/seqan/misc/misc_svg.h"(186)

//____________________________________________________________________________
// createIntervalTree

template <typename TGraph, typename TPropertyMap, typename TIntervals, typename TSpec> void createIntervalTree(TGraph & g, TPropertyMap & pm, TIntervals & intervals, Tag<TSpec> const tag);       	// "core/include/seqan/misc/misc_interval_tree.h"(864)
template <typename TGraph, typename TPropertyMap, typename TIntervals> void createIntervalTree(TGraph & g, TPropertyMap & pm, TIntervals & intervals);       	// "core/include/seqan/misc/misc_interval_tree.h"(905)
template <typename TValue,typename TCargo, typename TIntervals> void createIntervalTree(IntervalTree<TValue,TCargo> & it, TIntervals & intervals);       	// "core/include/seqan/misc/misc_interval_tree.h"(922)
template <typename TGraph, typename TPropertyMap, typename TIntervals, typename TSpec> void createIntervalTree(TGraph & g, TPropertyMap & pm, TIntervals & intervals, typename Value<typename Value<TIntervals>::Type>::Type center, Tag<TSpec> const tag);       	// "core/include/seqan/misc/misc_interval_tree.h"(939)
template <typename TGraph, typename TPropertyMap, typename TIntervals> void createIntervalTree(TGraph & g, TPropertyMap & pm, TIntervals & intervals, typename Value<typename Value<TIntervals>::Type>::Type center);       	// "core/include/seqan/misc/misc_interval_tree.h"(981)

//____________________________________________________________________________
// empty

template <typename TValue, typename TSpec> inline bool empty(Dequeue<TValue, TSpec> const &me);       	// "core/include/seqan/misc/misc_dequeue.h"(156)
template <typename TValue, typename TLess> inline bool empty(PriorityType<TValue, TLess, PriorityHeap> const & me);       	// "core/include/seqan/misc/priority_type_heap.h"(106)

//____________________________________________________________________________
// end

template <typename TElement, typename TSpec> inline typename Iterator< VectorSet_<TElement, TSpec> >::Type end(VectorSet_<TElement, TSpec> &set);       	// "core/include/seqan/misc/misc_set.h"(307)
template <typename TElement, typename TSpec> inline typename Iterator< VectorSet_<TElement, TSpec> const>::Type end(VectorSet_<TElement, TSpec> const &set);       	// "core/include/seqan/misc/misc_set.h"(313)

//____________________________________________________________________________
// eof

template <typename TSet> inline bool eof(Iter<TSet, VectorSetIterator__> const &a);       	// "core/include/seqan/misc/misc_set.h"(330)

//____________________________________________________________________________
// erase

template <typename TKey, typename TValue, typename TSpec> finline void erase(TKey const &key, VectorSet_<TValue, TSpec> &set);       	// "core/include/seqan/misc/misc_set.h"(258)

//____________________________________________________________________________
// find

template <typename TKey, typename TKey2, typename TSpec> inline typename Iterator< VectorSet_<TKey2, TSpec> >::Type find(TKey const &key, VectorSet_<TKey2, TSpec> &set);       	// "core/include/seqan/misc/misc_set.h"(273)
template <typename TKey, typename TKey2, typename TSpec> inline typename Iterator< VectorSet_<TKey2, TSpec> const>::Type find(TKey const &key, VectorSet_<TKey2, TSpec> const &set);       	// "core/include/seqan/misc/misc_set.h"(283)

//____________________________________________________________________________
// findIntervals

template <typename TGraph, typename TPropertyMap, typename TValue,typename TCargo> void findIntervals(TGraph & g, TPropertyMap & pm, TValue query, String<TCargo> & result);       	// "core/include/seqan/misc/misc_interval_tree.h"(1431)
template <typename TValue,typename TCargo> void findIntervals(IntervalTree<TValue,TCargo> & it, TValue query, String<TCargo> & result);       	// "core/include/seqan/misc/misc_interval_tree.h"(1510)
template <typename TValue,typename TCargo> void findIntervals(IntervalTree<TValue,TCargo> & tree, TValue query_begin, TValue query_end, String<TCargo> & result);       	// "core/include/seqan/misc/misc_interval_tree.h"(1635)
template <typename TGraph, typename TPropertyMap, typename TValue,typename TCargo> void findIntervals(TGraph & g, TPropertyMap & pm, TValue query_begin, TValue query_end, String<TCargo> & result);       	// "core/include/seqan/misc/misc_interval_tree.h"(1647)
template <typename TGraph, typename TPropertyMap, typename TValue,typename TCargo> void findIntervals(TGraph & g, TPropertyMap & pm, typename VertexDescriptor<TGraph>::Type & act_knot, TValue query_begin, TValue query_end, String<TCargo> & result);       	// "core/include/seqan/misc/misc_interval_tree.h"(1670)

//____________________________________________________________________________
// findIntervalsExcludeTouching

template <typename TGraph, typename TPropertyMap, typename TValue,typename TCargo> void findIntervalsExcludeTouching(TGraph & g, TPropertyMap & pm, TValue query, String<TCargo> & result);       	// "core/include/seqan/misc/misc_interval_tree.h"(1534)
template <typename TValue,typename TCargo> void findIntervalsExcludeTouching(IntervalTree<TValue,TCargo> & tree, TValue query, String<TCargo> & result);       	// "core/include/seqan/misc/misc_interval_tree.h"(1616)

//____________________________________________________________________________
// front

template <typename TValue, typename TSpec> inline TValue & front(Dequeue<TValue, TSpec> &me);       	// "core/include/seqan/misc/misc_dequeue.h"(207)
template <typename TValue, typename TSpec> inline TValue const & front(Dequeue<TValue, TSpec> const &me);       	// "core/include/seqan/misc/misc_dequeue.h"(214)

//____________________________________________________________________________
// geomRand

template <typename T> inline T geomRand();       	// "core/include/seqan/misc/misc_random.h"(213)

//____________________________________________________________________________
// getCargo

template <typename TValue, typename TCargo> TCargo getCargo(IntervalAndCargo<TValue,TCargo> & interval);       	// "core/include/seqan/misc/misc_interval_tree.h"(564)
template <typename TValue, typename TCargo> TCargo getCargo(PointAndCargo<TValue,TCargo> & point);       	// "core/include/seqan/misc/misc_interval_tree.h"(680)

//____________________________________________________________________________
// getLeftBoundary

template <typename TValue, typename TCargo> TValue getLeftBoundary(IntervalAndCargo<TValue,TCargo> & interval);       	// "core/include/seqan/misc/misc_interval_tree.h"(509)
template <typename TValue, typename TCargo> TValue getLeftBoundary(PointAndCargo<TValue,TCargo> & point);       	// "core/include/seqan/misc/misc_interval_tree.h"(633)

//____________________________________________________________________________
// getRightBoundary

template <typename TValue, typename TCargo> TValue getRightBoundary(IntervalAndCargo<TValue,TCargo> & interval);       	// "core/include/seqan/misc/misc_interval_tree.h"(531)
template <typename TValue, typename TCargo> TValue getRightBoundary(PointAndCargo<TValue,TCargo> & point);       	// "core/include/seqan/misc/misc_interval_tree.h"(648)

//____________________________________________________________________________
// in

template <typename TKey, typename TValue, typename TSpec> finline bool in(TKey const &key, VectorSet_<TValue, TSpec> const &set);       	// "core/include/seqan/misc/misc_set.h"(267)

//____________________________________________________________________________
// insert

template <typename TElement, typename TSetKey, typename TSpec> finline void insert(TElement const &element, VectorSet_<TSetKey, TSpec> &set);       	// "core/include/seqan/misc/misc_set.h"(235)
template <typename TElement, typename TSetKey, typename TSetObject, typename TPairSpec, typename TSpec> finline void insert(TElement const &element, VectorSet_< Pair<TSetKey, TSetObject, TPairSpec>, TSpec > &set);       	// "core/include/seqan/misc/misc_set.h"(248)

//____________________________________________________________________________
// keyOf

template <typename TElement> inline typename Key<TElement>::Type & keyOf(TElement & element);       	// "core/include/seqan/misc/misc_base.h"(85)
template <typename TElement> inline typename Key<TElement const>::Type & keyOf(TElement const & element);       	// "core/include/seqan/misc/misc_base.h"(91)
template <typename TKey, typename TObject, typename TSpec> inline TKey & keyOf(Pair<TKey, TObject, TSpec> &element);       	// "core/include/seqan/misc/misc_base.h"(97)
template <typename TKey, typename TObject, typename TSpec> inline TKey const & keyOf(Pair<TKey, TObject, TSpec> const &element);       	// "core/include/seqan/misc/misc_base.h"(102)
template <typename TSet> inline typename Key<TSet>::Type keyOf(Iter<TSet, VectorSetIterator__> &it);       	// "core/include/seqan/misc/misc_set.h"(343)
template <typename TSet> inline typename Key<TSet>::Type keyOf(Iter<TSet, VectorSetIterator__> const &it);       	// "core/include/seqan/misc/misc_set.h"(348)

//____________________________________________________________________________
// leftBoundary

template <typename TValue, typename TCargo> TValue & leftBoundary(IntervalAndCargo<TValue,TCargo> & interval);       	// "core/include/seqan/misc/misc_interval_tree.h"(465)
template <typename TValue, typename TCargo> TValue & leftBoundary(PointAndCargo<TValue,TCargo> & point);       	// "core/include/seqan/misc/misc_interval_tree.h"(603)

//____________________________________________________________________________
// length

template <typename TValue, typename TSpec> inline typename Size<Dequeue<TValue, TSpec> >::Type length(Dequeue<TValue, TSpec> const &me);       	// "core/include/seqan/misc/misc_dequeue.h"(339)
template <typename TObject, typename TSpec> inline typename Size< VectorSet_<TObject, TSpec> >::Type length(VectorSet_<TObject, TSpec> const &set);       	// "core/include/seqan/misc/misc_set.h"(164)
template <typename TValue, typename TLess> inline typename Size<PriorityType<TValue, TLess, PriorityHeap> >::Type length( PriorityType<TValue, TLess, PriorityHeap> const & me);       	// "core/include/seqan/misc/priority_type_heap.h"(117)

//____________________________________________________________________________
// lognormRand

inline double lognormRand(double mean, double stddev);       	// "core/include/seqan/misc/misc_random.h"(280)

//____________________________________________________________________________
// mtRand

inline unsigned mtRand();       	// "core/include/seqan/misc/misc_random.h"(156)

//____________________________________________________________________________
// mtRandDouble

inline double mtRandDouble();       	// "core/include/seqan/misc/misc_random.h"(192)

//____________________________________________________________________________
// mtRandInit

inline void mtRandInit(bool _doSRand );       	// "core/include/seqan/misc/misc_random.h"(113)
inline void mtRandInit();       	// "core/include/seqan/misc/misc_random.h"(133)

//____________________________________________________________________________
// normRand

inline double normRand(double mean, double stddev);       	// "core/include/seqan/misc/misc_random.h"(249)

//____________________________________________________________________________
// objectOf

template <typename TKey, typename TObject, typename TSpec> inline TObject & objectOf(Pair<TKey, TObject, TSpec> &element);       	// "core/include/seqan/misc/misc_base.h"(112)
template <typename TKey, typename TObject, typename TSpec> inline TObject const & objectOf(Pair<TKey, TObject, TSpec> const &element);       	// "core/include/seqan/misc/misc_base.h"(117)
template <typename TSet> inline typename Object<TSet>::Type & objectOf(Iter<TSet, VectorSetIterator__> &it);       	// "core/include/seqan/misc/misc_set.h"(354)
template <typename TSet> inline typename Object<TSet>::Type & objectOf(Iter<TSet, VectorSetIterator__> const &it);       	// "core/include/seqan/misc/misc_set.h"(359)

//____________________________________________________________________________
// open

template <typename TFileName> inline bool open(SVGFile &svg, TFileName const &fileName);       	// "core/include/seqan/misc/misc_svg.h"(178)

//____________________________________________________________________________
// operator!=

template <typename TSet> inline bool operator!=(Iter<TSet, VectorSetIterator__> const &a, Iter<TSet, VectorSetIterator__> const &b);       	// "core/include/seqan/misc/misc_set.h"(325)

//____________________________________________________________________________
// operator<<

inline SVGFile & operator<< (SVGFile & target, char source);       	// "core/include/seqan/misc/misc_svg.h"(406)
inline SVGFile & operator<< (SVGFile & target, char const *source);       	// "core/include/seqan/misc/misc_svg.h"(414)

//____________________________________________________________________________
// operator==

template <typename TSet> inline bool operator==(Iter<TSet, VectorSetIterator__> const &a, Iter<TSet, VectorSetIterator__> const &b);       	// "core/include/seqan/misc/misc_set.h"(320)

//____________________________________________________________________________
// pop

template <typename TValue, typename TLess> inline void pop (PriorityType<TValue, TLess, PriorityHeap> & me);       	// "core/include/seqan/misc/priority_type_heap.h"(274)

//____________________________________________________________________________
// popBack

template <typename TValue, typename TSpec> inline bool popBack(Dequeue<TValue, TSpec> &me);       	// "core/include/seqan/misc/misc_dequeue.h"(256)

//____________________________________________________________________________
// popFront

template <typename TValue, typename TSpec> inline bool popFront(Dequeue<TValue, TSpec> &me);       	// "core/include/seqan/misc/misc_dequeue.h"(239)

//____________________________________________________________________________
// push

template <typename TValue, typename TLess> inline void push (PriorityType<TValue, TLess, PriorityHeap> & me, TValue const & element);       	// "core/include/seqan/misc/priority_type_heap.h"(221)

//____________________________________________________________________________
// pushBack

template <typename TValue, typename TSpec> inline void pushBack(Dequeue<TValue, TSpec> &me, TValue const & _value);       	// "core/include/seqan/misc/misc_dequeue.h"(308)

//____________________________________________________________________________
// pushFront

template <typename TValue, typename TSpec> inline void pushFront(Dequeue<TValue, TSpec> &me, TValue const & _value);       	// "core/include/seqan/misc/misc_dequeue.h"(276)

//____________________________________________________________________________
// reserve

template <typename TValue, typename TSpec, typename TSize_, typename TExpand> inline typename Size<Dequeue<TValue, TSpec> >::Type reserve(Dequeue<TValue, TSpec> &me, TSize_ new_capacity, Tag<TExpand> const tag);       	// "core/include/seqan/misc/misc_dequeue.h"(353)

//____________________________________________________________________________
// rightBoundary

template <typename TValue, typename TCargo> TValue & rightBoundary(IntervalAndCargo<TValue,TCargo> & interval);       	// "core/include/seqan/misc/misc_interval_tree.h"(487)
template <typename TValue, typename TCargo> TValue & rightBoundary(PointAndCargo<TValue,TCargo> & point);       	// "core/include/seqan/misc/misc_interval_tree.h"(618)

//____________________________________________________________________________
// streamPut

template <typename TChar> inline void streamPut(SVGFile & svg, TChar character);       	// "core/include/seqan/misc/misc_svg.h"(198)

//____________________________________________________________________________
// svgResize

inline void svgResize(SVGFile &svg, int width, int height);       	// "core/include/seqan/misc/misc_svg.h"(124)

//____________________________________________________________________________
// svgWriteFooter

inline void svgWriteFooter(SVGFile &svg);       	// "core/include/seqan/misc/misc_svg.h"(170)

//____________________________________________________________________________
// svgWriteHeader

inline void svgWriteHeader(SVGFile &svg);       	// "core/include/seqan/misc/misc_svg.h"(130)

//____________________________________________________________________________
// top

template <typename TValue, typename TLess> inline TValue & top(PriorityType<TValue, TLess, PriorityHeap> & me);       	// "core/include/seqan/misc/priority_type_heap.h"(144)
template <typename TValue, typename TLess> inline TValue const & top(PriorityType<TValue, TLess, PriorityHeap> const & me);       	// "core/include/seqan/misc/priority_type_heap.h"(152)

//____________________________________________________________________________
// value

template <typename TValue, typename TSpec, typename TPos> inline TValue & value(Dequeue<TValue, TSpec> &me, TPos pos);       	// "core/include/seqan/misc/misc_dequeue.h"(179)
template <typename TValue, typename TSpec, typename TPos> inline TValue const & value(Dequeue<TValue, TSpec> const &me, TPos pos);       	// "core/include/seqan/misc/misc_dequeue.h"(192)

} //namespace SEQAN_NAMESPACE_MAIN
//////////////////////////////////////////////////////////////////////////////

namespace seqan {

//____________________________________________________________________________
// _addMinMaxRestrictions

inline void _addMinMaxRestrictions(StringSet<CharString> & restrictions, CommandLineOption const & opt);       	// "core/include/seqan/misc/cmdparser/cmdparser_ctd_support.h"(108)

//____________________________________________________________________________
// _addValidValuesRestrictions

inline void _addValidValuesRestrictions(StringSet<CharString> & restrictions, CommandLineOption const & opt);       	// "core/include/seqan/misc/cmdparser/cmdparser_ctd_support.h"(132)

//____________________________________________________________________________
// _allMandatorySet

inline bool _allMandatorySet(CommandLineParser const & me);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(826)

//____________________________________________________________________________
// _assignOptionValue

template <typename TErrorStream> bool _assignOptionValue(CommandLineParser & me, CommandLineOption & opt, CharString const & val, unsigned argNo, TErrorStream & estream);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(1097)
template <typename TErrorStream> bool _assignOptionValue(CommandLineParser & me, CommandLineOption & opt, CharString const & val, TErrorStream & estream);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(1129)
template <typename TErrorStream> bool _assignOptionValue(CommandLineParser & me, unsigned option_index, CharString const & val, unsigned argNo, TErrorStream & estream);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(1137)
template <typename TErrorStream> inline bool _assignOptionValue(CommandLineParser & me, unsigned option_index, CharString const & val, TErrorStream & estream);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(1147)

//____________________________________________________________________________
// _checkMinMaxValue

template <typename TValue, typename TErrorStream> bool _checkMinMaxValue(CommandLineOption const & opt, CharString const & val, TErrorStream & estream);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(988)

//____________________________________________________________________________
// _checkRestrictions

template <typename TErrorStream> bool _checkRestrictions(CommandLineOption const & opt, CharString const & val, TErrorStream & estream);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(1070)

//____________________________________________________________________________
// _checkValidValues

template <typename TErrorStream> bool _checkValidValues(CommandLineOption const & opt, CharString const & val, TErrorStream & estream);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(1029)

//____________________________________________________________________________
// _convertOptionValue

inline bool _convertOptionValue(CommandLineOption const & opt, bool & dst, CharString const & src);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(1212)
inline bool _convertOptionValue(CommandLineOption const & opt, int & dst, CharString const & src);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(1222)
inline bool _convertOptionValue(CommandLineOption const & opt, unsigned int & dst, CharString const & src);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(1232)
inline bool _convertOptionValue(CommandLineOption const & opt, __int64 & dst, CharString const & src);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(1242)
inline bool _convertOptionValue(CommandLineOption const & opt, __uint64 & dst, CharString const & src);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(1252)
inline bool _convertOptionValue(CommandLineOption const & opt, float & dst, CharString const & src);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(1262)
inline bool _convertOptionValue(CommandLineOption const & opt, double & dst, CharString const & src);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(1272)
template <typename TObject> inline bool _convertOptionValue(CommandLineOption const & opt, TObject & dst, CharString const & src);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(1283)

//____________________________________________________________________________
// _dataHost

template <typename TText, typename TSpec> inline Holder<TText> & _dataHost(StringEnumerator<TText, TSpec> & enumerator);       	// "core/include/seqan/misc/edit_environment.h"(475)
template <typename TText, typename TSpec> inline Holder<TText> const & _dataHost(StringEnumerator<TText, TSpec> const & enumerator);       	// "core/include/seqan/misc/edit_environment.h"(482)

//____________________________________________________________________________
// _getOptionIndex

inline Size<String<CommandLineOption> >::Type _getOptionIndex(CommandLineParser const & me, CharString const & _name);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(412)

//____________________________________________________________________________
// _getOptionValue

inline CharString const & _getOptionValue(CommandLineParser const & me, CommandLineOption const & opt, unsigned argNo);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(1177)
inline CharString const & _getOptionValue(CommandLineParser const & me, CommandLineOption const & opt);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(1189)
inline CharString const & _getOptionValue(CommandLineParser const & me, unsigned option_index, unsigned argNo);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(1195)
inline CharString const & _getOptionValue(CommandLineParser const & me, unsigned option_index);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(1202)

//____________________________________________________________________________
// _getOptionValues

inline String<CharString> const & _getOptionValues(CommandLineParser const &, CommandLineOption const & opt);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(1157)
inline String<CharString> const & _getOptionValues(CommandLineParser const & me, unsigned option_index);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(1166)

//____________________________________________________________________________
// _includeInCTD

inline bool _includeInCTD(CommandLineOption const & opt);       	// "core/include/seqan/misc/cmdparser/cmdparser_ctd_support.h"(161)

//____________________________________________________________________________
// _isDouble

template <typename TString> inline bool _isDouble(TString const s);       	// "core/include/seqan/misc/cmdparser/cmdparser_type_support.h"(47)

//____________________________________________________________________________
// _isInt

template <typename TString> inline bool _isInt(TString const s);       	// "core/include/seqan/misc/cmdparser/cmdparser_type_support.h"(60)

//____________________________________________________________________________
// _join

template <typename TValue> inline CharString _join(StringSet<TValue> const & v, CharString const & delimiter);       	// "core/include/seqan/misc/cmdparser/cmdparser_ctd_support.h"(54)

//____________________________________________________________________________
// _parseAppName

inline CharString _parseAppName(CharString const & candidate);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(840)

//____________________________________________________________________________
// _printStringSet

template <typename TStringSet, typename TStream> inline void _printStringSet(TStringSet const & set, TStream & target);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(491)

//____________________________________________________________________________
// _printTitle

template <typename TStream> inline void _printTitle(CommandLineParser const & me, TStream & target);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(541)

//____________________________________________________________________________
// _printUsage

template <typename TStream> inline void _printUsage(CommandLineParser const & me, TStream & target);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(506)

//____________________________________________________________________________
// _reportInvalidFileType

template <typename TErrorStream> inline void _reportInvalidFileType(CommandLineOption const & opt, CharString const & val, TErrorStream & estream);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(963)

//____________________________________________________________________________
// _reportInvalidOption

template <typename TErrorStream> inline void _reportInvalidOption(CommandLineParser const & me, CharString const & option, TErrorStream & estream);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(901)

//____________________________________________________________________________
// _reportInvalidType

template <typename TErrorStream> inline void _reportInvalidType(CommandLineParser const & me, CommandLineOption const & opt, CharString const & val, TErrorStream & estream);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(859)

//____________________________________________________________________________
// _reportInvalidValue

template <typename TErrorStream> inline void _reportInvalidValue(CommandLineOption const & opt, CharString const & val, TErrorStream & estream);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(935)

//____________________________________________________________________________
// _reportMissingArgument

template <typename TErrorStream> inline void _reportMissingArgument(CommandLineParser const & me, CommandLineOption const & opt, TErrorStream & estream);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(884)

//____________________________________________________________________________
// _reportValueNotInRange

template <typename TErrorStream> inline void _reportValueNotInRange(CommandLineOption const & opt, CharString const & val, TErrorStream & estream);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(916)

//____________________________________________________________________________
// _writeOptName

template <typename TStream> inline void _writeOptName(TStream & target, CommandLineOption const & me);       	// "core/include/seqan/misc/cmdparser/cmdoption.h"(541)

//____________________________________________________________________________
// _xmlEscape

template <typename TSequence> inline TSequence _xmlEscape(TSequence const & original);       	// "core/include/seqan/misc/cmdparser/cmdparser_ctd_support.h"(82)

//____________________________________________________________________________
// addArgumentText

inline CommandLineOption addArgumentText(CommandLineOption const & opt, CharString const & text);       	// "core/include/seqan/misc/cmdparser/cmdoption.h"(236)

//____________________________________________________________________________
// addHelpLine

template <typename TString> inline void addHelpLine(CommandLineParser & me, TString const & line);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(308)

//____________________________________________________________________________
// addLine

template <typename TString> inline void addLine(CommandLineParser & me, TString const & line);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(285)

//____________________________________________________________________________
// addOption

inline void addOption(CommandLineParser & me, CommandLineOption const & opt);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(236)

//____________________________________________________________________________
// addSection

template <typename TString> inline void addSection(CommandLineParser & me, TString const & line);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(331)

//____________________________________________________________________________
// addTitleLine

template <typename TString> inline void addTitleLine(CommandLineParser & me, TString const & line);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(355)

//____________________________________________________________________________
// addUsageLine

inline void addUsageLine(CommandLineParser & me, CharString const & line);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(402)

//____________________________________________________________________________
// addVersionLine

template <typename TString> inline void addVersionLine(CommandLineParser & me, TString const & line);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(378)

//____________________________________________________________________________
// argumentCount

inline Size<String<CharString> >::Type argumentCount(CommandLineParser const & me);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(1536)

//____________________________________________________________________________
// argumentText

inline CharString argumentText(CommandLineOption const & me);       	// "core/include/seqan/misc/cmdparser/cmdoption.h"(503)

//____________________________________________________________________________
// atBegin

template <typename TObject, unsigned DISTANCE> inline void atBegin(Iter<StringEnumerator<TObject, EditEnvironment<HammingDistance, DISTANCE> >, Standard> const & it);       	// "core/include/seqan/misc/edit_environment.h"(643)
template <typename TObject, unsigned DISTANCE> inline bool atBegin(Iter<StringEnumerator<TObject, EditEnvironment<HammingDistance, DISTANCE> >, Standard> & it);       	// "core/include/seqan/misc/edit_environment.h"(651)

//____________________________________________________________________________
// atEnd

template <typename TObject, unsigned DISTANCE> inline bool atEnd(Iter<StringEnumerator<TObject, EditEnvironment<HammingDistance, DISTANCE> >, Standard> const & it);       	// "core/include/seqan/misc/edit_environment.h"(682)
template <typename TObject, unsigned DISTANCE> inline bool atEnd(Iter<StringEnumerator<TObject, EditEnvironment<HammingDistance, DISTANCE> >, Standard> & it);       	// "core/include/seqan/misc/edit_environment.h"(699)
template <typename TObject, unsigned DISTANCE> inline bool atEnd(Iter<StringEnumerator<TObject, EditEnvironment<LevenshteinDistance, DISTANCE> >, Standard> const & it);       	// "core/include/seqan/misc/edit_environment.h"(839)
template <typename TObject, unsigned DISTANCE> inline bool atEnd(Iter<StringEnumerator<TObject, EditEnvironment<LevenshteinDistance, DISTANCE> >, Standard> & it);       	// "core/include/seqan/misc/edit_environment.h"(856)

//____________________________________________________________________________
// average

template <typename TValue> inline typename Result<Accumulator<TValue, Average>, Average>::Type average(Accumulator<TValue, Average> const & acc);       	// "core/include/seqan/misc/misc_accumulators.h"(267)

//____________________________________________________________________________
// begin

template <typename TObject, typename TSpec> inline Iter<StringEnumerator<TObject, TSpec>, Standard> begin(StringEnumerator<TObject, TSpec> & enumerator, Standard);       	// "core/include/seqan/misc/edit_environment.h"(496)
template <typename TObject, typename TSpec> inline Iter<StringEnumerator<TObject, TSpec>, Standard> begin(StringEnumerator<TObject, TSpec> const & enumerator, Standard);       	// "core/include/seqan/misc/edit_environment.h"(503)

//____________________________________________________________________________
// clear

template <typename TValue> inline void clear(Accumulator<TValue, Average> & accumulator);       	// "core/include/seqan/misc/misc_accumulators.h"(230)
template <typename TValue> inline void clear(UnionFind<TValue> & unionFind);       	// "core/include/seqan/misc/misc_union_find.h"(161)

//____________________________________________________________________________
// clearBit

template <typename TWord> inline void clearBit(TWord & word, unsigned index);       	// "core/include/seqan/misc/misc_bit_twiddling.h"(144)

//____________________________________________________________________________
// clearBits

template <typename TWord> inline void clearBits(TWord & word);       	// "core/include/seqan/misc/misc_bit_twiddling.h"(170)

//____________________________________________________________________________
// count

template <typename TValue> inline typename Result<Accumulator<TValue, Average>, Count>::Type count(Accumulator<TValue, Average> const & acc);       	// "core/include/seqan/misc/misc_accumulators.h"(316)

//____________________________________________________________________________
// end

template <typename TObject, typename TSpec> inline Iter<StringEnumerator<TObject, TSpec>, Standard> end(StringEnumerator<TObject, TSpec> & enumerator, Standard);       	// "core/include/seqan/misc/edit_environment.h"(517)
template <typename TObject, typename TSpec> inline Iter<StringEnumerator<TObject, TSpec>, Standard> end(StringEnumerator<TObject, TSpec> const & enumerator, Standard);       	// "core/include/seqan/misc/edit_environment.h"(526)

//____________________________________________________________________________
// findSet

template <typename TValue, typename TQuery> inline TValue findSet(UnionFind<TValue> & unionFind, TQuery const & query);       	// "core/include/seqan/misc/misc_union_find.h"(256)

//____________________________________________________________________________
// getArgumentValue

inline CharString const & getArgumentValue(CommandLineParser const & me, unsigned position);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(1491)

//____________________________________________________________________________
// getArgumentValues

inline String<CharString> const & getArgumentValues(CommandLineParser const & me);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(1516)

//____________________________________________________________________________
// getOption

inline CommandLineOption & getOption(CommandLineParser & me, CharString const & _name);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(432)
inline CommandLineOption const & getOption(CommandLineParser const & me, CharString const & _name);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(439)

//____________________________________________________________________________
// getOptionValue

template <typename TValue> inline bool getOptionValue(CommandLineParser const & me, CharString const & name, unsigned argNo, TValue & val);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(1314)
template <typename TValue> inline bool getOptionValue(CommandLineParser const & me, CharString const & name, TValue & val);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(1323)

//____________________________________________________________________________
// getOptionValueLong

template <typename TValue> inline bool getOptionValueLong(CommandLineParser const & me, CharString const & longName, unsigned argNo, TValue & val);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(1436)
template <typename TValue> inline bool getOptionValueLong(CommandLineParser const & me, CharString const & longName, TValue & val);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(1444)

//____________________________________________________________________________
// getOptionValueShort

template <typename TValue> inline bool getOptionValueShort(CommandLineParser const & me, CharString const & shortName, unsigned argNo, TValue & val);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(1375)
template <typename TValue> inline bool getOptionValueShort(CommandLineParser const & me, CharString const & shortName, TValue & val);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(1383)

//____________________________________________________________________________
// getOptionValues

inline String<CharString> const & getOptionValues(CommandLineParser & me, CharString const & name);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(1345)

//____________________________________________________________________________
// getOptionValuesLong

inline String<CharString> const & getOptionValuesLong(CommandLineParser & me, CharString const & longName);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(1468)

//____________________________________________________________________________
// getOptionValuesShort

inline String<CharString> const & getOptionValuesShort(CommandLineParser & me, CharString const & shortName);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(1407)

//____________________________________________________________________________
// getTerminalSize

inline bool getTerminalSize(unsigned & cols, unsigned & rows);       	// "core/include/seqan/misc/misc_terminal.h"(160)
inline bool getTerminalSize(unsigned & cols, unsigned & rows);       	// "core/include/seqan/misc/misc_terminal.h"(180)

//____________________________________________________________________________
// goBegin

template <typename TObject, unsigned DISTANCE> inline void goBegin(Iter<StringEnumerator<TObject, EditEnvironment<HammingDistance, DISTANCE> >, Standard> & it);       	// "core/include/seqan/misc/edit_environment.h"(590)
template <typename TObject, unsigned DISTANCE> inline void goBegin(Iter<StringEnumerator<TObject, EditEnvironment<LevenshteinDistance, DISTANCE> >, Standard> & it);       	// "core/include/seqan/misc/edit_environment.h"(785)

//____________________________________________________________________________
// goEnd

template <typename TObject, unsigned DISTANCE> inline void goEnd(Iter<StringEnumerator<TObject, EditEnvironment<HammingDistance, DISTANCE> >, Standard> & it);       	// "core/include/seqan/misc/edit_environment.h"(662)
template <typename TObject, unsigned DISTANCE> inline void goEnd(Iter<StringEnumerator<TObject, EditEnvironment<LevenshteinDistance, DISTANCE> >, Standard> & it);       	// "core/include/seqan/misc/edit_environment.h"(818)

//____________________________________________________________________________
// hasOption

inline bool hasOption(CommandLineParser const & me, CharString const & _name);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(214)

//____________________________________________________________________________
// hasOptionLong

inline bool hasOptionLong(CommandLineParser const & me, CharString const & _long);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(170)

//____________________________________________________________________________
// hasOptionShort

inline bool hasOptionShort(CommandLineParser const & me, CharString const & _short);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(192)

//____________________________________________________________________________
// help

template <typename TStream> inline void help(CommandLineParser const & me, TStream & target);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(697)
inline void help(CommandLineParser const & me);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(703)

//____________________________________________________________________________
// isAnsiColorTerminal

inline bool isAnsiColorTerminal();       	// "core/include/seqan/misc/misc_terminal.h"(114)
inline bool isAnsiColorTerminal();       	// "core/include/seqan/misc/misc_terminal.h"(121)

//____________________________________________________________________________
// isBitSet

template <typename TWord> inline bool isBitSet(TWord const & word, unsigned index);       	// "core/include/seqan/misc/misc_bit_twiddling.h"(199)

//____________________________________________________________________________
// isBooleanOption

inline bool isBooleanOption(CommandLineOption const & me);       	// "core/include/seqan/misc/cmdparser/cmdoption.h"(283)

//____________________________________________________________________________
// isDoubleOption

inline bool isDoubleOption(CommandLineOption const & me);       	// "core/include/seqan/misc/cmdparser/cmdoption.h"(305)

//____________________________________________________________________________
// isHiddenOption

inline bool isHiddenOption(CommandLineOption const & me);       	// "core/include/seqan/misc/cmdparser/cmdoption.h"(349)

//____________________________________________________________________________
// isInputFile

inline bool isInputFile(CommandLineOption const & me);       	// "core/include/seqan/misc/cmdparser/cmdoption.h"(437)

//____________________________________________________________________________
// isIntOption

inline bool isIntOption(CommandLineOption const & me);       	// "core/include/seqan/misc/cmdparser/cmdoption.h"(327)

//____________________________________________________________________________
// isLabelOption

inline bool isLabelOption(CommandLineOption const & me);       	// "core/include/seqan/misc/cmdparser/cmdoption.h"(393)

//____________________________________________________________________________
// isOptionList

inline bool isOptionList(CommandLineOption const & me);       	// "core/include/seqan/misc/cmdparser/cmdoption.h"(415)

//____________________________________________________________________________
// isOptionMandatory

inline bool isOptionMandatory(CommandLineOption const & me);       	// "core/include/seqan/misc/cmdparser/cmdoption.h"(371)

//____________________________________________________________________________
// isOutputFile

inline bool isOutputFile(CommandLineOption const & me);       	// "core/include/seqan/misc/cmdparser/cmdoption.h"(459)

//____________________________________________________________________________
// isSet

inline bool isSet(CommandLineParser const & me, CharString const & name);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(775)

//____________________________________________________________________________
// isSetLong

inline bool isSetLong(CommandLineParser & me, CharString const & longName);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(816)

//____________________________________________________________________________
// isSetShort

inline bool isSetShort(CommandLineParser & me, CharString const & shortName);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(796)

//____________________________________________________________________________
// isStringOption

inline bool isStringOption(CommandLineOption const & me);       	// "core/include/seqan/misc/cmdparser/cmdoption.h"(261)

//____________________________________________________________________________
// isTerminal

inline bool isTerminal();       	// "core/include/seqan/misc/misc_terminal.h"(80)
inline bool isTerminal();       	// "core/include/seqan/misc/misc_terminal.h"(91)

//____________________________________________________________________________
// joinSets

template <typename TValue, typename TLeft, typename TRight> inline void joinSets(UnionFind<TValue> & unionFind, TLeft const & left, TRight const & right);       	// "core/include/seqan/misc/misc_union_find.h"(301)

//____________________________________________________________________________
// length

template <typename TObject, unsigned DISTANCE> inline typename Size<StringEnumerator<TObject, EditEnvironment<HammingDistance, DISTANCE> > >::Type length(StringEnumerator<TObject, EditEnvironment<HammingDistance, DISTANCE> > const & me);       	// "core/include/seqan/misc/edit_environment.h"(542)
template <typename TObject, unsigned DISTANCE> inline typename Size<StringEnumerator<TObject, EditEnvironment<LevenshteinDistance, DISTANCE> > >::Type length(StringEnumerator<TObject, EditEnvironment<LevenshteinDistance, DISTANCE> > const & me);       	// "core/include/seqan/misc/edit_environment.h"(977)
inline size_t length(LongWord<NativeWidth> const &);       	// "core/include/seqan/misc/misc_long_word.h"(144)
template <unsigned LENGTH> size_t length(LongWord<StaticWidth<LENGTH> > const &);       	// "core/include/seqan/misc/misc_long_word.h"(276)
size_t length(LongWord<DynamicWidth> const & a);       	// "core/include/seqan/misc/misc_long_word.h"(622)
template <typename TValue> inline typename Size<UnionFind<TValue> >::Type length(UnionFind<TValue> const & unionFind);       	// "core/include/seqan/misc/misc_union_find.h"(176)

//____________________________________________________________________________
// memset

template <unsigned SIZE> finline void memset(void* ptr, unsigned char c);       	// "core/include/seqan/misc/misc_memset.h"(145)
template <unsigned SIZE, unsigned char c> finline void memset(void* ptr);       	// "core/include/seqan/misc/misc_memset.h"(208)

//____________________________________________________________________________
// operator!=

template <typename TObject, unsigned DISTANCE> inline bool operator!=( Iter<StringEnumerator<TObject, EditEnvironment<HammingDistance, DISTANCE> >, Standard> const & a, Iter<StringEnumerator<TObject, EditEnvironment<HammingDistance, DISTANCE> >, Standard> const & b);       	// "core/include/seqan/misc/edit_environment.h"(1072)
template <typename TObject, unsigned DISTANCE> inline bool operator!=( Iter<StringEnumerator<TObject, EditEnvironment<LevenshteinDistance, DISTANCE> >, Standard> const & a, Iter<StringEnumerator<TObject, EditEnvironment<LevenshteinDistance, DISTANCE> >, Standard> const & b);       	// "core/include/seqan/misc/edit_environment.h"(1130)
template <unsigned LENGTH> bool operator!=(LongWord<StaticWidth<LENGTH> > const & a, LongWord<StaticWidth<LENGTH> > const & b);       	// "core/include/seqan/misc/misc_long_word.h"(297)
bool operator!=(LongWord<DynamicWidth> const & a, LongWord<DynamicWidth> const & b);       	// "core/include/seqan/misc/misc_long_word.h"(641)

//____________________________________________________________________________
// operator&

template <unsigned LENGTH> LongWord<StaticWidth<LENGTH> > operator&(LongWord<StaticWidth<LENGTH> > const & a, LongWord<StaticWidth<LENGTH> > const & b);       	// "core/include/seqan/misc/misc_long_word.h"(390)
LongWord<DynamicWidth> operator&(LongWord<DynamicWidth> const & a, LongWord<DynamicWidth> const & b);       	// "core/include/seqan/misc/misc_long_word.h"(711)

//____________________________________________________________________________
// operator&=

inline LongWord<NativeWidth> & operator&=(LongWord<NativeWidth> & x, LongWord<NativeWidth> const & mask);       	// "core/include/seqan/misc/misc_long_word.h"(164)
template <unsigned LENGTH> LongWord<StaticWidth<LENGTH> > & operator&=(LongWord<StaticWidth<LENGTH> > & a, LongWord<StaticWidth<LENGTH> > const & b);       	// "core/include/seqan/misc/misc_long_word.h"(402)
LongWord<DynamicWidth> & operator&=(LongWord<DynamicWidth> & a, LongWord<DynamicWidth> const & b);       	// "core/include/seqan/misc/misc_long_word.h"(701)

//____________________________________________________________________________
// operator*

template <typename TObject, typename TSpec> inline TObject const & operator*(Iter<StringEnumerator<TObject, TSpec>, Standard> & it);       	// "core/include/seqan/misc/edit_environment.h"(572)
template <typename TObject, typename TSpec> inline TObject const & operator*(Iter<StringEnumerator<TObject, TSpec>, Standard> const & it);       	// "core/include/seqan/misc/edit_environment.h"(579)

//____________________________________________________________________________
// operator++

template <typename TObject, unsigned DISTANCE> inline Iter<StringEnumerator<TObject, EditEnvironment<HammingDistance, DISTANCE> >, Standard> & operator++(Iter<StringEnumerator<TObject, EditEnvironment<HammingDistance, DISTANCE> >, Standard> & it);       	// "core/include/seqan/misc/edit_environment.h"(710)
template <typename TObject, unsigned DISTANCE> inline Iter<StringEnumerator<TObject, EditEnvironment<LevenshteinDistance, DISTANCE> >, Standard> & operator++(Iter<StringEnumerator<TObject, EditEnvironment<LevenshteinDistance, DISTANCE> >, Standard> & it);       	// "core/include/seqan/misc/edit_environment.h"(867)

//____________________________________________________________________________
// operator<

template <unsigned LENGTH> bool operator<(LongWord<StaticWidth<LENGTH> > const & a, LongWord<StaticWidth<LENGTH> > const & b);       	// "core/include/seqan/misc/misc_long_word.h"(338)
bool operator<(LongWord<DynamicWidth> const & a, LongWord<DynamicWidth> const & b);       	// "core/include/seqan/misc/misc_long_word.h"(671)

//____________________________________________________________________________
// operator<<

template <unsigned LENGTH> LongWord<StaticWidth<LENGTH> > operator<<(LongWord<StaticWidth<LENGTH> > const & a, unsigned shift);       	// "core/include/seqan/misc/misc_long_word.h"(478)
LongWord<DynamicWidth> operator<<(LongWord<DynamicWidth> const & a, unsigned shift);       	// "core/include/seqan/misc/misc_long_word.h"(803)
template <typename TStream> inline TStream & operator<<(TStream & target, CommandLineOption const & source);       	// "core/include/seqan/misc/cmdparser/cmdoption.h"(587)

//____________________________________________________________________________
// operator<<=

inline LongWord<NativeWidth> & operator<<=(LongWord<NativeWidth> & x, unsigned const shift);       	// "core/include/seqan/misc/misc_long_word.h"(157)
template <unsigned LENGTH> LongWord<StaticWidth<LENGTH> > & operator<<=(LongWord<StaticWidth<LENGTH> > & a, unsigned shift);       	// "core/include/seqan/misc/misc_long_word.h"(487)
LongWord<DynamicWidth> & operator<<=(LongWord<DynamicWidth> & a, unsigned shift);       	// "core/include/seqan/misc/misc_long_word.h"(773)

//____________________________________________________________________________
// operator<=

template <unsigned LENGTH> bool operator<=(LongWord<StaticWidth<LENGTH> > const & a, LongWord<StaticWidth<LENGTH> > const & b);       	// "core/include/seqan/misc/misc_long_word.h"(312)
bool operator<=(LongWord<DynamicWidth> const & a, LongWord<DynamicWidth> const & b);       	// "core/include/seqan/misc/misc_long_word.h"(647)

//____________________________________________________________________________
// operator==

template <typename TObject, unsigned DISTANCE> inline bool operator==( Iter<StringEnumerator<TObject, EditEnvironment<HammingDistance, DISTANCE> >, Standard> const & a, Iter<StringEnumerator<TObject, EditEnvironment<HammingDistance, DISTANCE> >, Standard> const & b);       	// "core/include/seqan/misc/edit_environment.h"(1044)
template <typename TObject, unsigned DISTANCE> inline bool operator==( Iter<StringEnumerator<TObject, EditEnvironment<LevenshteinDistance, DISTANCE> >, Standard> const & a, Iter<StringEnumerator<TObject, EditEnvironment<LevenshteinDistance, DISTANCE> >, Standard> const & b);       	// "core/include/seqan/misc/edit_environment.h"(1100)
template <unsigned LENGTH> bool operator==(LongWord<StaticWidth<LENGTH> > const & a, LongWord<StaticWidth<LENGTH> > const & b);       	// "core/include/seqan/misc/misc_long_word.h"(283)
bool operator==(LongWord<DynamicWidth> const & a, LongWord<DynamicWidth> const & b);       	// "core/include/seqan/misc/misc_long_word.h"(628)

//____________________________________________________________________________
// operator>

template <unsigned LENGTH> bool operator>(LongWord<StaticWidth<LENGTH> > const & a, LongWord<StaticWidth<LENGTH> > const & b);       	// "core/include/seqan/misc/misc_long_word.h"(352)
bool operator>(LongWord<DynamicWidth> const & a, LongWord<DynamicWidth> const & b);       	// "core/include/seqan/misc/misc_long_word.h"(677)

//____________________________________________________________________________
// operator>=

template <unsigned LENGTH> bool operator>=(LongWord<StaticWidth<LENGTH> > const & a, LongWord<StaticWidth<LENGTH> > const & b);       	// "core/include/seqan/misc/misc_long_word.h"(325)
bool operator>=(LongWord<DynamicWidth> const & a, LongWord<DynamicWidth> const & b);       	// "core/include/seqan/misc/misc_long_word.h"(659)

//____________________________________________________________________________
// operator>>

template <unsigned LENGTH> LongWord<StaticWidth<LENGTH> > operator>>(LongWord<StaticWidth<LENGTH> > const & a, unsigned shift);       	// "core/include/seqan/misc/misc_long_word.h"(438)
LongWord<DynamicWidth> operator>>(LongWord<DynamicWidth> const & a, unsigned shift);       	// "core/include/seqan/misc/misc_long_word.h"(766)

//____________________________________________________________________________
// operator>>=

inline LongWord<NativeWidth> & operator>>=(LongWord<NativeWidth> & x, unsigned const shift);       	// "core/include/seqan/misc/misc_long_word.h"(150)
template <unsigned LENGTH> LongWord<StaticWidth<LENGTH> > & operator>>=(LongWord<StaticWidth<LENGTH> > & a, unsigned shift);       	// "core/include/seqan/misc/misc_long_word.h"(447)
LongWord<DynamicWidth> & operator>>=(LongWord<DynamicWidth> & a, unsigned shift);       	// "core/include/seqan/misc/misc_long_word.h"(737)

//____________________________________________________________________________
// operator^

template <unsigned LENGTH> LongWord<StaticWidth<LENGTH> > operator^(LongWord<StaticWidth<LENGTH> > const & a, LongWord<StaticWidth<LENGTH> > const & b);       	// "core/include/seqan/misc/misc_long_word.h"(414)
LongWord<DynamicWidth> operator^(LongWord<DynamicWidth> const & a, LongWord<DynamicWidth> const & b);       	// "core/include/seqan/misc/misc_long_word.h"(729)

//____________________________________________________________________________
// operator^=

inline LongWord<NativeWidth> & operator^=(LongWord<NativeWidth> & x, LongWord<NativeWidth> const & mask);       	// "core/include/seqan/misc/misc_long_word.h"(178)
template <unsigned LENGTH> LongWord<StaticWidth<LENGTH> > & operator^=(LongWord<StaticWidth<LENGTH> > & a, LongWord<StaticWidth<LENGTH> > const & b);       	// "core/include/seqan/misc/misc_long_word.h"(426)
LongWord<DynamicWidth> & operator^=(LongWord<DynamicWidth> & a, LongWord<DynamicWidth> const & b);       	// "core/include/seqan/misc/misc_long_word.h"(719)

//____________________________________________________________________________
// operator|

template <unsigned LENGTH> LongWord<StaticWidth<LENGTH> > operator|(LongWord<StaticWidth<LENGTH> > const & a, LongWord<StaticWidth<LENGTH> > const & b);       	// "core/include/seqan/misc/misc_long_word.h"(366)
LongWord<DynamicWidth> operator|(LongWord<DynamicWidth> const & a, LongWord<DynamicWidth> const & b);       	// "core/include/seqan/misc/misc_long_word.h"(693)

//____________________________________________________________________________
// operator|=

inline LongWord<NativeWidth> & operator|=(LongWord<NativeWidth> & x, LongWord<NativeWidth> const & mask);       	// "core/include/seqan/misc/misc_long_word.h"(171)
template <unsigned LENGTH> LongWord<StaticWidth<LENGTH> > & operator|=(LongWord<StaticWidth<LENGTH> > & a, LongWord<StaticWidth<LENGTH> > const & b);       	// "core/include/seqan/misc/misc_long_word.h"(378)
LongWord<DynamicWidth> & operator|=(LongWord<DynamicWidth> & a, LongWord<DynamicWidth> const & b);       	// "core/include/seqan/misc/misc_long_word.h"(683)

//____________________________________________________________________________
// parse

template <typename TErrorStream> bool parse(CommandLineParser & me, int argc, const char * argv[], TErrorStream & estream);       	// "core/include/seqan/misc/cmdparser/cmdparser_parse.h"(65)
inline bool parse(CommandLineParser & me, int argc, const char * argv[]);       	// "core/include/seqan/misc/cmdparser/cmdparser_parse.h"(221)

//____________________________________________________________________________
// printHelp

template <typename TStream> inline void printHelp(CommandLineParser const & me, TStream & target);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(617)

//____________________________________________________________________________
// printShortHelp

template <typename TStream> inline void printShortHelp(CommandLineParser const & me, TStream & target);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(563)

//____________________________________________________________________________
// printVersion

template <typename TStream> inline void printVersion(CommandLineParser const & me, TStream & target);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(726)

//____________________________________________________________________________
// push

template <typename TValue, typename TValue2> inline void push(Accumulator<TValue, Average> & acc, TValue2 value);       	// "core/include/seqan/misc/misc_accumulators.h"(242)

//____________________________________________________________________________
// requiredArguments

inline void requiredArguments(CommandLineParser & me, unsigned count);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(480)

//____________________________________________________________________________
// reserve

template <typename TValue, typename TSize, typename TTag> inline typename Size<UnionFind<TValue> >::Type reserve(UnionFind<TValue> & unionFind, TSize const & newSize, TTag const & tag);       	// "core/include/seqan/misc/misc_union_find.h"(193)

//____________________________________________________________________________
// reset

inline LongWord<NativeWidth> & reset(LongWord<NativeWidth> & x);       	// "core/include/seqan/misc/misc_long_word.h"(137)
template <unsigned LENGTH> inline LongWord<StaticWidth<LENGTH> > & reset(LongWord<StaticWidth<LENGTH> > & a);       	// "core/include/seqan/misc/misc_long_word.h"(266)
inline LongWord<DynamicWidth> & reset(LongWord<DynamicWidth> & a);       	// "core/include/seqan/misc/misc_long_word.h"(614)

//____________________________________________________________________________
// resize

template <typename TValue, typename TSize, typename TTag> inline typename Size<UnionFind<TValue> >::Type resize(UnionFind<TValue> & unionFind, TSize const & newSize, TTag const & tag);       	// "core/include/seqan/misc/misc_union_find.h"(211)

//____________________________________________________________________________
// resizeVertexMap

template <typename TSpec, typename TValue> inline typename Size<UnionFind<TValue> >::Type resizeVertexMap(Graph<TSpec> const & g, UnionFind<TValue> & unionFind);       	// "core/include/seqan/misc/misc_union_find.h"(228)

//____________________________________________________________________________
// setBit

template <typename TWord> inline void setBit(TWord & word, unsigned index);       	// "core/include/seqan/misc/misc_bit_twiddling.h"(116)

//____________________________________________________________________________
// setBitTo

template <typename TWord> inline void setBitTo(TWord & word, unsigned index, bool value);       	// "core/include/seqan/misc/misc_bit_twiddling.h"(87)

//____________________________________________________________________________
// setMaxValue

inline void setMaxValue(CommandLineOption & me, const CharString _maxValue);       	// "core/include/seqan/misc/cmdparser/cmdoption.h"(633)
inline void setMaxValue(CommandLineParser & me, CharString const & name, CharString const & _maxValue);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(1583)

//____________________________________________________________________________
// setMinValue

inline void setMinValue(CommandLineOption & me, const CharString _minValue);       	// "core/include/seqan/misc/cmdparser/cmdoption.h"(610)
inline void setMinValue(CommandLineParser & me, CharString const & name, CharString const & _minValue);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(1558)

//____________________________________________________________________________
// setOptionType

inline void setOptionType(CommandLineOption & me, const int _newOptionType);       	// "core/include/seqan/misc/cmdparser/cmdoption.h"(481)

//____________________________________________________________________________
// setRequiredArguments

inline void setRequiredArguments(CommandLineParser & me, unsigned count);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(461)

//____________________________________________________________________________
// setValidValues

inline void setValidValues(CommandLineOption & me, StringSet<CharString> const & _values);       	// "core/include/seqan/misc/cmdparser/cmdoption.h"(656)
inline void setValidValues(CommandLineParser & me, CharString const & name, StringSet<CharString> const & _values);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(1608)
inline void setValidValues(CommandLineParser & me, CharString const & name, CharString const & _values);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(1616)

//____________________________________________________________________________
// shortHelp

template <typename TStream> inline void shortHelp(CommandLineParser const & me, TStream & target);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(587)
template <typename TStream> inline void shortHelp(CommandLineParser const & me);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(594)

//____________________________________________________________________________
// sum

template <typename TValue> inline typename Result<Accumulator<TValue, Average>, Sum>::Type sum(Accumulator<TValue, Average> const & acc);       	// "core/include/seqan/misc/misc_accumulators.h"(293)

//____________________________________________________________________________
// version

template <typename TStream> inline void version(CommandLineParser const & me, TStream & target);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(747)
inline void version(CommandLineParser const & me);       	// "core/include/seqan/misc/cmdparser/cmdparser.h"(753)

//____________________________________________________________________________
// write

template <typename TStream> inline void write(TStream & target, CommandLineOption const & me);       	// "core/include/seqan/misc/cmdparser/cmdoption.h"(571)

//____________________________________________________________________________
// writeCTD

inline void writeCTD(CommandLineParser const & me);       	// "core/include/seqan/misc/cmdparser/cmdparser_ctd_support.h"(181)

} //namespace seqan
//////////////////////////////////////////////////////////////////////////////

namespace std {

//____________________________________________________________________________
// operator<<

template <typename TStream, unsigned LENGTH> TStream & operator<<(TStream & stream, seqan::LongWord<seqan::StaticWidth<LENGTH> > const & a);       	// "core/include/seqan/misc/misc_long_word.h"(816)
template <typename TStream> TStream & operator<<(TStream & stream, seqan::LongWord<seqan::DynamicWidth> const & a);       	// "core/include/seqan/misc/misc_long_word.h"(833)

} //namespace std

#endif

