// ==========================================================================
//                 SeqAn - The Library for Sequence Analysis
// ==========================================================================
// Copyright (c) 2006-2010, Knut Reinert, FU Berlin
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
//     * Redistributions of source code must retain the above copyright
//       notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above copyright
//       notice, this list of conditions and the following disclaimer in the
//       documentation and/or other materials provided with the distribution.
//     * Neither the name of Knut Reinert or the FU Berlin nor the names of
//       its contributors may be used to endorse or promote products derived
//       from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL KNUT REINERT OR THE FU BERLIN BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
// LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
// OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
// DAMAGE.
//
// ==========================================================================


#ifndef SEQAN_HEADER_STORE_GENERATED_FORWARDS_H 
#define SEQAN_HEADER_STORE_GENERATED_FORWARDS_H 

//////////////////////////////////////////////////////////////////////////////
// NOTE: This file is automatically generated by build_forwards.py
//       Do not edit this file manually!
//////////////////////////////////////////////////////////////////////////////


//////////////////////////////////////////////////////////////////////////////
// CLASSES
//////////////////////////////////////////////////////////////////////////////

namespace SEQAN_NAMESPACE_MAIN {

//____________________________________________________________________________
// AlignIntervalsStoreElement

template <typename TInterval , typename TSpec > struct AlignIntervalsStoreElement;       	// "core/include/seqan/store/store_align_intervals.h"(75)

//____________________________________________________________________________
// AlignQualityStoreElement

template <typename TScore, typename TSpec > struct AlignQualityStoreElement;       	// "core/include/seqan/store/store_align.h"(215)

//____________________________________________________________________________
// AlignedMateLess_

template <typename TFragStore> struct AlignedMateLess_;       	// "core/include/seqan/store/store_io_sam.h"(736)

//____________________________________________________________________________
// AlignedReadLayout

struct AlignedReadLayout;       	// "core/include/seqan/store/store_all.h"(1453)

//____________________________________________________________________________
// AlignedReadStoreElement

template <typename TPos_, typename TGapAnchor_, typename TSpec_ > struct AlignedReadStoreElement;       	// "core/include/seqan/store/store_align.h"(120)

//____________________________________________________________________________
// AnnotationStoreElement

template <typename TPos_, typename TSpec > struct AnnotationStoreElement;       	// "core/include/seqan/store/store_annotation.h"(47)

//____________________________________________________________________________
// AnnotationTree

template <typename TSpec > struct AnnotationTree;       	// "core/include/seqan/store/store_annotation.h"(87)

//____________________________________________________________________________
// CigarElement

template <typename TOperation_ , typename TCount_ > struct CigarElement;       	// "core/include/seqan/store/store_io_sam.h"(100)

//____________________________________________________________________________
// ContigFile

template <typename TSpec_ > struct ContigFile;       	// "core/include/seqan/store/store_contig.h"(178)

//____________________________________________________________________________
// ContigStoreElement

template <typename TContigSeq_, typename TGapAnchor_, typename TSpec_ > struct ContigStoreElement;       	// "core/include/seqan/store/store_contig.h"(110)

//____________________________________________________________________________
// FragmentStore

template <typename TSpec , typename TConfig > class FragmentStore;       	// "core/include/seqan/store/store_all.h"(423)

//____________________________________________________________________________
// FragmentStoreConfig

template <typename TSpec > struct FragmentStoreConfig;       	// "core/include/seqan/store/store_all.h"(264)

//____________________________________________________________________________
// FromBam_

struct FromBam_;       	// "core/include/seqan/store/store_io_sam.h"(61)

//____________________________________________________________________________
// IOContextGff_

template <typename TFragmentStore, typename TSpec > struct IOContextGff_;       	// "core/include/seqan/store/store_io_gff.h"(157)

//____________________________________________________________________________
// IOContextUcsc_

template <typename TFragmentStore, typename TSpec > struct IOContextUcsc_;       	// "core/include/seqan/store/store_io_ucsc.h"(107)

//____________________________________________________________________________
// Interval

template <typename TValue > struct Interval;       	// "core/include/seqan/store/store_align_intervals.h"(47)

//____________________________________________________________________________
// LibraryStoreElement

template <typename TMean , typename TStd , typename TSpec > struct LibraryStoreElement;       	// "core/include/seqan/store/store_library.h"(77)

//____________________________________________________________________________
// MatchMateInfoLess_

struct MatchMateInfoLess_;       	// "core/include/seqan/store/store_io_sam.h"(773)

//____________________________________________________________________________
// MatchMateInfo_

template <typename TPos, typename TId> struct MatchMateInfo_;       	// "core/include/seqan/store/store_io_sam.h"(725)

//____________________________________________________________________________
// MatePairStoreElement

template <typename TSpec > struct MatePairStoreElement;       	// "core/include/seqan/store/store_matepair.h"(80)

//____________________________________________________________________________
// NameStoreCache

template <typename TNameStore, typename TName > struct NameStoreCache;       	// "core/include/seqan/store/store_all.h"(103)

//____________________________________________________________________________
// NameStoreLess

template <typename TNameStore, typename TName> struct NameStoreLess;       	// "core/include/seqan/store/store_all.h"(49)

//____________________________________________________________________________
// ReadStoreElement

template <typename TSpec > struct ReadStoreElement;       	// "core/include/seqan/store/store_read.h"(74)

//____________________________________________________________________________
// Sam_

struct Sam_;       	// "core/include/seqan/store/store_io_sam.h"(52)

//____________________________________________________________________________
// SortBeginPos_

struct SortBeginPos_;       	// "core/include/seqan/store/store_align.h"(277)

//____________________________________________________________________________
// SortContigId_

struct SortContigId_;       	// "core/include/seqan/store/store_align.h"(271)

//____________________________________________________________________________
// SortEndPos_

struct SortEndPos_;       	// "core/include/seqan/store/store_align.h"(280)

//____________________________________________________________________________
// SortId_

struct SortId_;       	// "core/include/seqan/store/store_align.h"(274)

//____________________________________________________________________________
// SortPairMatchId_

struct SortPairMatchId_;       	// "core/include/seqan/store/store_align.h"(283)

//____________________________________________________________________________
// SortReadId_

struct SortReadId_;       	// "core/include/seqan/store/store_align.h"(286)

//____________________________________________________________________________
// TagAmos_

struct TagAmos_;       	// "core/include/seqan/store/store_io.h"(68)

//____________________________________________________________________________
// TagGff_

struct TagGff_;       	// "core/include/seqan/store/store_io_gff.h"(46)

//____________________________________________________________________________
// TagGtf_

struct TagGtf_;       	// "core/include/seqan/store/store_io_gff.h"(54)

//____________________________________________________________________________
// UcscKnownGene_

struct UcscKnownGene_;       	// "core/include/seqan/store/store_io_ucsc.h"(60)

//____________________________________________________________________________
// UcscKnownIsoforms_

struct UcscKnownIsoforms_;       	// "core/include/seqan/store/store_io_ucsc.h"(68)

//____________________________________________________________________________
// Ucsc_

template <typename TSpec> struct Ucsc_;       	// "core/include/seqan/store/store_io_ucsc.h"(52)

//____________________________________________________________________________
// _LessAlignedRead

template <typename TAlignedRead, typename TTag> struct _LessAlignedRead;       	// "core/include/seqan/store/store_align.h"(311)

} //namespace SEQAN_NAMESPACE_MAIN
//////////////////////////////////////////////////////////////////////////////

namespace seqan {

//____________________________________________________________________________
// Bam_

struct Bam_;       	// "core/include/seqan/store/store_io_bam.h"(54)

} //namespace seqan


//////////////////////////////////////////////////////////////////////////////
// TYPEDEFS
//////////////////////////////////////////////////////////////////////////////

namespace SEQAN_NAMESPACE_MAIN {

//____________________________________________________________________________
// Amos

typedef Tag<TagAmos_> const Amos;       	// "core/include/seqan/store/store_io.h"(69)

//____________________________________________________________________________
// FromBam

typedef Tag<FromBam_> FromBam;       	// "core/include/seqan/store/store_io_sam.h"(62)

//____________________________________________________________________________
// Gff

typedef Tag<TagGff_> const Gff;       	// "core/include/seqan/store/store_io_gff.h"(47)

//____________________________________________________________________________
// Gtf

typedef Tag<TagGtf_> const Gtf;       	// "core/include/seqan/store/store_io_gff.h"(55)

//____________________________________________________________________________
// Sam

typedef Tag<Sam_> const Sam;       	// "core/include/seqan/store/store_io_sam.h"(53)

//____________________________________________________________________________
// SortBeginPos

typedef Tag<SortBeginPos_> const SortBeginPos;       	// "core/include/seqan/store/store_align.h"(278)

//____________________________________________________________________________
// SortContigId

typedef Tag<SortContigId_> const SortContigId;       	// "core/include/seqan/store/store_align.h"(272)

//____________________________________________________________________________
// SortEndPos

typedef Tag<SortEndPos_> const SortEndPos;       	// "core/include/seqan/store/store_align.h"(281)

//____________________________________________________________________________
// SortId

typedef Tag<SortId_> const SortId;       	// "core/include/seqan/store/store_align.h"(275)

//____________________________________________________________________________
// SortPairMatchId

typedef Tag<SortPairMatchId_> const SortPairMatchId;       	// "core/include/seqan/store/store_align.h"(284)

//____________________________________________________________________________
// SortReadId

typedef Tag<SortReadId_> const SortReadId;       	// "core/include/seqan/store/store_align.h"(287)

//____________________________________________________________________________
// Ucsc

typedef Tag<Ucsc_<UcscKnownGene_> > const Ucsc;       	// "core/include/seqan/store/store_io_ucsc.h"(61)

//____________________________________________________________________________
// UcscIsoforms

typedef Tag<Ucsc_<UcscKnownIsoforms_> > const UcscIsoforms;       	// "core/include/seqan/store/store_io_ucsc.h"(69)

} //namespace SEQAN_NAMESPACE_MAIN
//////////////////////////////////////////////////////////////////////////////

namespace seqan {

//____________________________________________________________________________
// Bam

typedef Tag<Bam_> Bam;       	// "core/include/seqan/store/store_io_bam.h"(55)

} //namespace seqan


//////////////////////////////////////////////////////////////////////////////
// FUNCTIONS
//////////////////////////////////////////////////////////////////////////////

namespace SEQAN_NAMESPACE_MAIN {

//____________________________________________________________________________
// _adjustParent

template <typename TAnnotation> inline void _adjustParent ( TAnnotation &parent, TAnnotation const &child);       	// "core/include/seqan/store/store_io_gff.h"(326)

//____________________________________________________________________________
// _compareAlignedReadAndMateInfo

template <typename TAlignedRead, typename TMInfo, typename TFragStore> inline int _compareAlignedReadAndMateInfo(TAlignedRead const &a, TMInfo const &b, TFragStore const &fragStore);       	// "core/include/seqan/store/store_io_sam.h"(790)

//____________________________________________________________________________
// _cyclicListFrontInsert

template <typename TAnnotationStore, typename TId> inline TId _cyclicListFrontInsert(TAnnotationStore & annotationStore, TId newId, TId lastChildId);       	// "core/include/seqan/store/store_annotation.h"(470)

//____________________________________________________________________________
// _cyclicListRemove

template <typename TAnnotationStore, typename TId> inline TId _cyclicListRemove(TAnnotationStore & annotationStore, TId _id, TId lastChildId);       	// "core/include/seqan/store/store_annotation.h"(521)

//____________________________________________________________________________
// _cyclicListSearchPrev

template <typename TAnnotationStore, typename TId> inline TId _cyclicListSearchPrev(TAnnotationStore & annotationStore, TId _id, TId lastChildId);       	// "core/include/seqan/store/store_annotation.h"(498)

//____________________________________________________________________________
// _generatePairMatchIds

template <typename TSpec, typename TConfig, typename TMatchMateInfos> inline void _generatePairMatchIds ( FragmentStore<TSpec, TConfig> & fragStore, TMatchMateInfos & matchMateInfos);       	// "core/include/seqan/store/store_io_sam.h"(819)

//____________________________________________________________________________
// _getClippedLength

template <typename TCigarString, typename TNum> inline void _getClippedLength(TCigarString const & cigar, TNum & sum);       	// "core/include/seqan/store/store_io_sam.h"(445)

//____________________________________________________________________________
// _getLengthInRef

template <typename TCigarString, typename TNum> inline void _getLengthInRef(TCigarString const & cigar, TNum & sum);       	// "core/include/seqan/store/store_io_sam.h"(459)

//____________________________________________________________________________
// _parseIsDna

template <typename TChar> inline bool _parseIsDna(TChar const & c);       	// "core/include/seqan/store/store_io_sam.h"(591)

//____________________________________________________________________________
// _parseIsPhredQual

template <typename TChar> inline bool _parseIsPhredQual(TChar c);       	// "core/include/seqan/store/store_io_sam.h"(623)

//____________________________________________________________________________
// _parseReadCharsUntilEndOfLine

template <typename TFile, typename TChar> inline void _parseReadCharsUntilEndOfLine(TFile & file, String<char> & str, TChar& c);       	// "core/include/seqan/store/store_io_sam.h"(675)

//____________________________________________________________________________
// _parseReadCigar

template <typename TFile, typename TCigarString, typename TChar> inline void _parseReadCigar(TFile & file, TCigarString & cigar, TChar & c);       	// "core/include/seqan/store/store_io_sam.h"(540)

//____________________________________________________________________________
// _parseReadDnaSeq

template <typename TFile, typename TString, typename TChar> inline void _parseReadDnaSeq(TFile & file, TString & str, TChar & c);       	// "core/include/seqan/store/store_io_sam.h"(603)

//____________________________________________________________________________
// _parseReadGffIdentifier

template <typename TFile, typename TString, typename TChar> inline void _parseReadGffIdentifier(TFile & file, TString & str, TChar& c);       	// "core/include/seqan/store/store_io_gff.h"(63)

//____________________________________________________________________________
// _parseReadGffKeyValue

template <typename TFile, typename TKeyString, typename TValueString, typename TChar> inline bool _parseReadGffKeyValue(TFile & file, TKeyString & key, TValueString & value, TChar& c);       	// "core/include/seqan/store/store_io_gff.h"(96)

//____________________________________________________________________________
// _parseReadSamIdentifier

template <typename TFile, typename TString, typename TChar> inline void _parseReadSamIdentifier(TFile & file, TString & str, TChar& c);       	// "core/include/seqan/store/store_io_sam.h"(573)

//____________________________________________________________________________
// _parseReadSeqQual

template <typename TFile, typename TQualString, typename TChar> inline void _parseReadSeqQual(TFile & file, TQualString & str, TChar & c);       	// "core/include/seqan/store/store_io_sam.h"(635)

//____________________________________________________________________________
// _parseReadUcscIdentifier

template <typename TFile, typename TString, typename TChar> inline void _parseReadUcscIdentifier(TFile & file, TString & str, TChar& c);       	// "core/include/seqan/store/store_io_ucsc.h"(77)

//____________________________________________________________________________
// _parseSkipEntryUntilWhitespace

template <typename TFile, typename TChar> inline bool _parseSkipEntryUntilWhitespace(TFile& file, TChar& c);       	// "core/include/seqan/store/store_io_gff.h"(82)

//____________________________________________________________________________
// _parseSkipWhiteComma

template <typename TFile, typename TChar> inline void _parseSkipWhiteComma(TFile& file, TChar& c);       	// "core/include/seqan/store/store_io_ucsc.h"(92)

//____________________________________________________________________________
// _printContig

template <typename TStream, typename TFormatTag, typename TContigGaps, typename TContigName> inline void _printContig( TStream &stream, Tag<TFormatTag> const &format, AlignedReadLayout &, TContigGaps &contigGaps, TContigName const &);       	// "core/include/seqan/store/store_all.h"(1550)

//____________________________________________________________________________
// _printRead

template <typename TStream, typename TFormatTag, typename TContigGaps, typename TReadGaps, typename TAlignedRead, typename TLine> inline void _printRead( TStream &stream, Tag<TFormatTag> const &format, AlignedReadLayout &, TContigGaps &, TReadGaps &readGaps, TAlignedRead &, TLine);       	// "core/include/seqan/store/store_all.h"(1539)

//____________________________________________________________________________
// _readAlignments

template <typename TFile, typename TSpec, typename TConfig, typename TContigAnchorGaps, typename TMatchMateInfos, typename TChar> inline void _readAlignments ( TFile & file, FragmentStore<TSpec, TConfig> & fragStore, TContigAnchorGaps & contigAnchorGaps, TMatchMateInfos & matchMateInfos, TChar & c, Sam);       	// "core/include/seqan/store/store_io_sam.h"(939)

//____________________________________________________________________________
// _readHeader

template <typename TFile, typename TSpec, typename TConfig, typename TChar> inline void _readHeader ( TFile & file, FragmentStore<TSpec, TConfig> &, TChar & c, Sam);       	// "core/include/seqan/store/store_io_sam.h"(918)

//____________________________________________________________________________
// _readOneAlignment

template <typename TFile, typename TSpec, typename TConfig, typename TContigAnchorGaps, typename TMatchMateInfos, typename TChar, typename TContextSAM> inline void _readOneAlignment ( TFile & file, FragmentStore<TSpec, TConfig> & fragStore, TContigAnchorGaps & contigAnchorGaps, TMatchMateInfos & matchMateInfos, TChar & c, Sam, TContextSAM & contextSAM);       	// "core/include/seqan/store/store_io_sam.h"(996)

//____________________________________________________________________________
// _readOneAnnotation

template <typename TFile, typename TChar, typename TFragmentStore, typename TSpec> inline bool _readOneAnnotation ( TFile & file, TChar & c, IOContextGff_<TFragmentStore, TSpec> & ctx);       	// "core/include/seqan/store/store_io_gff.h"(214)
template <typename TFile, typename TChar, typename TFragmentStore, typename TSpec> inline bool _readOneAnnotation ( TFile & file, TChar & c, IOContextUcsc_<TFragmentStore, TSpec> & ctx);       	// "core/include/seqan/store/store_io_ucsc.h"(149)

//____________________________________________________________________________
// _retrieveOneAnnotation

template <typename TFragmentStore, typename TSpec, typename TAnnotation, typename TId> inline bool _retrieveOneAnnotation ( TFragmentStore & fragStore, IOContextUcsc_<TFragmentStore, TSpec> & ctx, TAnnotation &annotation, TId id, Ucsc);       	// "core/include/seqan/store/store_io_ucsc.h"(441)
template <typename TFragmentStore, typename TSpec, typename TAnnotation, typename TId> inline bool _retrieveOneAnnotation ( TFragmentStore & fragStore, IOContextUcsc_<TFragmentStore, TSpec> & ctx, TAnnotation &annotation, TId id, UcscIsoforms);       	// "core/include/seqan/store/store_io_ucsc.h"(485)

//____________________________________________________________________________
// _storeAppendAnnotationName

template <typename TSpec, typename TConfig, typename TId, typename TName> inline void _storeAppendAnnotationName ( FragmentStore<TSpec, TConfig> & fragStore, TId & annotationId, TName & annotationName);       	// "core/include/seqan/store/store_all.h"(814)

//____________________________________________________________________________
// _storeAppendContig

template <typename TSpec, typename TConfig, typename TId, typename TName> inline void _storeAppendContig ( FragmentStore<TSpec, TConfig> & fragStore, TId & contigId, TName & rName);       	// "core/include/seqan/store/store_all.h"(786)

//____________________________________________________________________________
// _storeAppendKey

template <typename TSpec, typename TConfig, typename TId, typename TName> inline void _storeAppendKey ( FragmentStore<TSpec, TConfig> & fragStore, TId & keyId, TName & annotationKey);       	// "core/include/seqan/store/store_all.h"(856)

//____________________________________________________________________________
// _storeAppendRead

template <typename TSpec, typename TConfig, typename TId, typename TName, typename TString, typename TFlag, typename TContext> inline bool _storeAppendRead ( FragmentStore<TSpec, TConfig> & fragStore, TId & readId, TName const & qname, TString const & readSeq, TFlag const flag, TContext &);       	// "core/include/seqan/store/store_all.h"(691)

//____________________________________________________________________________
// _storeAppendType

template <typename TSpec, typename TConfig, typename TId, typename TName> inline void _storeAppendType ( FragmentStore<TSpec, TConfig> & fragStore, TId & typeId, TName & annotationType);       	// "core/include/seqan/store/store_all.h"(834)

//____________________________________________________________________________
// _storeClearAnnoBackLinks

template <typename TAnnotationStore> inline void _storeClearAnnoBackLinks(TAnnotationStore & me);       	// "core/include/seqan/store/store_annotation.h"(664)

//____________________________________________________________________________
// _storeClearAnnotations

template <typename TConfig, typename TSpec > inline void _storeClearAnnotations(FragmentStore<TSpec, TConfig> & me);       	// "core/include/seqan/store/store_all.h"(597)

//____________________________________________________________________________
// _storeCreateAnnoBackLinks

template <typename TAnnotationStore> inline void _storeCreateAnnoBackLinks(TAnnotationStore & me);       	// "core/include/seqan/store/store_annotation.h"(681)

//____________________________________________________________________________
// _storeOneAnnotation

template <typename TFragmentStore, typename TSpec> inline void _storeOneAnnotation ( TFragmentStore & fragStore, IOContextGff_<TFragmentStore, TSpec> & ctx);       	// "core/include/seqan/store/store_io_gff.h"(374)
template <typename TFragmentStore, typename TSpec> inline void _storeOneAnnotation ( TFragmentStore & fragStore, IOContextUcsc_<TFragmentStore, TSpec> & ctx);       	// "core/include/seqan/store/store_io_ucsc.h"(392)

//____________________________________________________________________________
// _storeOneAnnotationKnownGene

template <typename TFragmentStore, typename TSpec> inline void _storeOneAnnotationKnownGene ( TFragmentStore & fragStore, IOContextUcsc_<TFragmentStore, TSpec> & ctx);       	// "core/include/seqan/store/store_io_ucsc.h"(288)

//____________________________________________________________________________
// _storeOneAnnotationKnownIsoforms

template <typename TFragmentStore, typename TSpec> inline void _storeOneAnnotationKnownIsoforms ( TFragmentStore & fragStore, IOContextUcsc_<TFragmentStore, TSpec> & ctx);       	// "core/include/seqan/store/store_io_ucsc.h"(350)

//____________________________________________________________________________
// _storeRemoveTempAnnoNames

template <typename TConfig, typename TSpec > inline void _storeRemoveTempAnnoNames(FragmentStore<TSpec, TConfig> & me);       	// "core/include/seqan/store/store_all.h"(615)

//____________________________________________________________________________
// _writeAlignments

template <typename TFile, typename TSpec, typename TConfig, typename TDoAlign> inline void _writeAlignments(TFile & target, FragmentStore<TSpec, TConfig> & store, Sam, TDoAlign doAlign);       	// "core/include/seqan/store/store_io_sam.h"(1272)
template <typename TFile, typename TSpec, typename TConfig> inline void _writeAlignments(TFile & target, FragmentStore<TSpec, TConfig> & store, Sam);       	// "core/include/seqan/store/store_io_sam.h"(1566)

//____________________________________________________________________________
// _writeGffGtf

template <typename TTargetStream, typename TSpec, typename TConfig, typename TFormat> inline void _writeGffGtf ( TTargetStream & target, FragmentStore<TSpec, TConfig> & store, TFormat format);       	// "core/include/seqan/store/store_io_gff.h"(752)

//____________________________________________________________________________
// _writeHeader

template <typename TFile, typename TSpec, typename TConfig> inline void _writeHeader(TFile & target, FragmentStore<TSpec, TConfig> & store, Sam);       	// "core/include/seqan/store/store_io_sam.h"(1215)

//____________________________________________________________________________
// _writeOneAnnotation

template <typename TTargetStream, typename TSpec, typename TConfig, typename TAnnotation, typename TId> inline void _writeOneAnnotation ( TTargetStream & target, FragmentStore<TSpec, TConfig> & store, TAnnotation &annotation, TId id, Gff);       	// "core/include/seqan/store/store_io_gff.h"(503)
template <typename TTargetStream, typename TSpec, typename TConfig, typename TAnnotation, typename TId> inline void _writeOneAnnotation ( TTargetStream & target, FragmentStore<TSpec, TConfig> & store, TAnnotation &annotation, TId id, Gtf);       	// "core/include/seqan/store/store_io_gff.h"(608)
template <typename TTargetStream, typename TFragmentStore, typename TSpec> inline void _writeOneAnnotation ( TTargetStream & file, IOContextUcsc_<TFragmentStore, TSpec> & ctx);       	// "core/include/seqan/store/store_io_ucsc.h"(500)

//____________________________________________________________________________
// alignAndGetCigarString

template <typename TCigar, typename TMDString, typename TContig, typename TReadSeq, typename TErrors, typename TAlignedRead> inline void alignAndGetCigarString(TCigar &cigar, TMDString &md, TContig &contig, TReadSeq &readSeq, TAlignedRead &alignedRead, TErrors &errors, True);       	// "core/include/seqan/store/store_io_sam.h"(388)
template <typename TCigar, typename TMDString, typename TContig, typename TReadSeq, typename TErrors, typename TAlignedRead> inline void alignAndGetCigarString(TCigar &cigar, TMDString &md, TContig &contig, TReadSeq &readSeq, TAlignedRead &alignedRead, TErrors &, False);       	// "core/include/seqan/store/store_io_sam.h"(411)

//____________________________________________________________________________
// annotationAssignValueByKey

template <typename TSpec, typename TConfig, typename TAnnotation, typename TKey, typename TValue> inline void annotationAssignValueByKey ( FragmentStore<TSpec, TConfig> & fragStore, TAnnotation & annotation, TKey const & key, TValue const & value);       	// "core/include/seqan/store/store_all.h"(881)

//____________________________________________________________________________
// annotationGetValueByKey

template <typename TSpec, typename TConfig, typename TAnnotation, typename TKey, typename TValue> inline bool annotationGetValueByKey ( FragmentStore<TSpec, TConfig> & fragStore, TAnnotation const & annotation, TKey const & key, TValue & value);       	// "core/include/seqan/store/store_all.h"(899)
template <typename TSpec, typename TConfig, typename TAnnotation, typename TKey> inline CharString annotationGetValueByKey ( FragmentStore<TSpec, TConfig> & fragStore, TAnnotation const & annotation, TKey const & key);       	// "core/include/seqan/store/store_all.h"(923)

//____________________________________________________________________________
// appendAlignedRead

template <typename TSpec, typename TConfig, typename TReadId, typename TContigId, typename TPos, typename TPairMatchId> inline typename Size<typename FragmentStore<TSpec, TConfig>::TAlignedReadStore>::Type appendAlignedRead( FragmentStore<TSpec, TConfig> & store, TReadId const & readId, TContigId const & contigId, TPos const & beginPos, TPos const & endPos, TPairMatchId const & pairMatchId);       	// "core/include/seqan/store/store_all.h"(1097)
template <typename TSpec, typename TConfig, typename TReadId, typename TContigId, typename TPos> inline typename Size<typename FragmentStore<TSpec, TConfig>::TAlignedReadStore>::Type appendAlignedRead( FragmentStore<TSpec, TConfig> & store, TReadId const & readId, TContigId const & contigId, TPos const & beginPos, TPos const & endPos);       	// "core/include/seqan/store/store_all.h"(1117)

//____________________________________________________________________________
// appendAlignment

template <typename TSpec, typename TConfig, typename TId, typename TPos, typename TGaps> inline typename Size<typename FragmentStore<TSpec, TConfig>::TAlignedReadStore>::Type appendAlignment( FragmentStore<TSpec, TConfig> & fragStore, TId readId, TId contigId, TPos beginPos, TPos endPos, TGaps const & gaps);       	// "core/include/seqan/store/store_io_sam.h"(702)

//____________________________________________________________________________
// appendMatePair

template <typename TSpec, typename TConfig, typename TRead> inline typename Size<typename FragmentStore<TSpec, TConfig>::TMatePairStore>::Type appendMatePair( FragmentStore<TSpec, TConfig> &me, TRead const &read1, TRead const &read2);       	// "core/include/seqan/store/store_all.h"(1153)
template <typename TSpec, typename TConfig, typename TRead> inline typename Size<typename FragmentStore<TSpec, TConfig>::TMatePairStore>::Type appendMatePair( FragmentStore<TSpec, TConfig> &me, TRead const &read1, TRead const &read2, CharString const &name1, CharString const &name2);       	// "core/include/seqan/store/store_all.h"(1180)

//____________________________________________________________________________
// appendName

template <typename TNameStore, typename TName> inline void appendName(TNameStore &store, TName &name);       	// "core/include/seqan/store/store_all.h"(238)
template <typename TNameStore, typename TName, typename TContext> inline void appendName(TNameStore &store, TName &name, TContext &);       	// "core/include/seqan/store/store_all.h"(245)
template <typename TNameStore, typename TName, typename TCNameStore, typename TCName> inline void appendName(TNameStore &store, TName &name, NameStoreCache<TCNameStore, TCName> &context);       	// "core/include/seqan/store/store_all.h"(252)

//____________________________________________________________________________
// appendRead

template <typename TSpec, typename TConfig, typename TRead, typename TId> inline typename Size<typename FragmentStore<TSpec, TConfig>::TReadStore>::Type appendRead( FragmentStore<TSpec, TConfig> &me, TRead const &read, TId matePairId);       	// "core/include/seqan/store/store_all.h"(987)
template <typename TSpec, typename TConfig, typename TRead, typename TId> inline typename Size<typename FragmentStore<TSpec, TConfig>::TReadStore>::Type appendRead( FragmentStore<TSpec, TConfig> &me, TRead const &read, CharString const &name, TId matePairId);       	// "core/include/seqan/store/store_all.h"(1006)
template <typename TSpec, typename TConfig, typename TRead> inline typename Size<typename FragmentStore<TSpec, TConfig>::TReadStore>::Type appendRead( FragmentStore<TSpec, TConfig> &me, TRead const &read);       	// "core/include/seqan/store/store_all.h"(1024)
template <typename TSpec, typename TConfig, typename TRead> inline typename Size<typename FragmentStore<TSpec, TConfig>::TReadStore>::Type appendRead( FragmentStore<TSpec, TConfig> &me, TRead const &read, CharString const &name);       	// "core/include/seqan/store/store_all.h"(1037)

//____________________________________________________________________________
// assignValueByKey

template <typename TFragmentStore, typename TSpec, typename TKey, typename TValue> inline void assignValueByKey( Iter<TFragmentStore, AnnotationTree<TSpec> > & it, TKey const & key, TValue const & value);       	// "core/include/seqan/store/store_annotation.h"(252)

//____________________________________________________________________________
// atBegin

template <typename TFragmentStore, typename TSpec> inline bool atBegin(Iter<TFragmentStore, AnnotationTree<TSpec> > & it);       	// "core/include/seqan/store/store_annotation.h"(316)

//____________________________________________________________________________
// atEnd

template <typename TFragmentStore, typename TSpec> inline bool atEnd(Iter<TFragmentStore, AnnotationTree<TSpec> > & it);       	// "core/include/seqan/store/store_annotation.h"(323)

//____________________________________________________________________________
// begin

template <typename TConfig, typename TSpec, typename TIterSpec > inline typename Iterator<FragmentStore<TSpec, TConfig>, TIterSpec >::Type begin(FragmentStore<TSpec, TConfig> &store, TIterSpec const);       	// "core/include/seqan/store/store_all.h"(565)
template <typename TConfig, typename TSpec, typename TIterSpec > inline typename Iterator<FragmentStore<TSpec, TConfig> const, TIterSpec >::Type begin(FragmentStore<TSpec, TConfig> const &store, TIterSpec const);       	// "core/include/seqan/store/store_all.h"(572)

//____________________________________________________________________________
// buildAlignIntervalsStore

template <typename TAlignIntervalsStore, typename TSpec, typename TConfig > inline void buildAlignIntervalsStore(TAlignIntervalsStore & alignIntervalsStore, FragmentStore<TSpec, TConfig> & me, const unsigned & thresholdGaps);       	// "core/include/seqan/store/store_align_intervals.h"(88)

//____________________________________________________________________________
// calculateInsertSizes

template <typename TLibSizeString, typename TSpec, typename TConfig> inline void calculateInsertSizes(TLibSizeString &insertSizes, FragmentStore<TSpec, TConfig> &me);       	// "core/include/seqan/store/store_all.h"(1330)

//____________________________________________________________________________
// calculateMateIndices

template <typename TMateIndexString, typename TSpec, typename TConfig> inline void calculateMateIndices(TMateIndexString &mateIndices, FragmentStore<TSpec, TConfig> &me);       	// "core/include/seqan/store/store_all.h"(1414)

//____________________________________________________________________________
// cigarToGapAnchorContig

template <typename TCigarString, typename TGaps> inline unsigned cigarToGapAnchorContig(TCigarString const & cigar, TGaps & gaps);       	// "core/include/seqan/store/store_io_sam.h"(503)

//____________________________________________________________________________
// cigarToGapAnchorRead

template <typename TCigarString, typename TGaps> inline unsigned cigarToGapAnchorRead(TCigarString const & cigar, TGaps & gaps);       	// "core/include/seqan/store/store_io_sam.h"(477)

//____________________________________________________________________________
// clear

template <typename TFragmentStore, typename TSpec> inline void clear(Iter<TFragmentStore, AnnotationTree<TSpec> > & it);       	// "core/include/seqan/store/store_annotation.h"(304)
template <typename TFragmentStore, typename TSpec> inline void clear(IOContextGff_<TFragmentStore, TSpec> &ctx);       	// "core/include/seqan/store/store_io_gff.h"(183)
template <typename TFragmentStore, typename TSpec> inline void clear(IOContextUcsc_<TFragmentStore, TSpec> &ctx);       	// "core/include/seqan/store/store_io_ucsc.h"(126)

//____________________________________________________________________________
// clearReads

template <typename TSpec, typename TConfig> inline void clearReads(FragmentStore<TSpec, TConfig> &me);       	// "core/include/seqan/store/store_all.h"(954)

//____________________________________________________________________________
// clearValues

template <typename TFragmentStore, typename TSpec> inline void clearValues(Iter<TFragmentStore, AnnotationTree<TSpec> > & it);       	// "core/include/seqan/store/store_annotation.h"(242)

//____________________________________________________________________________
// compactAlignedReads

template <typename TSpec, typename TConfig> inline typename Size<typename FragmentStore<TSpec, TConfig>::TAlignedReadStore>::Type compactAlignedReads(FragmentStore<TSpec, TConfig> &me);       	// "core/include/seqan/store/store_all.h"(1226)

//____________________________________________________________________________
// compactPairMatchIds

template <typename TSpec, typename TConfig> inline typename Size<typename FragmentStore<TSpec, TConfig>::TAlignedReadStore>::Type compactPairMatchIds(FragmentStore<TSpec, TConfig> &me);       	// "core/include/seqan/store/store_all.h"(1283)

//____________________________________________________________________________
// container

template <typename TFragmentStore, typename TSpec> inline TFragmentStore & container(Iter< TFragmentStore, AnnotationTree<TSpec> > &it);       	// "core/include/seqan/store/store_annotation.h"(164)
template <typename TFragmentStore, typename TSpec> inline TFragmentStore & container(Iter< TFragmentStore, AnnotationTree<TSpec> > const &it);       	// "core/include/seqan/store/store_annotation.h"(170)

//____________________________________________________________________________
// convertMatchesToGlobalAlignment

template <typename TSpec, typename TConfig, typename TScore, typename TShrinkMatches> void convertMatchesToGlobalAlignment(FragmentStore<TSpec, TConfig> &store, TScore const & score, TShrinkMatches const &);       	// "core/include/seqan/store/store_all.h"(1712)

//____________________________________________________________________________
// convertPairWiseToGlobalAlignment

template <typename TSpec, typename TConfig, typename TContigGapsString> void convertPairWiseToGlobalAlignment(FragmentStore<TSpec, TConfig> &store, TContigGapsString &gaps);       	// "core/include/seqan/store/store_all.h"(2047)

//____________________________________________________________________________
// createIntervalTreeStore

template <typename TSpec, typename TConfig> inline void createIntervalTreeStore(FragmentStore<TSpec, TConfig> & me, const bool &unknownO);       	// "core/include/seqan/store/store_intervaltree.h"(50)

//____________________________________________________________________________
// createLeftChild

template <typename TFragmentStore, typename TSpec> inline Iter<TFragmentStore, AnnotationTree<TSpec> > createLeftChild(Iter<TFragmentStore, AnnotationTree<TSpec> > & it);       	// "core/include/seqan/store/store_annotation.h"(545)

//____________________________________________________________________________
// createRightChild

template <typename TFragmentStore, typename TSpec> inline Iter<TFragmentStore, AnnotationTree<TSpec> > createRightChild(Iter<TFragmentStore, AnnotationTree<TSpec> > & it);       	// "core/include/seqan/store/store_annotation.h"(568)

//____________________________________________________________________________
// createSibling

template <typename TFragmentStore, typename TSpec> inline Iter<TFragmentStore, AnnotationTree<TSpec> > createSibling(Iter<TFragmentStore, AnnotationTree<TSpec> > & it);       	// "core/include/seqan/store/store_annotation.h"(592)

//____________________________________________________________________________
// end

template <typename TConfig, typename TSpec, typename TIterSpec > inline typename Iterator<FragmentStore<TSpec, TConfig>, TIterSpec >::Type end(FragmentStore<TSpec, TConfig> &store, TIterSpec const);       	// "core/include/seqan/store/store_all.h"(581)
template <typename TConfig, typename TSpec, typename TIterSpec > inline typename Iterator<FragmentStore<TSpec, TConfig> const, TIterSpec >::Type end(FragmentStore<TSpec, TConfig> const &store, TIterSpec const);       	// "core/include/seqan/store/store_all.h"(588)

//____________________________________________________________________________
// extractAlignIntervals

template <typename TIntervals, typename TAlignedReadStoreElement, typename TSpec, typename TConfig> inline void extractAlignIntervals(TIntervals & contigIntervals, TAlignedReadStoreElement & align, FragmentStore<TSpec, TConfig> & me, const unsigned & thresholdGaps);       	// "core/include/seqan/store/store_align_intervals.h"(126)

//____________________________________________________________________________
// findIntervalsForInterval

template <typename TIntervalTree, typename TInterval, typename TCargo> inline void findIntervalsForInterval(String<TCargo> & result, TIntervalTree & intervalTree, TInterval & interval, const unsigned & offsetInterval);       	// "core/include/seqan/store/store_intervaltree.h"(179)

//____________________________________________________________________________
// getAnnoName

template <typename TSpec, typename TConfig, typename TId> inline typename GetValue<typename FragmentStore<TSpec, TConfig>::TAnnotationNameStore>::Type getAnnoName(FragmentStore<TSpec, TConfig> & store, TId id);       	// "core/include/seqan/store/store_all.h"(646)

//____________________________________________________________________________
// getAnnoType

template <typename TSpec, typename TConfig, typename TId> inline typename GetValue<typename FragmentStore<TSpec, TConfig>::TAnnotationTypeStore>::Type getAnnoType(FragmentStore<TSpec, TConfig> & store, TId id);       	// "core/include/seqan/store/store_all.h"(653)

//____________________________________________________________________________
// getAnnoUniqueName

template <typename TSpec, typename TConfig, typename TId> inline CharString getAnnoUniqueName(FragmentStore<TSpec, TConfig> & store, TId id);       	// "core/include/seqan/store/store_all.h"(660)

//____________________________________________________________________________
// getAnnotation

template <typename TFragmentStore, typename TSpec> inline typename Reference<typename TFragmentStore::TAnnotationStore>::Type getAnnotation(Iter<TFragmentStore, AnnotationTree<TSpec> > const & it);       	// "core/include/seqan/store/store_annotation.h"(179)

//____________________________________________________________________________
// getCigarString

template <typename TCigar, typename TGaps1, typename TGaps2, typename TThresh> inline void getCigarString( TCigar &cigar, TGaps1 &gaps1, TGaps2 &gaps2, TThresh splicedGapThresh);       	// "core/include/seqan/store/store_io_sam.h"(240)
template <typename TCigar, typename TGaps1, typename TGaps2> inline void getCigarString( TCigar &cigar, TGaps1 &gaps1, TGaps2 &gaps2);       	// "core/include/seqan/store/store_io_sam.h"(314)
template <typename TOperation, typename TCount, typename TSpec, typename TGaps1, typename TGaps2, typename TThresh> inline void getCigarString( String<CigarElement<TOperation, TCount>, TSpec> &cigar, TGaps1 &gaps1, TGaps2 &gaps2, TThresh splicedGapThresh);       	// "core/include/seqan/store/store_io_sam.h"(331)

//____________________________________________________________________________
// getClrRange

template <typename TSpec, typename TConfig, typename TPos, typename TGapAnchor, typename TSpecAlign, typename TBeginClr, typename TEndClr> inline void getClrRange(FragmentStore<TSpec, TConfig> const& fragStore, AlignedReadStoreElement<TPos, TGapAnchor, TSpecAlign> const& alignEl, TBeginClr& begClr, TEndClr& endClr);       	// "core/include/seqan/store/store_io.h"(100)

//____________________________________________________________________________
// getIdByName

template <typename TNameStore, typename TName, typename TPos> inline bool getIdByName(TNameStore const & store, TName const & name, TPos & pos);       	// "core/include/seqan/store/store_all.h"(171)
template <typename TNameStore, typename TName, typename TPos, typename TContext> inline bool getIdByName(TNameStore const & store, TName const & name, TPos & pos, TContext const & );       	// "core/include/seqan/store/store_all.h"(192)
template <typename TNameStore, typename TName, typename TPos, typename TCNameStore, typename TCName> inline bool getIdByName(TNameStore const & , TName const & name, TPos & pos, NameStoreCache<TCNameStore, TCName> const & context);       	// "core/include/seqan/store/store_all.h"(199)

//____________________________________________________________________________
// getMDString

template <typename TMDString, typename TGaps1, typename TGaps2> inline void getMDString( TMDString &md, TGaps1 &gaps1, TGaps2 &gaps2);       	// "core/include/seqan/store/store_io_sam.h"(173)

//____________________________________________________________________________
// getMateNo

template <typename TSpec, typename TConfig, typename TId> inline int getMateNo(FragmentStore<TSpec, TConfig> const &me, TId readId);       	// "core/include/seqan/store/store_all.h"(1376)

//____________________________________________________________________________
// getName

template <typename TFragmentStore, typename TSpec> inline typename GetValue<typename TFragmentStore::TAnnotationNameStore>::Type getName(Iter<TFragmentStore, AnnotationTree<TSpec> > const & it);       	// "core/include/seqan/store/store_annotation.h"(186)

//____________________________________________________________________________
// getParentName

template <typename TFragmentStore, typename TSpec> inline typename GetValue<typename TFragmentStore::TAnnotationNameStore>::Type getParentName(Iter<TFragmentStore, AnnotationTree<TSpec> > & it);       	// "core/include/seqan/store/store_annotation.h"(202)

//____________________________________________________________________________
// getRead

template <typename TSpec, typename TConfig, typename TId> inline typename Value<typename FragmentStore<TSpec, TConfig>::TReadSeqStore>::Type getRead( FragmentStore<TSpec, TConfig> &me, TId id);       	// "core/include/seqan/store/store_all.h"(1061)

//____________________________________________________________________________
// getType

template <typename TFragmentStore, typename TSpec> inline typename GetValue<typename TFragmentStore::TAnnotationTypeStore>::Type getType(Iter<TFragmentStore, AnnotationTree<TSpec> > const & it);       	// "core/include/seqan/store/store_annotation.h"(217)

//____________________________________________________________________________
// getUniqueName

template <typename TFragmentStore, typename TSpec> inline CharString getUniqueName(Iter<TFragmentStore, AnnotationTree<TSpec> > const & it);       	// "core/include/seqan/store/store_annotation.h"(233)

//____________________________________________________________________________
// getValueByKey

template <typename TFragmentStore, typename TSpec, typename TKey, typename TValue> inline bool getValueByKey( Iter<TFragmentStore, AnnotationTree<TSpec> > const & it, TKey const & key, TValue & value);       	// "core/include/seqan/store/store_annotation.h"(262)
template <typename TFragmentStore, typename TSpec, typename TKey> inline CharString getValueByKey( Iter<TFragmentStore, AnnotationTree<TSpec> > const & it, TKey const & key);       	// "core/include/seqan/store/store_annotation.h"(271)

//____________________________________________________________________________
// goBegin

template <typename TFragmentStore, typename TSpec> inline void goBegin(Iter<TFragmentStore, AnnotationTree<TSpec> > & it);       	// "core/include/seqan/store/store_annotation.h"(280)

//____________________________________________________________________________
// goDown

template <typename TFragmentStore, typename TSpec> inline bool goDown(Iter<TFragmentStore, AnnotationTree<TSpec> > & it);       	// "core/include/seqan/store/store_annotation.h"(399)

//____________________________________________________________________________
// goEnd

template <typename TFragmentStore, typename TSpec> inline void goEnd(Iter<TFragmentStore, AnnotationTree<TSpec> > & it);       	// "core/include/seqan/store/store_annotation.h"(287)

//____________________________________________________________________________
// goNext

template <typename TFragmentStore, typename TSpec> inline void goNext(Iter<TFragmentStore, AnnotationTree<TSpec> > & it);       	// "core/include/seqan/store/store_annotation.h"(335)

//____________________________________________________________________________
// goNextRight

template <typename TFragmentStore, typename TSpec> inline void goNextRight(Iter<TFragmentStore, AnnotationTree<TSpec> > & it);       	// "core/include/seqan/store/store_annotation.h"(348)

//____________________________________________________________________________
// goNextUp

template <typename TFragmentStore, typename TSpec> inline void goNextUp(Iter<TFragmentStore, AnnotationTree<TSpec> > & it);       	// "core/include/seqan/store/store_annotation.h"(361)

//____________________________________________________________________________
// goRight

template <typename TFragmentStore, typename TSpec> inline bool goRight(Iter<TFragmentStore, AnnotationTree<TSpec> > & it);       	// "core/include/seqan/store/store_annotation.h"(416)

//____________________________________________________________________________
// goRoot

template <typename TFragmentStore, typename TSpec> inline void goRoot(Iter<TFragmentStore, AnnotationTree<TSpec> > & it);       	// "core/include/seqan/store/store_annotation.h"(375)

//____________________________________________________________________________
// goTo

template <typename TFragmentStore, typename TSpec, typename TId> inline void goTo(Iter<TFragmentStore, AnnotationTree<TSpec> > & it, TId _id);       	// "core/include/seqan/store/store_annotation.h"(297)

//____________________________________________________________________________
// goUp

template <typename TFragmentStore, typename TSpec> inline bool goUp(Iter<TFragmentStore, AnnotationTree<TSpec> > & it);       	// "core/include/seqan/store/store_annotation.h"(382)

//____________________________________________________________________________
// isLastChild

template <typename TFragmentStore, typename TSpec> inline bool isLastChild(Iter<TFragmentStore, AnnotationTree<TSpec> > const & it);       	// "core/include/seqan/store/store_annotation.h"(644)

//____________________________________________________________________________
// isLeaf

template <typename TFragmentStore, typename TSpec> inline bool isLeaf(Iter<TFragmentStore, AnnotationTree<TSpec> > const & it);       	// "core/include/seqan/store/store_annotation.h"(633)

//____________________________________________________________________________
// isRoot

template <typename TFragmentStore, typename TSpec> inline bool isRoot(Iter<TFragmentStore, AnnotationTree<TSpec> > const & it);       	// "core/include/seqan/store/store_annotation.h"(622)

//____________________________________________________________________________
// layoutAlignment

template <typename TSpec, typename TConfig> void layoutAlignment(AlignedReadLayout &layout, FragmentStore<TSpec, TConfig> &store);       	// "core/include/seqan/store/store_all.h"(1479)

//____________________________________________________________________________
// loadContig

template <typename TSpec, typename TConfig, typename TId> bool loadContig(FragmentStore<TSpec, TConfig> &store, TId _id);       	// "core/include/seqan/store/store_io.h"(968)

//____________________________________________________________________________
// loadContigs

template <typename TFSSpec, typename TFSConfig> bool loadContigs(FragmentStore<TFSSpec, TFSConfig> &store, StringSet<CharString> const &fileNameList, bool loadSeqs);       	// "core/include/seqan/store/store_io.h"(886)
template <typename TFSSpec, typename TFSConfig> bool loadContigs(FragmentStore<TFSSpec, TFSConfig> &store, CharString const &fileName, bool loadSeqs);       	// "core/include/seqan/store/store_io.h"(937)
template <typename TFSSpec, typename TFSConfig, typename TFileNames> bool loadContigs(FragmentStore<TFSSpec, TFSConfig> &store, TFileNames const &fileNames);       	// "core/include/seqan/store/store_io.h"(947)

//____________________________________________________________________________
// loadReads

template <typename TFSSpec, typename TFSConfig, typename TFileName> bool loadReads(FragmentStore<TFSSpec, TFSConfig> &store, TFileName &fileName);       	// "core/include/seqan/store/store_io.h"(1156)
template <typename TFSSpec, typename TFSConfig, typename TFileName> bool loadReads(FragmentStore<TFSSpec, TFSConfig> & store, TFileName & fileNameL, TFileName & fileNameR);       	// "core/include/seqan/store/store_io.h"(1200)

//____________________________________________________________________________
// lockContig

template <typename TSpec, typename TConfig, typename TId> bool lockContig(FragmentStore<TSpec, TConfig> &store, TId _id);       	// "core/include/seqan/store/store_io.h"(1004)

//____________________________________________________________________________
// lockContigs

template <typename TSpec, typename TConfig> bool lockContigs(FragmentStore<TSpec, TConfig> &store);       	// "core/include/seqan/store/store_io.h"(1085)

//____________________________________________________________________________
// lowerBoundAlignedReads

template <typename TAlign, typename TSearchValue> inline typename Iterator<TAlign, Standard>::Type lowerBoundAlignedReads(TAlign const& alignStore, TSearchValue const val, SortId);       	// "core/include/seqan/store/store_align.h"(478)
template <typename TAlign, typename TSearchValue> inline typename Iterator<TAlign, Standard>::Type lowerBoundAlignedReads(TAlign const& alignStore, TSearchValue const val, SortContigId);       	// "core/include/seqan/store/store_align.h"(514)
template <typename TAlign, typename TSearchValue> inline typename Iterator<TAlign, Standard>::Type lowerBoundAlignedReads(TAlign const& alignStore, TSearchValue const val, SortBeginPos);       	// "core/include/seqan/store/store_align.h"(550)
template <typename TAlign, typename TSearchValue> inline typename Iterator<TAlign, Standard>::Type lowerBoundAlignedReads(TAlign const& alignStore, TSearchValue const val, SortEndPos);       	// "core/include/seqan/store/store_align.h"(589)
template <typename TAlign, typename TSearchValue> inline typename Iterator<TAlign, Standard>::Type lowerBoundAlignedReads(TAlign const& alignStore, TSearchValue const val, SortPairMatchId);       	// "core/include/seqan/store/store_align.h"(628)
template <typename TAlign, typename TSearchValue> inline typename Iterator<TAlign, Standard>::Type lowerBoundAlignedReads(TAlign const& alignStore, TSearchValue const val, SortReadId);       	// "core/include/seqan/store/store_align.h"(664)
template <typename T, typename TSpec, typename TSearchValue> inline Iter<T, TSpec> lowerBoundAlignedReads(Iter<T, TSpec> const & alignedReadsItBegin, Iter<T, TSpec> const & alignedReadsItEnd, TSearchValue const val, SortId);       	// "core/include/seqan/store/store_align.h"(701)
template <typename T, typename TSpec, typename TSearchValue> inline Iter<T, TSpec> lowerBoundAlignedReads(Iter<T, TSpec> const & alignedReadsItBegin, Iter<T, TSpec> const & alignedReadsItEnd, TSearchValue const val, SortContigId);       	// "core/include/seqan/store/store_align.h"(739)
template <typename T, typename TSpec, typename TSearchValue> inline Iter<T, TSpec> lowerBoundAlignedReads(Iter<T, TSpec> const & alignedReadsItBegin, Iter<T, TSpec> const & alignedReadsItEnd, TSearchValue const val, SortBeginPos);       	// "core/include/seqan/store/store_align.h"(777)
template <typename T, typename TSpec, typename TSearchValue> inline Iter<T, TSpec> lowerBoundAlignedReads(Iter<T, TSpec> const & alignedReadsItBegin, Iter<T, TSpec> const & alignedReadsItEnd, TSearchValue const val, SortEndPos);       	// "core/include/seqan/store/store_align.h"(818)
template <typename T, typename TSpec, typename TSearchValue> inline Iter<T, TSpec> lowerBoundAlignedReads(Iter<T, TSpec> const & alignedReadsItBegin, Iter<T, TSpec> const & alignedReadsItEnd, TSearchValue const val, SortPairMatchId);       	// "core/include/seqan/store/store_align.h"(859)
template <typename T, typename TSpec, typename TSearchValue> inline Iter<T, TSpec> lowerBoundAlignedReads(Iter<T, TSpec> const & alignedReadsItBegin, Iter<T, TSpec> const & alignedReadsItEnd, TSearchValue const val, SortReadId);       	// "core/include/seqan/store/store_align.h"(897)
template <typename TReadAlignElement, typename TSearchValue> inline TReadAlignElement * lowerBoundAlignedReads(TReadAlignElement * const & alignedReadsItBegin, TReadAlignElement * const & alignedReadsItEnd, TSearchValue const val, SortId);       	// "core/include/seqan/store/store_align.h"(935)
template <typename TReadAlignElement, typename TSearchValue> inline TReadAlignElement * lowerBoundAlignedReads(TReadAlignElement * const & alignedReadsItBegin, TReadAlignElement * const & alignedReadsItEnd, TSearchValue const val, SortContigId);       	// "core/include/seqan/store/store_align.h"(973)
template <typename TReadAlignElement, typename TSearchValue> inline TReadAlignElement * lowerBoundAlignedReads(TReadAlignElement * const & alignedReadsItBegin, TReadAlignElement * const & alignedReadsItEnd, TSearchValue const val, SortBeginPos);       	// "core/include/seqan/store/store_align.h"(1011)
template <typename TReadAlignElement, typename TSearchValue> inline TReadAlignElement * lowerBoundAlignedReads(TReadAlignElement * const & alignedReadsItBegin, TReadAlignElement * const & alignedReadsItEnd, TSearchValue const val, SortEndPos);       	// "core/include/seqan/store/store_align.h"(1052)
template <typename TReadAlignElement, typename TSearchValue> inline TReadAlignElement * lowerBoundAlignedReads(TReadAlignElement * const & alignedReadsItBegin, TReadAlignElement * const & alignedReadsItEnd, TSearchValue const val, SortPairMatchId);       	// "core/include/seqan/store/store_align.h"(1093)
template <typename TReadAlignElement, typename TSearchValue> inline TReadAlignElement * lowerBoundAlignedReads(TReadAlignElement * const & alignedReadsItBegin, TReadAlignElement * const & alignedReadsItEnd, TSearchValue const val, SortReadId);       	// "core/include/seqan/store/store_align.h"(1131)

//____________________________________________________________________________
// mergeIntervals

template <typename TIntervals> inline void mergeIntervals(TIntervals & intervals, const unsigned & thresholdGaps);       	// "core/include/seqan/store/store_align_intervals.h"(331)

//____________________________________________________________________________
// nodeDown

template <typename TFragmentStore, typename TSpec> inline Iter<TFragmentStore, AnnotationTree<TSpec> > nodeDown(Iter<TFragmentStore, AnnotationTree<TSpec> > const & it);       	// "core/include/seqan/store/store_annotation.h"(449)

//____________________________________________________________________________
// nodeRight

template <typename TFragmentStore, typename TSpec> inline Iter<TFragmentStore, AnnotationTree<TSpec> > nodeRight(Iter<TFragmentStore, AnnotationTree<TSpec> > const & it);       	// "core/include/seqan/store/store_annotation.h"(458)

//____________________________________________________________________________
// nodeUp

template <typename TFragmentStore, typename TSpec> inline Iter<TFragmentStore, AnnotationTree<TSpec> > nodeUp(Iter<TFragmentStore, AnnotationTree<TSpec> > const & it);       	// "core/include/seqan/store/store_annotation.h"(440)

//____________________________________________________________________________
// operator<

template <typename TValue> inline bool operator< (Interval<TValue> const & interval1, Interval<TValue> const & interval2);       	// "core/include/seqan/store/store_align_intervals.h"(64)
template <typename TOperation, typename TCount> inline bool operator<(CigarElement<TOperation, TCount> const & lhs, CigarElement<TOperation, TCount> const & rhs);       	// "core/include/seqan/store/store_io_sam.h"(133)

//____________________________________________________________________________
// operator<<

template <typename TStream, typename TPos, typename TGapAnchor, typename TSpec> TStream & operator<<(TStream & stream, AlignedReadStoreElement<TPos, TGapAnchor, TSpec> const & e);       	// "core/include/seqan/store/store_align.h"(171)

//____________________________________________________________________________
// operator==

template <typename TValue> inline bool operator== (Interval<TValue> const & interval1, Interval<TValue> const & interval2);       	// "core/include/seqan/store/store_align_intervals.h"(57)
template <typename TOperation, typename TCount> inline bool operator==(CigarElement<TOperation, TCount> const & lhs, CigarElement<TOperation, TCount> const & rhs);       	// "core/include/seqan/store/store_io_sam.h"(140)

//____________________________________________________________________________
// operator>

template <typename TOperation, typename TCount> inline bool operator>(CigarElement<TOperation, TCount> const & lhs, CigarElement<TOperation, TCount> const & rhs);       	// "core/include/seqan/store/store_io_sam.h"(126)

//____________________________________________________________________________
// printAlignment

template <typename TStream, typename TFormatTag, typename TSpec, typename TConfig, typename TContigId, typename TPos, typename TNum> void printAlignment( TStream &stream, Tag<TFormatTag> const &format, AlignedReadLayout &layout, FragmentStore<TSpec, TConfig> &store, TContigId contigId, TPos posBegin, TPos posEnd, TNum lineBegin, TNum lineEnd);       	// "core/include/seqan/store/store_all.h"(1588)

//____________________________________________________________________________
// read

template <typename TFile, typename TSpec, typename TConfig> inline void read(TFile & file, FragmentStore<TSpec, TConfig>& fragStore, Amos);       	// "core/include/seqan/store/store_io.h"(158)
template <typename TFile, typename TSpec, typename TConfig> inline void read ( TFile & file, FragmentStore<TSpec, TConfig> & fragStore, Gff);       	// "core/include/seqan/store/store_io_gff.h"(456)
template <typename TFile, typename TSpec, typename TConfig> inline void read ( TFile & file, FragmentStore<TSpec, TConfig> & fragStore, Gtf);       	// "core/include/seqan/store/store_io_gff.h"(486)
template <typename TFile, typename TSpec, typename TConfig> inline void read( TFile & file, FragmentStore<TSpec, TConfig> & fragStore, Sam);       	// "core/include/seqan/store/store_io_sam.h"(875)
template <typename TFile, typename TSpec, typename TConfig, typename TFormatSpec> inline void read ( TFile & file, FragmentStore<TSpec, TConfig> & fragStore, Tag<Ucsc_<TFormatSpec> > const);       	// "core/include/seqan/store/store_io_ucsc.h"(405)

//____________________________________________________________________________
// refresh

template <typename TNameStore, typename TName> inline void refresh(NameStoreCache<TNameStore, TName> &cache);       	// "core/include/seqan/store/store_all.h"(140)

//____________________________________________________________________________
// setName

template <typename TFragmentStore, typename TSpec, typename TName> inline typename GetValue<typename TFragmentStore::TAnnotationNameStore>::Type setName(Iter<TFragmentStore, AnnotationTree<TSpec> > const & it, TName & name);       	// "core/include/seqan/store/store_annotation.h"(193)

//____________________________________________________________________________
// setType

template <typename TFragmentStore, typename TSpec, typename TTypeName> inline void setType(Iter<TFragmentStore, AnnotationTree<TSpec> > const & it, TTypeName & typeName);       	// "core/include/seqan/store/store_annotation.h"(224)

//____________________________________________________________________________
// sortAlignedReads

template <typename TAlign, typename TSortSpec> inline void sortAlignedReads(TAlign& alignStore, Tag<TSortSpec> const &);       	// "core/include/seqan/store/store_align.h"(432)
template <typename TAlign, typename TSortSpec> inline void sortAlignedReads(TAlign const & alignStore, Tag<TSortSpec> const &);       	// "core/include/seqan/store/store_align.h"(444)
template <typename TAlign, typename TFunctorLess> inline void sortAlignedReads(TAlign & alignStore, TFunctorLess const &less);       	// "core/include/seqan/store/store_align.h"(454)
template <typename TAlign, typename TFunctorLess> inline void sortAlignedReads(TAlign const & alignStore, TFunctorLess const &less);       	// "core/include/seqan/store/store_align.h"(464)

//____________________________________________________________________________
// swap

template <typename TPos, typename TGapAnchor, typename TSpec> inline void swap( AlignedReadStoreElement<TPos, TGapAnchor, TSpec> &a, AlignedReadStoreElement<TPos, TGapAnchor, TSpec> &b);       	// "core/include/seqan/store/store_align.h"(300)

//____________________________________________________________________________
// toBamCigarElement

template <typename TOperation, typename TCount> __uint32 toBamCigarElement(CigarElement<TOperation, TCount> const & cigarElement);       	// "core/include/seqan/store/store_io_sam.h"(146)

//____________________________________________________________________________
// unlockAndFreeContig

template <typename TSpec, typename TConfig, typename TId> bool unlockAndFreeContig(FragmentStore<TSpec, TConfig> &store, TId _id);       	// "core/include/seqan/store/store_io.h"(1054)

//____________________________________________________________________________
// unlockAndFreeContigs

template <typename TSpec, typename TConfig> bool unlockAndFreeContigs(FragmentStore<TSpec, TConfig> &store);       	// "core/include/seqan/store/store_io.h"(1127)

//____________________________________________________________________________
// unlockContig

template <typename TSpec, typename TConfig, typename TId> bool unlockContig(FragmentStore<TSpec, TConfig> &store, TId _id);       	// "core/include/seqan/store/store_io.h"(1033)

//____________________________________________________________________________
// unlockContigs

template <typename TSpec, typename TConfig> bool unlockContigs(FragmentStore<TSpec, TConfig> &store);       	// "core/include/seqan/store/store_io.h"(1106)

//____________________________________________________________________________
// upperBoundAlignedReads

template <typename TAlign, typename TSearchValue> inline typename Iterator<TAlign, Standard>::Type upperBoundAlignedReads(TAlign const& alignStore, TSearchValue const val, SortId);       	// "core/include/seqan/store/store_align.h"(496)
template <typename TAlign, typename TSearchValue> inline typename Iterator<TAlign, Standard>::Type upperBoundAlignedReads(TAlign const& alignStore, TSearchValue const val, SortContigId);       	// "core/include/seqan/store/store_align.h"(532)
template <typename TAlign, typename TSearchValue> inline typename Iterator<TAlign, Standard>::Type upperBoundAlignedReads(TAlign const& alignStore, TSearchValue const val, SortBeginPos);       	// "core/include/seqan/store/store_align.h"(569)
template <typename TAlign, typename TSearchValue> inline typename Iterator<TAlign, Standard>::Type upperBoundAlignedReads(TAlign const& alignStore, TSearchValue const val, SortEndPos);       	// "core/include/seqan/store/store_align.h"(608)
template <typename TAlign, typename TSearchValue> inline typename Iterator<TAlign, Standard>::Type upperBoundAlignedReads(TAlign const& alignStore, TSearchValue const val, SortPairMatchId);       	// "core/include/seqan/store/store_align.h"(646)
template <typename TAlign, typename TSearchValue> inline typename Iterator<TAlign, Standard>::Type upperBoundAlignedReads(TAlign const& alignStore, TSearchValue const val, SortReadId);       	// "core/include/seqan/store/store_align.h"(682)
template <typename T, typename TSpec, typename TSearchValue> inline Iter<T, TSpec> upperBoundAlignedReads(Iter<T, TSpec> const & alignedReadsItBegin, Iter<T, TSpec> const & alignedReadsItEnd, TSearchValue const val, SortId);       	// "core/include/seqan/store/store_align.h"(720)
template <typename T, typename TSpec, typename TSearchValue> inline Iter<T, TSpec> upperBoundAlignedReads(Iter<T, TSpec> const & alignedReadsItBegin, Iter<T, TSpec> const & alignedReadsItEnd, TSearchValue const val, SortContigId);       	// "core/include/seqan/store/store_align.h"(758)
template <typename T, typename TSpec, typename TSearchValue> inline Iter<T, TSpec> upperBoundAlignedReads(Iter<T, TSpec> const & alignedReadsItBegin, Iter<T, TSpec> const & alignedReadsItEnd, TSearchValue const val, SortBeginPos);       	// "core/include/seqan/store/store_align.h"(797)
template <typename T, typename TSpec, typename TSearchValue> inline Iter<T, TSpec> upperBoundAlignedReads(Iter<T, TSpec> const & alignedReadsItBegin, Iter<T, TSpec> const & alignedReadsItEnd, TSearchValue const val, SortEndPos);       	// "core/include/seqan/store/store_align.h"(838)
template <typename T, typename TSpec, typename TSearchValue> inline Iter<T, TSpec> upperBoundAlignedReads(Iter<T, TSpec> const & alignedReadsItBegin, Iter<T, TSpec> const & alignedReadsItEnd, TSearchValue const val, SortPairMatchId);       	// "core/include/seqan/store/store_align.h"(878)
template <typename T, typename TSpec, typename TSearchValue> inline Iter<T, TSpec> upperBoundAlignedReads(Iter<T, TSpec> const & alignedReadsItBegin, Iter<T, TSpec> const & alignedReadsItEnd, TSearchValue const val, SortReadId);       	// "core/include/seqan/store/store_align.h"(916)
template <typename TReadAlignElement, typename TSearchValue> inline TReadAlignElement * upperBoundAlignedReads(TReadAlignElement * const & alignedReadsItBegin, TReadAlignElement * const & alignedReadsItEnd, TSearchValue const val, SortId);       	// "core/include/seqan/store/store_align.h"(954)
template <typename TReadAlignElement, typename TSearchValue> inline TReadAlignElement * upperBoundAlignedReads(TReadAlignElement * const & alignedReadsItBegin, TReadAlignElement * const & alignedReadsItEnd, TSearchValue const val, SortContigId);       	// "core/include/seqan/store/store_align.h"(992)
template <typename TReadAlignElement, typename TSearchValue> inline TReadAlignElement * upperBoundAlignedReads(TReadAlignElement * const & alignedReadsItBegin, TReadAlignElement * const & alignedReadsItEnd, TSearchValue const val, SortBeginPos);       	// "core/include/seqan/store/store_align.h"(1031)
template <typename TReadAlignElement, typename TSearchValue> inline TReadAlignElement * upperBoundAlignedReads(TReadAlignElement * const & alignedReadsItBegin, TReadAlignElement * const & alignedReadsItEnd, TSearchValue const val, SortEndPos);       	// "core/include/seqan/store/store_align.h"(1072)
template <typename TReadAlignElement, typename TSearchValue> inline TReadAlignElement * upperBoundAlignedReads(TReadAlignElement * const & alignedReadsItBegin, TReadAlignElement * const & alignedReadsItEnd, TSearchValue const val, SortPairMatchId);       	// "core/include/seqan/store/store_align.h"(1112)
template <typename TReadAlignElement, typename TSearchValue> inline TReadAlignElement * upperBoundAlignedReads(TReadAlignElement * const & alignedReadsItBegin, TReadAlignElement * const & alignedReadsItEnd, TSearchValue const val, SortReadId);       	// "core/include/seqan/store/store_align.h"(1150)

//____________________________________________________________________________
// value

template <typename TFragmentStore, typename TSpec> inline typename VertexDescriptor<TFragmentStore>::Type & value(Iter< TFragmentStore, AnnotationTree<TSpec> > &it);       	// "core/include/seqan/store/store_annotation.h"(150)
template <typename TFragmentStore, typename TSpec> inline typename VertexDescriptor<TFragmentStore>::Type const & value(Iter< TFragmentStore, AnnotationTree<TSpec> > const &it);       	// "core/include/seqan/store/store_annotation.h"(156)

//____________________________________________________________________________
// write

template <typename TFile, typename TSpec, typename TConfig> inline void write(TFile & target, FragmentStore<TSpec, TConfig>& fragStore, Amos);       	// "core/include/seqan/store/store_io.h"(578)
template <typename TTargetStream, typename TSpec, typename TConfig> inline void write ( TTargetStream & target, FragmentStore<TSpec, TConfig> & store, Gff format);       	// "core/include/seqan/store/store_io_gff.h"(773)
template <typename TTargetStream, typename TSpec, typename TConfig> inline void write ( TTargetStream & target, FragmentStore<TSpec, TConfig> & store, Gtf format);       	// "core/include/seqan/store/store_io_gff.h"(784)
template <typename TFile, typename TSpec, typename TConfig> inline void write(TFile & target, FragmentStore<TSpec, TConfig> & store, Sam);       	// "core/include/seqan/store/store_io_sam.h"(1579)
template <typename TTargetStream, typename TSpec, typename TConfig, typename TFormatSpec> inline void write ( TTargetStream & target, FragmentStore<TSpec, TConfig> & store, Tag<Ucsc_<TFormatSpec> > const format);       	// "core/include/seqan/store/store_io_ucsc.h"(595)

//____________________________________________________________________________
// writeContigs

template <typename TStream, typename TFSSpec, typename TFSConfig, typename TFormat> bool writeContigs(TStream & file, FragmentStore<TFSSpec, TFSConfig> & store, TFormat const &);       	// "core/include/seqan/store/store_io.h"(854)

} //namespace SEQAN_NAMESPACE_MAIN
//////////////////////////////////////////////////////////////////////////////

namespace seqan {

//____________________________________________________________________________
// _readAlignments

template <typename TSpec, typename TConfig, typename TContigAnchorGaps, typename TMatchMateInfos> inline void _readAlignments( samfile_t * file, FragmentStore<TSpec, TConfig> & fragStore, TContigAnchorGaps & contigAnchorGaps, TMatchMateInfos & matchMateInfos, Bam const &);       	// "core/include/seqan/store/store_io_bam.h"(109)

//____________________________________________________________________________
// _readOneAlignment

template <typename TSpec, typename TConfig, typename TContigAnchorGaps, typename TMatchMateInfos, typename TContextBAM> inline void _readOneAlignment ( samfile_t * file, bam1_t * record, FragmentStore<TSpec, TConfig> & fragStore, TContigAnchorGaps & contigAnchorGaps, TMatchMateInfos & matchMateInfos, Bam const &, TContextBAM & contextBam);       	// "core/include/seqan/store/store_io_bam.h"(155)

//____________________________________________________________________________
// _writeAlignments

template <typename TSpec, typename TConfig> inline void _writeAlignments(samfile_t * , FragmentStore<TSpec, TConfig> & store, Bam const &);       	// "core/include/seqan/store/store_io_bam.h"(415)

//____________________________________________________________________________
// read

template <typename TSpec, typename TConfig> inline void read(samfile_t * file, FragmentStore<TSpec, TConfig> & fragStore, Bam const &);       	// "core/include/seqan/store/store_io_bam.h"(73)

//____________________________________________________________________________
// write

template <typename TSpec, typename TConfig> inline void write(char const * fileName, FragmentStore<TSpec, TConfig> & fragStore, Bam const &);       	// "core/include/seqan/store/store_io_bam.h"(373)

} //namespace seqan

#endif

